// <auto-generated>
//     Generated by the protocol buffer compiler.  DO NOT EDIT!
//     source: errorNo.proto
// </auto-generated>
#pragma warning disable 1591, 0612, 3021
#region Designer generated code

using pb = global::Google.Protobuf;
using pbc = global::Google.Protobuf.Collections;
using pbr = global::Google.Protobuf.Reflection;
using scg = global::System.Collections.Generic;
namespace ErrorNo {

  /// <summary>Holder for reflection information generated from errorNo.proto</summary>
  public static partial class ErrorNoReflection {

    #region Descriptor
    /// <summary>File descriptor for errorNo.proto</summary>
    public static pbr::FileDescriptor Descriptor {
      get { return descriptor; }
    }
    private static pbr::FileDescriptor descriptor;

    static ErrorNoReflection() {
      byte[] descriptorData = global::System.Convert.FromBase64String(
          string.Concat(
            "Cg1lcnJvck5vLnByb3RvEgdlcnJvck5vKu5pCgdFcnJvck5vEgsKB1N1Y2Nl",
            "c3MQABIPCgtGYWlsZWRMb2dpbhABEhAKDEluY29ycmVjdFBXRBACEhcKE0Zh",
            "aWxlZENyZWF0ZUFjY291bnQQAxIWChJGYWlsZWRDcmVhdGVQbGF5ZXIQBBIT",
            "Cg9Ob3RGb3VuZEFjY291bnQQBRIVChFDcmVhdGVQbGF5ZXJMaW1pdBAGEhYK",
            "EkZhaWxlZFVwZGF0ZURCRGF0YRAHEhIKDk5vdEZvdW5kUGxheWVyEAgSFAoQ",
            "RmFpbGVkSW5pdFBsYXllchAJEhQKEE5vdEZvdW5kTWF0Y2hTcnYQChIUChBO",
            "b3RGb3VuZFNjZW5lU3J2EAsSFgoSRmFpbGVkQ3JlYXRlQmF0dGxlEAwSDwoL",
            "Tm90SW5DZW50ZXIQDRISCg5OYW1lQWxyZWFkeVVzZRAOEhQKEEZhaWxlZENy",
            "ZWF0ZU5hbWUQDxIUChBOb3RGb3VuZExvZ2luS2V5EBASEQoNTmFtZUlzSW5W",
            "YWxpZBAREhUKEUZhaWxlZExvZ2luQmF0dGxlEBISFgoSTm90Rm91bmRCYXR0",
            "bGVSb29tEBMSEAoMQWxyZWFkeUZpZ2h0EBQSGgoWTm90Rm91bmRQbGF5ZXJJ",
            "bkJhdHRsZRAVEg8KC0ludmFsaWRJdGVtEBYSEgoOSGFzQWxyZWFkeUl0ZW0Q",
            "FxIRCg1JbnZhbGlkSGVyb0lkEBgSCwoHQmFnRnVsbBAZEhAKDE1hdGNoVGlt",
            "ZW91dBAaEhIKDkludmFsaWRTa2lsbElEEBsSEQoNTm90Rm91bmRJbkJhZxAd",
            "Eg0KCUZhaWxlZENNRBAeEhEKDU5vdEVub3VnaEl0ZW0QIxIRCg1GYWlsZWRV",
            "c2VJdGVtECQSEAoMQWxyZWFkeU1heEx2ECUSEgoORmFpbGVkRXF1aXBHZW0Q",
            "JhIUChBGYWlsZWRVbmVxdWlwR2VtECcSDwoLRmFpbGVkR2VtTFYQKBISCg5G",
            "YWlsZWRFcXVpcEFueRAqEhQKEEZhaWxlZFVuZXF1aXBBbnkQKxINCglOb3RP",
            "bmxpbmUQMRIXChNGYWlsZWRUb1BsYXllckxvZ2luEDISEAoMTm90Rm91bmRI",
            "ZXJvEDMSEAoMSGVyb1N0YXJGdWxsEDQSEQoNQmF0dGxlVGltZW91dBA1EhkK",
            "FUZhaWxlZENyZWF0ZVBWRUJhdHRsZRA2EhkKFVBsYXllckFscmVhZHlJbkJh",
            "dHRsZRA3EhcKE0ZhaWxlZFRvQ2hlY2tSZXBvcnQQOBIUChBBdGxhc0FjdGl2",
            "ZUxpbWl0EDkSFAoQRmFpbGVkVG9Mb2NrSXRlbRA6EgsKB0hhc0hlcm8QOxIZ",
            "ChVJbnN1ZmZpY2llbnRDb25kaXRpb24QPBISCg5Ob3RFbm91Z2hTdGFycxA9",
            "EhIKDk5vdEVub3VnaFBvd2VyED4SEgoOTm90RW5vdWdoTGV2ZWwQPxITCg9G",
            "YWlsZWRUb0RlbERhdGEQQBIXChNGYWlsZWRUb0dldE1haWxJdGVtEEESFAoQ",
            "RmFpbGVkRXF1aXBTdGFtcBBCEhYKEkZhaWxlZFVuZXF1aXBTdGFtcBBDEhUK",
            "EUZhaWxlZFN0YW1wVXBTdGFyEEQSEAoMU3RhbXBTdGFyTWF4EEUSEAoMTm90",
            "RW5vdWdoR2VtEEYSEgoOQWxyZWFkeUVxdWlwS1QQRxITCg9GYWlsZWRTZWxs",
            "VG9TeXMQSBIQCgxBbHJlYWR5QnV5S1QQSRIOCgpLVEJhZ0xpbWl0EEoSFQoR",
            "RmFpbGVkVG9FcXVpcEx2VXAQSxIQCgxOZWVkRW1iYXR0bGUQTBISCg5JbnZh",
            "bGlkTGV2ZWxJRBBNEhwKGFRvd2VyQWZ0ZXJMZXZlbE5vdEZpbmlzaBBOEhMK",
            "D1N1cnBhc3NQbGF5ZXJMdhBPEhoKFkZhaWxlZFRvUmVmcmVzaEtUUFNob3AQ",
            "UBIXChNOb3RGaW5pc2hUb3dlckxldmVsEFESGAoURmFpbGVkVG9DaGVja1Nh",
            "blhpYW8QUhIVChFFbWJhdHRsZUhlcm9MaW1pdBBTEhMKD05vdEVub3VnaEtU",
            "Q29pbhBUEhYKEkZhaWxlZFRvR29kTGV2ZWxVcBBVEhYKEk9wcG9lbnRSYW5r",
            "SW52YWxpZBBWEhcKE05vdEZvdW5kQmF0dGxlVmlkZW8QVxITCg9JbnZhbGlk",
            "SXRlbVR5cGUQWBIVChFJbnZhbGlkU2FuWGlhb0tleRBZEhUKEUZhaWxlZFNh",
            "dmVTYW5YaWFvEFoSFAoQRmFpbGVkUmVjb25ubmVjdBBbEhUKEU5vdEZvdW5k",
            "U3RvcmVJdGVtEFwSGAoUTm90RW5vdWdoQ29uc3VtZUl0ZW0QXRIfChtGYWls",
            "ZWRUb0dldEFjaGlldmVtZW50QXdhcmQQXhIVChFGYWlsZWRDcmVhdGVHdWls",
            "ZBBfEhEKDUxldmVsTm90UmVhY2gQYBISCg5HdWlsZE5hbWVFbXB0eRBhEhgK",
            "FEd1aWxkTmFtZUxlbmd0aEVycm9yEGISGQoVR3VpbGROYW1lQWxyZWFkeUV4",
            "aXN0EGMSGgoWR3VpbGROb3RpY2VMZW5ndGhFcnJvchBkEhYKEkd1aWxkSXRl",
            "bU5vdEVub3VnaBBlEhoKFlBsYXllckFscmVhZHlKb2luR3VpbGQQZhIWChJQ",
            "bGF5ZXJOb3RKb2luR3VpbGQQZxIUChBHdWlsZE5vQXV0aG9yaXR5EGgSFAoQ",
            "R3VpbGRNb2RpZnlFcnJvchBpEhUKEUd1aWxkSWNvbk5vdEV4aXN0EGoSFQoR",
            "R3VpbGRJY29uTm9DaGFuZ2UQaxIXChNHdWlsZE5vdGljZU5vQ2hhbmdlEGwS",
            "FAoQR3VpbGRQbGF5ZXJOb3RJbhBtEhQKEEd1aWxkVGFyZ2V0RXJyb3IQbhIX",
            "ChNHdWlsZEFscmVhZHlEaXNiYW5kEG8SEwoPR3VpbGREaXNiYW5kaW5nEHAS",
            "FgoSR3VpbGRBbHJlYWR5Tm9ybWFsEHESEQoNR3VpbGROb3RFeGlzdBByEhkK",
            "FUd1aWxkQWxyZWFkeUFwcGx5VGhpcxBzEhYKEkd1aWxkT3Zlck1heE1lbWJl",
            "chB0EhYKEkd1aWxkQWxyZWFkeUluVGhpcxB1EhMKD0d1aWxkQ2Fub3RMZWF2",
            "ZRB2EhYKEkd1aWxkQ2Fub3RLaWNrU2VsZhB3EhQKEEd1aWxkQXBwb2ludFNl",
            "bGYQeBIUChBHdWlsZE9wZXJhdGVTZWxmEHkSFAoQR3VpbGRQYXJhbXNFcnJv",
            "chB6EhoKFkd1aWxkUGxheWVyTGV2ZWxUb29Mb3cQexIXChNHdWlsZEZpZ2h0",
            "aW5nVG9vTG93EHwSEgoOR3VpbGRNYWlsRW1wdHkQfRIVChFHdWlsZE1haWxU",
            "b29MYXJnZRB+EhAKDEd1aWxkSm9iRnVsbBB/EhUKEEd1aWxkSm9iTm90RXhp",
            "c3QQgAESFwoSR3VpbGRBbHJlYWR5SW52aXRlEIEBEhgKE0d1aWxkSW52aXRl",
            "Tm90RXhpc3QQggESGgoVR3VpbGRCdWlsZGluZ05vdEV4aXN0EIMBEhwKF0d1",
            "aWxkQnVpbGRpbmdBbHJlYWR5TWF4EIQBEhcKEkd1aWxkTGV2ZWxOb0Vub3Vn",
            "aBCFARIXChJHdWlsZE1vbmV5Tm9Fbm91Z2gQhgESGQoUR3VpbGRNYWlsQnJv",
            "YWRjYXN0Q0QQhwESEgoNR3VpbGRSZWpvaW5DRBCIARIaChVOb3RFbm91Z2hD",
            "aGFsbGVuZ2VOdW0QiQESGgoVRmFpbGVkVG9HZXRRdWVzdEF3YXJkEIoBEiAK",
            "G0ZhaWxlZFRvR2V0QWN0aXZlVmFsdWVBd2FyZBCLARIYChNJbnZhbGlkTGll",
            "Wmh1YW5QYXJtEIwBEhQKD0FscmVhZHlCdXlMaW1pdBCNARISCg1SZWRpc0tl",
            "eUVycm9yEI4BEhMKDlJlZGlzUmFua0Vycm9yEI8BEhMKDlJlZGlzRGF0YUVt",
            "cHR5EJABEhkKFEV4cGVkaXRpb25MZXZlbEVycm9yEJEBEh8KGkV4cGVkaXRp",
            "b25DaGFsbGVuZ2VOb0NvdW50EJIBEhcKEkV4cGVkaXRpb25SZXNldGluZxCT",
            "ARIaChVFeHBlZGl0aW9uQ2hhbGxlbmdpbmcQlAESEgoNTm90U3lzdGVtT3Bl",
            "bhCVARIaChVGYWlsZWRUb1RydW5jYXRlVGFibGUQlgESFwoSRmFpbGVkVG9G",
            "aW5kRnJpZW5kEJcBEhoKFUZhaWxlZFRvWlJhbmdlQnlTY29yZRCYARIaChVG",
            "YWlsZWRUb1N0b3JlQW55VGFibGUQmQESFAoPRmFpbGVkVG9RdWVyeURiEJoB",
            "EhkKFEZhaWxlZFRvRGVjb2RlUGJEYXRhEJsBEhQKD1F1ZXJ5RGJfTm90RGF0",
            "YRCcARIZChRIb21lT3JuYW1lbnROb3RFeGlzdBCdARIWChFIb21lT3JuYW1l",
            "bnRFbXB0eRCeARIZChRIb21lQnVpbGRpbmdOb3RFeGlzdBCfARIdChhIb21l",
            "QnVpbGRpbmdBbHJlYWR5RXhpc3QQoAESGwoWSG9tZUJ1aWxkaW5nQWxyZWFk",
            "eU1heBChARIVChBIb21lSGVyb05vdEV4aXN0EKIBEhoKFUhvbWVIZXJvU3Rv",
            "cnlDZmdFcnJvchCjARIaChVIb21lSGVyb0FscmVheUluU2NlbmUQpAESIAob",
            "SG9tZUhlcm9JbnRlcmFjdE51bU5vRW5vdWdoEKUBEhcKEk90aGVyUGxhdGZv",
            "cm1Mb2dpbhCmARIZChRIb21lSGVyb1BsYWNlT3Zlck1heBCnARIXChJIb21l",
            "UmVnaW9uTm90RXhpc3QQqAESGAoTSG9tZVJlZ2lvbk5vdFVubG9jaxCpARIW",
            "ChFTYW54aWFvQ2ZnSURFcnJvchCqARIRCgxUcmlhbERhdGFOaWwQrAESGAoT",
            "VHJpYWxGb3JtYXRpb25FcnJvchCtARIXChJUcmlhbExldmVsQ2ZnRXJyb3IQ",
            "rgESGgoVVHJpYWxDbGllbnRMZXZlbEVycm9yEK8BEhkKFFRyaWFsQmF0dGxl",
            "Tm90Q3JlYXRlELABEh4KGVF1ZXN0Q29uc3VtZUl0ZW1Ob3RFbm91Z2gQsQES",
            "EgoNUXVlc3ROb3RFeGlzdBCyARIPCgpBY2NvdW50TmV3ELMBEhQKD0RhaVhp",
            "YW9SZXFMaW1pdBC0ARIYChNTYW5YaWFvQ2hlY2tUaW1lb3V0ELUBEhYKEVBs",
            "YXllck9ubGluZUxpbWl0ELYBEhMKDlNlcnZlck1haW50YWluELcBEhoKFVBs",
            "YXllck5hbWVMZW5ndGhFcnJvchC4ARIaChVFeHBlZGl0aW9uQ2Fubm90U3dl",
            "ZXAQuQESHgoZRXhwZWRpdGlvblN3ZWVwQXdhcmRFcnJvchC6ARIWChFIZXJv",
            "U3Rhck5vdEVub3VnaBC7ARIYChNEYWlYaWFvTG9zZUVmZmljYWN5EL0BEhgK",
            "E0tUU2tpbGxBbHJlYWR5RXF1aXAQwAESGQoUS1RTa2lsbFNsb3ROb3RFbm91",
            "Z2gQwQESFAoPS1RTa2lsbE5vdEZvdW5kEMIBEhcKEkZhblJvbmdEdU5vdEVu",
            "b3VnaBDDARIWChFCYXR0bGVWZXJOb3RNYXRjaBDEARIXChJTYW5YaWFvVmVy",
            "Tm90TWF0Y2gQxQESFAoPS1RTbG90Tm90RW5vdWdoEMYBEhgKE1BsYXllclNr",
            "aWxsTm90Rm91bmQQxwESHwoaUGxheWVyU2tpbGxBbHJlYWR5QWN0aXZhdGUQ",
            "yAESGwoWQWN0aXZhdGVQbGF5ZXJBdHRyRmFpbBDJARIZChRJbnZhbGlkTWFp",
            "blBsYXllckNmZxDKARIZChRGQUlMRURfUkVESVNfREVMX0tFWRDLARIUCg9B",
            "cmVhTmVlZFNhblhpYW8QzAESHwoaRmFpbGVkVG9HZXREYWlseVRvd2VyQXdh",
            "cmQQzQESHwoaU3RvcmVSZWZyZXNoQ291bnROb3RFbm91Z2gQzgESEgoNQ2hh",
            "dEZvcmJpZGRlbhDPARIXChJQbGF5ZXJBY2NvdW50QmxvY2sQ0AESGAoTUGxh",
            "eWVyU2tpbGxMVlVQRmFpbBDRARIYChNHdWlsZERvbmF0ZUNmZ0Vycm9yENIB",
            "Eh0KGEd1aWxkRG9uYXRlSXRlbU5vdEVub3VnaBDTARIbChZHdWlsZEludHJv",
            "ZHVjZU5vQ2hhbmdlENQBEh4KGUd1aWxkSW50cm9kdWNlTGVuZ3RoRXJyb3IQ",
            "1QESHAoXR3VpbGRBdXRob3JpdHlEYXRhRXJyb3IQ1gESGwoWR3VpbGRCdWls",
            "ZGluZ0luVXBncmFkZRDXARIXChJHdWlsZEF1Y3Rpb25Ob0l0ZW0Q2AESGAoT",
            "R3VpbGRBdWN0aW9uTm9Eb2luZxDZARIdChhHdWlsZEF1Y3Rpb25JdGVtTm90",
            "RXhpc3QQ2gESHgoZR3VpbGRBdWN0aW9uSXRlbUFscmVheUJpZBDbARIeChlH",
            "dWlsZEF1Y3Rpb25JdGVtTm90RW5vdWdoENwBEiQKH0d1aWxkQXVjdGlvbkl0",
            "ZW1BbHJlYWR5RmluaXNoZWQQ3QESHwoaR3VpbGRBdWN0aW9uSXRlbUFscmVh",
            "ZHlCdXkQ3gESGQoUR3VpbGRTa2lsbEFscmVhZHlNYXgQ3wESFQoQR3VpbGRC",
            "b3NzTm9Db3VudBDgARIbChZHdWlsZEJvc3NMZXZlbENmZ0Vycm9yEOEBEhQK",
            "D0d1aWxkQm9zc0lzRGVhZBDiARIXChJHdWlsZFF1ZXN0Tm90RXhpc3QQ4wES",
            "FgoRR3VpbGRRdWVzdE5vdE9wZW4Q5AESFgoRR3VpbGRRdWVzdE92ZXJNYXgQ",
            "5QESEgoNR3VpZGFuY2VMaW1pdBDqARIXChJTdG9yeVByb2dyZXNzTGltaXQQ",
            "6wESFQoQQWxyZWFkeUVxdWlwSGVybxDsARIWChFHb25nTWluZ0hlcm9MaW1p",
            "dBDtARIWChFGYWlsZWRUb0ZYTGV2ZWxVcBDuARIWChFGYWlsZWRHZXRMZXZl",
            "bEJveBDvARIXChJOb3RGb3VuZENoYWxsZW5nZXIQ8AESGgoVRmFjdGlvblR5",
            "cGVBbHJlYWR5U2V0EPEBEhUKEEZhY3Rpb25UeXBlRXJyb3IQ8gESEwoOQ2hh",
            "dFJlcVRpbWVPdXQQ8wESFwoSQ2hhdEZyZXF1ZW5jeUxpbWl0EPQBEhgKE1Jl",
            "ZGlzTGlzdFN0b3JlRXJyb3IQ9QESEwoORmFpbGVkVG9MUkFOR0UQ9gESHgoZ",
            "RmFpbGVkVG9HZXRDaGF0TXNnQnlSb29tRBD3ARITCg5GYWlsZWRUb1NpZ25J",
            "bhD4ARIQCgtTaWduSW5SZXNldBD5ARIZChRBY2NlcHRBc3Npc3RGYWlsTGF0",
            "ZRD6ARIeChlBY2NlcHRBc3Npc3RGYWlsUGFzc0xldmVsEPsBEh0KGEFzc2lz",
            "dEVudGVyRmFpbEFscmVhZHlJbhD8ARIfChpBc3Npc3RTYXZlRW1iYXR0bGVJ",
            "bmZvRmFpbBD9ARISCg1Bc3Npc3ROb1RpbWVzEP4BEhgKE0ludml0ZUFzc2lz",
            "dFJlcUZhaWwQ/wESGgoVQWNjZXB0QXNzaXN0RmFpbExldmVsEIACEh0KGEFj",
            "Y2VwdEFzc2lzdEZhaWxOb1BsYXllchCBAhIbChZBc3Npc3RFbnRlckZhaWxO",
            "b3RPcGVuEIICEh0KGEFzc2lzdEhlbHBQbGF5ZXJOb3RSZWFkeRCDAhIYChNB",
            "c3Npc3RQbGF5ZXJJblZhbGlkEIQCEhoKFUFzc2lzdFN3ZWVwV3JvbmdMZXZl",
            "bBCFAhIZChRHdWlsZFBsYXllck5vRmFjdGlvbhCGAhIZChRHdWlsZEZhY3Rp",
            "b25Ob3RNYXRjaBCHAhIfChpHdWlsZENhbm90QXBwbHlUaGlzRmFjdGlvbhCI",
            "AhIbChZHdWlsZFNlYXJjaE5hbWVJbnZhbGlkEIkCEhYKEUxvZ2luVG9rZW5J",
            "bnZhaWxkEIoCEhcKEkZhaWxlZFhpWHVuRGlhblphbhCLAhIWChFGYWlsZWRT",
            "dGFuZ2VyQ2hhdBCMAhIWChFGYWlsZWRCbGFja0ZyaWVuZBCNAhIcChdSZWFs",
            "VXNlck5vdFZlcmlmaWNhdGlvbhCOAhIYChNOb25hZ2VDYW5vdFBsYXlUaW1l",
            "EI8CEhcKEk5vbmFnZU92ZXJQbGF5VGltZRCQAhISCg1QYXlSZXFUaW1lT3V0",
            "EJECEg8KClBheVJlcUZhaWwQkgISFQoQRmFpbGVkVG93ZXJQb3dlchCTAhIV",
            "ChBIZWFydGJlYXRUaW1lb3V0EJQCEhoKFVJlY2hhcmdlU3RvcmVDZmdFcnJv",
            "chCVAhIVChBCdXlDaG91a2FOb1RpbWVzEJYCEhwKF1JlY2hhcmdlTm9uYWdl",
            "T25jZUxpbWl0EJcCEh0KGFJlY2hhcmdlTm9uYWdlTW9udGhMaW1pdBCYAhIa",
            "ChVGYWlsZWRFeHBlZGl0aW9uUG93ZXIQmQISGQoUTm90RW5vdWdoQ2hvdUth",
            "Q291bnQQmgISGAoTTm9uYWdlTG9naW5BZ2VMaW1pdBCbAhIOCglHTUtpY2tP",
            "dXQQnAISGAoTTmVlZExpZVpodWFuU2FuWGlhbxCdAhIWChFYaW5nSnVuUmV3",
            "YXJkRmFpbBCeAhIWChFTZXJ2ZXJEYXRhUmVxRmFpbBCfAhIbChZSaW5nQWN0",
            "aXZpdHlBbHJlYWR5RW5kEKACEhkKFFJpbmdBY3Rpdml0eU5vdFN0YXJ0EKEC",
            "EhcKEkFjdGl2aXR5U3RhdGVFcnJvchCiAhIUCg9SaW5nUmVwZWF0QXBwbHkQ",
            "owISGAoTQ2hhcHRlckxldmVsTm90T3BlbhCkAhIcChdTYW5YaWFvQmFvRGlh",
            "bkRhdGFFcnJvchClAhIgChtTYW5YaWFvQmFvRGlhblJhbmtEYXRhRXJyb3IQ",
            "pgISHgoZUmluZ05vdUVub3VnaENoYWxsZW5nZU51bRCnAhIRCgxSaW5nTm90",
            "QXBwbHkQqAISGAoTR3VpbGRRdWVzdE5vdEVub3VnaBCpAhITCg5SaW5nQXBw",
            "bHlMaW1pdBCqAhISCg1SZWRpc0dldEVycm9yEKsCEhIKDVJlZGlzU2V0RXJy",
            "b3IQrAISFQoQUmVkaXNLZXlOb3RFeGlzdBCtAhIVChBGQk1haWxBbHJlYWR5",
            "R2V0EK4CEhUKEEZhaWxlZFRvREJJbnNlcnQQrwISFQoQRmFpbGVkVG9EQlVw",
            "ZGF0ZRCwAhIfChpGYWlsZWRUb0NyZWF0ZVBsYXllck5hbWVJRBCxAhIdChhG",
            "YWlsZWRUb0dldFNldmVuRGF5QXdhcmQQsgISFAoPRmFpbEdldENvZGVVc2Vk",
            "ELMCEhQKD0ZhaWxHZXRDb2RlTm9uZRC0AhIZChRQbGF5ZXJCb29rTm90QWNj",
            "dGl2ZRC1AhISCg1Cb29rSWROb3RGaW5kELYCEhoKFUVxdWlwQm9va0ZhaWxO",
            "b3RNYXRjaBC3AhIcChdFcXVpcEJvb2tsbGVnYWxQb3NpdGlvbhC4AhIXChJQ",
            "bGF5ZXJCb29rTHZVcEZhaWwQuQISGgoVUmVmcmVzaEJvb2tOb3RBY2N0aXZl",
            "ELoCEhoKFVBsYXllclNraWxsTm90QWNjdGl2ZRC7AhISCg1DYW1wTm90VW5s",
            "b2NrELwCEhkKFENhbXBQb3NBbHJlYWR5VW5sb2NrEL0CEhUKEENhbXBQb3NO",
            "b3RVbmxvY2sQvgISFwoSQ2FtcFBvc1VubG9ja0Vycm9yEL8CEhIKDUNhbXBQ",
            "b3NOb0hlcm8QwAISGgoVQ2FtcFBvc0FscmVhZHlIYXNIZXJvEMECEhsKFkNh",
            "bXBQb3NDYW5ub3RQbGFjZUhlcm8QwgISGQoUQ2FtcEhlcm9BbHJlYWR5UGxh",
            "Y2UQwwISEgoNSGVyb1N0YXJFbXB0eRDEAhIfChpSZXJlc2hTa2lsbEJvb2tG",
            "YWlsTm9FbnRyeRDFAhIXChJIb21lU3RvcmVJdGVtRW1wdHkQxgISGQoUSG9t",
            "ZUJ1aWxkaW5nQ2ZnRXJyb3IQxwISHQoYSG9tZUNvdXJ0eWFyZFZpc2l0b3JG",
            "dWxsEMgCEiMKHkhvbWVDb3VydHlhcmRCeVZpc2l0Q291bnRFbXB0eRDJAhIh",
            "ChxIb21lQ291cnR5YXJkVmlzaXRDb3VudEVtcHR5EMoCEhoKFUhvbWVIb3Rl",
            "bFJvb21Ob3RFeGlzdBDLAhIeChlIb21lSG90ZWxSb29tSGVyb05vdEV4aXN0",
            "EMwCEhoKFUhvbWVIb3RlbFJvb21IZXJvRnVsbBDNAhIfChpIb21lSG90ZWxI",
            "ZXJvQ2Fub3RKb2luVGhpcxDOAhIfChpIb21lQWR2ZW50dXJlQ291bnROb0Vu",
            "b3VnaBDPAhIeChlIb21lQWR2ZW50dXJlTm9kZUNmZ0Vycm9yENACEhoKFUhv",
            "bWVBZHZlbnR1cmVOb3RTdGFydBDRAhIdChhIb21lQWR2ZW50dXJlTm90Rmlu",
            "aXNoZWQQ0gISHwoaSG9tZUFkdmVudHVyZU5vdEJhdHRsZU5vZGUQ0wISHAoX",
            "SG9tZUZhcm1IZXJvQWxyZWFkeUJ1c3kQ1AISHgoZSG9tZUZhcm1GcmllbmRI",
            "ZXJvT3Zlck1heBDVAhIYChNIb21lRmFybVdvcmtOb0NvdW50ENYCEh4KGUhv",
            "bWVGYXJtRnJpZW5kV29ya05vQ291bnQQ1wISHQoYSG9tZUZhcm1IZXJvSW5G",
            "cmllbmRIb21lENgCEhgKE0hvbWVGYXJtSGVyb092ZXJNYXgQ2QISHwoaSG9t",
            "ZUhvdGVsSGVyb0FscmVhZHlJblJvb20Q2gISFgoRSG9tZUhvdGVsSGVyb0Z1",
            "bGwQ2wISGwoWSG9tZUhvdGVsUXVlc3RGaW5pc2hlZBDcAhIUCg9SZWRpc0Rp",
            "c2Nvbm5lY3QQ3QISGwoWTm90RW5vdWdoRHJhd0NhcmRDb3VudBDeAhIYChNI",
            "ZXJvQXdha2VXcm9uZ0xldmVsEOgCEhgKE0ludmFpbGRBYmlsaXR5Q2ZnSUQQ",
            "6QISHgoZS1RTa2lsbEVxdWlwU2xvdE5vdEVub3VnaBDqAhIeChlIZXJvQXdh",
            "a2VXcm9uZ0hlcm9RdWFsaXR5EOsCEh0KGEhlcm9Qb3RlbnRpYWxBdHRyV3Jv",
            "bmdMdhDsAhIYChNCbG9vZFBvd2VyTm90RW5vdWdoEO0CEhEKDEh0dHBSZXFF",
            "cnJvchDuAhITCg5IdHRwUmVxVGltZW91dBDvAhIXChJIdHRwUmVzRGVjb2Rl",
            "RXJyb3IQ8AISFwoSUmVkZWVtQ29kZVJlcUVycm9yEPECEh0KGFJlZGVlbUNv",
            "ZGVBbHJlYWR5R2V0SXRlbRDyAhIUCg9SZWRlZW1Db2RlRG9pbmcQ8wISEQoM",
            "REJSZXFUaW1lb3V0EPQCEhUKEEZhaWxlZFRvRW1iYXR0bGUQ9QISFgoRRmFp",
            "bGVkVG9SaW5nQXBwbHkQ9gISGAoTR3VpbGRCb3NzQXdhcmRUYWtlZBD3AhId",
            "ChhHdWlsZEJvc3NCdXlDb3VudE92ZXJNYXgQ+AISGQoUR3VpbGRJbmZvS2V5",
            "Tm90RXhpc3QQ+QISGwoWUmVtb3ZlVGFyZ2V0R3VhcmROb3RJcxD6AhIbChZJ",
            "bnZpdGVHdWFyZFByb3RlY3RUaW1lEPsCEhkKFEludml0ZUd1YXJkQWxyZWFk",
            "eUlzEPwCEiEKHEludml0ZUd1YXJkUmVtb3ZlUHJvdGVjdFRpbWUQ/QISFgoR",
            "SW52aXRlR3VhcmRGcmllbmQQ/gISGAoTSW52aXRlR3VhcmRQcmVzdGlnZRD/",
            "AhISCg1HdWFyZE5vdEZvdW5kEIADEhMKDlRtcHRHdWFyZE93bmVyEIEDEhQK",
            "D0ludml0ZUd1YXJkRmFpbBCCAxIXChJJbnZpdGVHdWFyZE5vVGltZXMQgwMS",
            "FgoRVGFyZ2V0R3VhcmRNYXhOdW0QhAMSGQoUVGFyZ2V0R3VhcmRBbHJlYWR5",
            "SXMQhQMSFgoRSW52aXRlR3VhcmRNYXhOdW0QhgMSGgoVU0RLUXVlcnlSZWFs",
            "TmFtZUVycm9yEIcDEh0KGFNhblhpYW9Db2xsZXRSZXdhcmRFcnJvchCIAxId",
            "ChhTYW5YaWFvQ29sbGV0UmV3YXJkRW1wdHkQiQMSHgoZR3VpbGRSZWNydWl0",
            "SXRlbU5vdEVub3VnaBCKAxIZChRHdWlsZFJlY3J1aXRNc2dFbXB0eRCLAxIf",
            "ChpHdWlsZFJlY3J1aXRNc2dMZW5ndGhFcnJvchCMAxIUCg9Ob3RFbWJhdHRs",
            "ZUhlcm8QjQMSHwoaSG9tZVBhcnR5RGF5SG9sZENvdW50RW1wdHkQjgMSIAob",
            "SG9tZVBhcnR5V2Vla0hvbGRDb3VudEVtcHR5EI8DEiAKG0hvbWVQYXJ0eVN1",
            "YnNjcmliZVRpbWVFcnJvchCQAxIZChRIb21lUGFydHlOb3RPcGVuVGltZRCR",
            "AxIXChJIb21lUGFydHlJc0V4cGlyZWQQkgMSFgoRSG9tZVBhcnR5Tm90RXhp",
            "c3QQkwMSHQoYSG9tZVBhcnR5Tm9PcGVuQXV0aG9yaXR5EJQDEhoKFUhvbWVQ",
            "YXJ0eUdpZnROb3RFeGlzdBCVAxIcChdIb21lUGFydHlKb2luQ291bnRFbXB0",
            "eRCWAxIbChZIb21lUGFydHlQbGF5ZXJOb3RKb2luEJcDEh8KGkhvbWVQYXJ0",
            "eVBsYXllckFscmVhZHlHaWZ0EJgDEhkKFEhvbWVQYXJ0eUFscmVhZHlPcGVu",
            "EJkDEhgKE0hvbWVQYXJ0eUFscmVhZHlHZXQQmgMSIAobSG9tZVBhcnR5Q2Fu",
            "bm90U2NhdHRlclN1Z2FyEJsDEh0KGEhvbWVQYXJ0eVBsYXllckNvdW50RnVs",
            "bBCcAxIYChNIb21lUGFydHlQbGF5ZXJCdXN5EJ0DEiAKG0hvbWVQYXJ0eURh",
            "bmNlQWxyZWFkeUludml0ZRCeAxIgChtIb21lUGFydHlEYW5jZUludml0ZUV4",
            "cGlyZWQQnwMSHgoZSG9tZVBhcnR5RmlyZXdvcmtOb3RQbGFjZRCgAxIcChdI",
            "b21lUGFydHlBbHJlYWR5RWF0RGlzaBChAxIZChROZWVkR3VhcmRCb3NzU2Fu",
            "WGlhbxCiAxIaChVJbnZpdGVHdWFyZEluQm9zc1RpbWUQowMSJgohR3VpbGRN",
            "c2dJbnZlc3RpZ2F0ZUNvdW50Tm90RW5vdWdoEKQDEhsKFkd1YXJkQm9zc0lu",
            "c3BpcmVNYXhOdW0QpQMSJAofR2V0Qm9zc0RhbWFnZVJhbmtMaXN0V3JvbmdT",
            "dGF0ZRCmAxIcChdHdWlsZEJ1aWxkRXZlbnROb3RFeGlzdBCnAxIgChtHdWls",
            "ZEJ1aWxkRXZlbnRBcmVhZHlGaW5pc2gQqAMSFgoRR2V0Qm9zc0JveE5vdEV4",
            "aXQQqQMSFQoQSG9tZVBhcnR5Tm90T3BlbhCqAxIgChtHdWlsZEF1Y3Rpb25C",
            "b251c0FscmVhZHlHZXQQqwMSGAoTR3VpbGROb0F1Y3Rpb25Cb251cxCsAxIe",
            "ChlIb21lUGFydHlGaXJld29ya05vdEV4aXN0EK0DEiIKHUZhaWxlZFRvU2V2",
            "ZW5Gb3VydGVlblNhbGVJdGVtEK4DEiQKH0ZhaWxlZFRvU2V2ZW5Gb3VydGVl",
            "bkFjdGl2ZUl0ZW0QrwMSGAoTRmFpbGVkR2V0Q29kZVJld2FyZBCwAxIVChBS",
            "ZWRpc01lbWJlckV4aXN0ELEDEhMKDlJlZGlzU0FkZEVycm9yELIDEhYKEUlu",
            "R3VpbGRXcm9uZ1N0YXRlELMDEhQKD0d1YXJkSW5Cb3NzVGltZRC0AxIZChRI",
            "b21lUGFydHlOb1dpbmVDb3VudBC1AxIiCh1Ib21lUGFydHlJbnZpdGVQbGF5",
            "ZXJOb3RFeGlzdBC2AxIYChNIb21lUGFydHlSb2JiZXJEaWVkELcDEiIKHUhv",
            "bWVQYXJ0eUdhbWVFYXRBbHJlYWR5RmluaXNoELgDEiEKHEhvbWVQYXJ0eUZp",
            "bmlzaEF3YXJkQ2ZnRXJyb3IQuQMSFwoSSG9tZVBhcnR5R2FtZUVycm9yELoD",
            "EicKIkhvbWVQYXJ0eUF0bW9zcGhlcmVBY2hpZXZlQ2ZnRXJyb3IQuwMSIAob",
            "SG9tZVBhcnR5QXRtb3NwaGVyZU5vRW5vdWdoELwDEi4KKUhvbWVQYXJ0eUF0",
            "bW9zcGhlcmVBY2hpZXZlQXdhcmRBbHJlYWR5R2V0EL0DEh0KGEZhaWxlZFRv",
            "U2V0RW1iYXR0bGVJbmRleBC+AxIXChJOb3RGb3VuZFBsYXllckluZm8QvwMS",
            "GgoVRnJpZW5kSmlCYW5Mdk5vRW5vdWdoEMADEiYKIUhvbWVQYXJ0eUF0bW9z",
            "cGhlckF3YXJkQWxyZWFkeUdldBDBAxIZChRIb21lUGFydHlBbHJlYWR5Sm9p",
            "bhDCAxIbChZIb21lUGFydHlBbHJlYWR5RmluaXNoEMMDEhoKFUd1aWxkQm9z",
            "c0dyb3VwTm90UGFzcxDEAxIbChZHdWlsZEJvc3NHcm91cENmZ0Vycm9yEMUD",
            "EhUKEERhaVhpYW9Ob3RGaW5pc2gQxgMSFgoRRGFpWGlhb05vdEludmFsaWQQ",
            "xwMSGgoVSG9tZVBhcnR5R3Vlc3RPdmVyTWF4EMgDEh4KGUhvbWVQYXJ0eU1h",
            "aW5HdWVzdE92ZXJNYXgQyQMSGQoUWmhhbmdMaW5nQ2ZnTm90RXhpc3QQygMS",
            "FwoSWmhhbmdMaW5nTm90VW5sb2NrEMsDEhgKE1poYW5nTGluZ0FscmVhZHlH",
            "ZXQQzAMSIAobQWNjb3VudEJpbmRSZXdhcmRHZXRBbHJlYWR5EM0DEh0KGEFj",
            "Y291bnRCaW5kUmV3YXJkR2V0RmFpbBDOAxIeChlTaGFuZ0d1WWlKaUludmFs",
            "aWRMZXZlbElEEM8DEh0KGFNoYW5nR3VTaG9ydGN1dE5vdEVub3VnaBDQAxIX",
            "ChJSZWNoYXJnZU9yZGVyRXJyb3IQ0QMSFgoRQmF0dGxlVmlkZW9FeHBpcmUQ",
            "0gMSFQoQUXVlc3ROb3RGaW5pc2hlZBDTAxIfChpaaGFuZ0xpbmdQYXlDb3Vu",
            "dE5vdEVub3VnaBDUAxIbChZaaGFuZ0xpbmdQYXlDaGVja0Vycm9yENUDEhQK",
            "D1poYW5nTGluZ05vdFBheRDWAxIWChFBbHJlYWR5RXF1aXBTdGFtcBDXAxIO",
            "CglTdGFtcExvY2sQ2AMSEwoOWXVlS2FPdXRPZlRpbWUQ2QMSGgoVWXVlS2FS",
            "ZXdhcmRBbHJlYWR5R2V0ENoDEhcKEll1ZUthUGF5Q2hlY2tFcnJvchDbAxIQ",
            "CgtZdWVLYU5vdEJ1eRDcAxIWChFDbGltYlRvd2VyTm9UaW1lcxDdAxIVChBI",
            "b21lRmFybVBvc0Vycm9yEN4DEhwKF0hvbWVGYXJtQWxyZWFkeUNvbXBsZXRl",
            "EN8DEhgKE0hvbWVGYXJtTm90Q29tcGxldGUQ4AMSGwoWSG9tZUZhcm1Qb3NB",
            "bHJlYWR5VXNlZBDhAxIhChxIb21lRmFybU9uZUZyaWVuZEhlcm9PdmVyTWF4",
            "EOIDEhYKEUhvbWVGYXJtUG9zTm9IZXJvEOMDEhoKFVFpRnVQYXlDb3VudE5v",
            "dEVub3VnaBDkAxIQCgtRaUZ1Tm9UaW1lcxDlAxIeChlEYWlseURlYWxSZXdh",
            "cmRBbHJlYWR5R2V0EOYDEhsKFkRhaWx5RGVhbFBheUNoZWNrRXJyb3IQ5wMS",
            "IQocV2Vla0dpZnRQYWNrYWdlUGF5Q2hlY2tFcnJvchDoAxIgChtEYXlHaWZ0",
            "UGFja2FnZVBheUNoZWNrRXJyb3IQ6QMSFgoRUmVjaGFyZ2VXZWVrTGltaXQQ",
            "6gMSFQoQUmVjaGFyZ2VEYXlMaW1pdBDrAxIdChhTZXZlbkRheVJld2FyZEFs",
            "cmVhZHlHZXQQ7AMSHQoYU2V2ZW5EYXlSZXdhcmROb3RSZWFjaGVkEO0DEhYK",
            "EVJlY2hhcmdlTGl2ZUxpbWl0EO4DEhoKFVBsYXllck5vUmVjaGFyZ2VDb3Vu",
            "dBDvAxIhChxGaXJzdFJlY2hhcmdlQXdhcmRBbHJlYWR5R2V0EPADEiQKH0dl",
            "dFN0YXJBd2FrZW5GYWlsTm90RW5vdWdoUG9pbnQQ8QMSIwoeR2V0U3RhckF3",
            "YWtlbkZhaWxOb3RFbm91Z2hJdGVtEPIDEhoKFVBpY2tHaWZ0UmVjaGFyZ2VF",
            "cnJvchDzAxIbChZQaWNrR2lmdFBhY2thZ2VOb3RIYXZlEPQDEhoKFVRpdGxl",
            "QWN0aXZlRmFpbE5vdEdldBD1AxIYChNUaXRsZUFjdGl2ZUZhaWxOb0lEEPYD",
            "EhwKF1RpdGxlRXF1aXBGYWlsTm90QWN0aXZlEPcDEhUKEENhbXBMZXZlbENh",
            "bm90VXAQ+AMSGgoVSG9tZUZhcm1JbnZpdGVOb0NvdW50EPkDEhsKFlRob3Vz",
            "YW5kRHJhd0NhcmRVbkxvY2sQ+gMSHAoXVGhvdXNhbmREcmF3Q2FyZE5vSW5k",
            "ZXgQ+wMSFgoRTm9IYXNUaGlzSGVhZEljb24Q/AMSGwoWTm9IYXNUaGlzSGVh",
            "ZEljb25GcmFtZRD9AxIVChBWSVBMZXZlbE5vdFJlYWNoEP4DEhcKElZJUEF3",
            "YXJkQWxyZWFkeUdldBD/AxIcChdEb3dubG9hZEF3YXJkQWxyZWFkeUdldBCA",
            "BBIXChJIb21lRmFybU5vSGVyb1dvcmsQgQQSHAoXRGFpbHlQaHlzaWNhbEFs",
            "cmVhZHlHZXQQggQSIAobUmVjaGFyZ2VUb3RhbE1vbWVueUNmZ0Vycm9yEIME",
            "EicKIlJlY2hhcmdlVG90YWxNb21lbnlBd2FyZEFscmVhZHlHZXQQhAQSIAob",
            "UmVjaGFyZ2VUb3RhbE1vbWVueU5vRW5vdWdoEIUEEhwKF0hlcm9RdWVzdE5v",
            "dEFsbEZpbmlzaGVkEIYEEh0KGEhlcm9RdWVzdEF3YXJkQWxyZWFkeUdldBCH",
            "BBIgChtSZWNoYXJnZVRvdGFsTW9tZW55Tm90RXhpc3QQiAQSGgoVUm9sbE1v",
            "bmV5VHJlZU1heFRpbWVzEIkEEh4KGVJvbGxNb25leVRyZWVBd2FyZEFscmVh",
            "ZHkQigQSGgoVUG9CaW5nQXdhcmRBbHJlYWR5R2V0EIsEEh0KGEZYRXF1aXBS",
            "ZWZpbmVGYWlsUXVhbGl0eRCMBBIYChNGYWlsZWRNYXRjaE9wcG9uZW50EI0E",
            "EhgKE1F1ZXN0QXdhcmRBbGVhZHlHZXQQjgQSIQocR3VpbGREZXZlbG9wQ2hh",
            "cHRlck5vdEZpbmlzaBCPBBImCiFHdWlsZERldmVsb3BDaGFwdGVyQXdhcmRB",
            "bGVhZHlHZXQQkAQSHQoYR3VpbGRHdWFyZFdvcnNoaXBOb1RpbWVzEJEEEhMK",
            "DlpJTlRFUlNUT1JFRXJyEJIEEh8KGkFzc2lzdFNhblhpYW9QbGF5ZXJJRFdy",
            "b25nEJMEEhwKF01pbmdHZURyYXdDYXJkTm9YaW5ZdWFuEJQEEicKIkZhaWxl",
            "ZFRvV29ybGRNYXRjaFNlYXNvblNjb3JlQXdhcmQQlQQSGQoUWU1QRHJhd0Nh",
            "cmROb1hpbll1YW4QlgQSEgoNUGhvdG9Ob3RFeGlzdBCXBBIWChFQaG90b092",
            "ZXJNYXhDb3VudBCYBBIVChBQaG90b0xpa2VOb0NvdW50EJkEEhIKDVBob3Rv",
            "VVJMRW1wdHkQmgQSGQoUUGhvdG9Qb3NBbHJlYWR5RXhpc3QQmwQSGQoUU3Ry",
            "YXRlZ3lGYWlsTm9IZXJvSUQQnAQSEgoNU3lzU2FuWGlhb0VychCdBBIYChNM",
            "ZXZlbEF3YXJkQWxlYWR5R2V0EJ4EEhYKEUxldmVsQXdhcmROb0V4aXN0EJ8E",
            "EhwKF0NvbXBvc2VJdGVtQ29zdENmZ0Vycm9yEKAEEhgKE1ZvdWNoZXJJdGVt",
            "Tm9Fbm91Z2gQoQQSEwoOU2Vuc2l0aXZlV29yZHMQ6AdiBnByb3RvMw=="));
      descriptor = pbr::FileDescriptor.FromGeneratedCode(descriptorData,
          new pbr::FileDescriptor[] { },
          new pbr::GeneratedClrTypeInfo(new[] {typeof(global::ErrorNo.ErrorNo), }, null, null));
    }
    #endregion

  }
  #region Enums
  public enum ErrorNo {
    [pbr::OriginalName("Success")] Success = 0,
    [pbr::OriginalName("FailedLogin")] FailedLogin = 1,
    [pbr::OriginalName("IncorrectPWD")] IncorrectPwd = 2,
    [pbr::OriginalName("FailedCreateAccount")] FailedCreateAccount = 3,
    [pbr::OriginalName("FailedCreatePlayer")] FailedCreatePlayer = 4,
    [pbr::OriginalName("NotFoundAccount")] NotFoundAccount = 5,
    [pbr::OriginalName("CreatePlayerLimit")] CreatePlayerLimit = 6,
    [pbr::OriginalName("FailedUpdateDBData")] FailedUpdateDbdata = 7,
    [pbr::OriginalName("NotFoundPlayer")] NotFoundPlayer = 8,
    [pbr::OriginalName("FailedInitPlayer")] FailedInitPlayer = 9,
    [pbr::OriginalName("NotFoundMatchSrv")] NotFoundMatchSrv = 10,
    [pbr::OriginalName("NotFoundSceneSrv")] NotFoundSceneSrv = 11,
    [pbr::OriginalName("FailedCreateBattle")] FailedCreateBattle = 12,
    [pbr::OriginalName("NotInCenter")] NotInCenter = 13,
    [pbr::OriginalName("NameAlreadyUse")] NameAlreadyUse = 14,
    [pbr::OriginalName("FailedCreateName")] FailedCreateName = 15,
    [pbr::OriginalName("NotFoundLoginKey")] NotFoundLoginKey = 16,
    [pbr::OriginalName("NameIsInValid")] NameIsInValid = 17,
    [pbr::OriginalName("FailedLoginBattle")] FailedLoginBattle = 18,
    [pbr::OriginalName("NotFoundBattleRoom")] NotFoundBattleRoom = 19,
    [pbr::OriginalName("AlreadyFight")] AlreadyFight = 20,
    [pbr::OriginalName("NotFoundPlayerInBattle")] NotFoundPlayerInBattle = 21,
    [pbr::OriginalName("InvalidItem")] InvalidItem = 22,
    [pbr::OriginalName("HasAlreadyItem")] HasAlreadyItem = 23,
    [pbr::OriginalName("InvalidHeroId")] InvalidHeroId = 24,
    [pbr::OriginalName("BagFull")] BagFull = 25,
    [pbr::OriginalName("MatchTimeout")] MatchTimeout = 26,
    [pbr::OriginalName("InvalidSkillID")] InvalidSkillId = 27,
    [pbr::OriginalName("NotFoundInBag")] NotFoundInBag = 29,
    [pbr::OriginalName("FailedCMD")] FailedCmd = 30,
    /// <summary>
    ///没有足够道具
    /// </summary>
    [pbr::OriginalName("NotEnoughItem")] NotEnoughItem = 35,
    [pbr::OriginalName("FailedUseItem")] FailedUseItem = 36,
    /// <summary>
    ///已经到达最大级
    /// </summary>
    [pbr::OriginalName("AlreadyMaxLv")] AlreadyMaxLv = 37,
    /// <summary>
    ///装备宝石失败
    /// </summary>
    [pbr::OriginalName("FailedEquipGem")] FailedEquipGem = 38,
    /// <summary>
    ///卸下装备宝石失败
    /// </summary>
    [pbr::OriginalName("FailedUnequipGem")] FailedUnequipGem = 39,
    /// <summary>
    ///宝石升级失败
    /// </summary>
    [pbr::OriginalName("FailedGemLV")] FailedGemLv = 40,
    /// <summary>
    ///穿装备失败
    /// </summary>
    [pbr::OriginalName("FailedEquipAny")] FailedEquipAny = 42,
    /// <summary>
    ///卸装备失败
    /// </summary>
    [pbr::OriginalName("FailedUnequipAny")] FailedUnequipAny = 43,
    [pbr::OriginalName("NotOnline")] NotOnline = 49,
    [pbr::OriginalName("FailedToPlayerLogin")] FailedToPlayerLogin = 50,
    /// <summary>
    ///没有找到英雄
    /// </summary>
    [pbr::OriginalName("NotFoundHero")] NotFoundHero = 51,
    /// <summary>
    ///英雄星际以及升满
    /// </summary>
    [pbr::OriginalName("HeroStarFull")] HeroStarFull = 52,
    /// <summary>
    ///战斗超时
    /// </summary>
    [pbr::OriginalName("BattleTimeout")] BattleTimeout = 53,
    /// <summary>
    ///创建PVE战斗失败
    /// </summary>
    [pbr::OriginalName("FailedCreatePVEBattle")] FailedCreatePvebattle = 54,
    /// <summary>
    ///正在战斗中
    /// </summary>
    [pbr::OriginalName("PlayerAlreadyInBattle")] PlayerAlreadyInBattle = 55,
    /// <summary>
    ///战斗校验失败,退出战斗
    /// </summary>
    [pbr::OriginalName("FailedToCheckReport")] FailedToCheckReport = 56,
    /// <summary>
    ///图集激活达到上限
    /// </summary>
    [pbr::OriginalName("AtlasActiveLimit")] AtlasActiveLimit = 57,
    /// <summary>
    ///锁道具失败
    /// </summary>
    [pbr::OriginalName("FailedToLockItem")] FailedToLockItem = 58,
    /// <summary>
    ///已经拥有此英雄
    /// </summary>
    [pbr::OriginalName("HasHero")] HasHero = 59,
    /// <summary>
    ///PVE关卡条件不足
    /// </summary>
    [pbr::OriginalName("InsufficientCondition")] InsufficientCondition = 60,
    /// <summary>
    ///没有足够的星星
    /// </summary>
    [pbr::OriginalName("NotEnoughStars")] NotEnoughStars = 61,
    /// <summary>
    ///没有足够的体力
    /// </summary>
    [pbr::OriginalName("NotEnoughPower")] NotEnoughPower = 62,
    /// <summary>
    ///等级不足
    /// </summary>
    [pbr::OriginalName("NotEnoughLevel")] NotEnoughLevel = 63,
    /// <summary>
    ///失败删除数据
    /// </summary>
    [pbr::OriginalName("FailedToDelData")] FailedToDelData = 64,
    /// <summary>
    ///失败的获取邮件内容
    /// </summary>
    [pbr::OriginalName("FailedToGetMailItem")] FailedToGetMailItem = 65,
    /// <summary>
    ///装备印记失败
    /// </summary>
    [pbr::OriginalName("FailedEquipStamp")] FailedEquipStamp = 66,
    /// <summary>
    ///装备印记失败
    /// </summary>
    [pbr::OriginalName("FailedUnequipStamp")] FailedUnequipStamp = 67,
    /// <summary>
    ///印记强化失败
    /// </summary>
    [pbr::OriginalName("FailedStampUpStar")] FailedStampUpStar = 68,
    /// <summary>
    ///印记强化到上限
    /// </summary>
    [pbr::OriginalName("StampStarMax")] StampStarMax = 69,
    /// <summary>
    ///没有足够宝石
    /// </summary>
    [pbr::OriginalName("NotEnoughGem")] NotEnoughGem = 70,
    /// <summary>
    ///开天牌已经装备
    /// </summary>
    [pbr::OriginalName("AlreadyEquipKT")] AlreadyEquipKt = 71,
    /// <summary>
    ///销售给系统道具失败
    /// </summary>
    [pbr::OriginalName("FailedSellToSys")] FailedSellToSys = 72,
    /// <summary>
    ///已经买过次开天牌
    /// </summary>
    [pbr::OriginalName("AlreadyBuyKT")] AlreadyBuyKt = 73,
    /// <summary>
    ///开天牌达到上限
    /// </summary>
    [pbr::OriginalName("KTBagLimit")] KtbagLimit = 74,
    /// <summary>
    ///失败的强化装备槽位
    /// </summary>
    [pbr::OriginalName("FailedToEquipLvUp")] FailedToEquipLvUp = 75,
    /// <summary>
    ///请先布阵
    /// </summary>
    [pbr::OriginalName("NeedEmbattle")] NeedEmbattle = 76,
    /// <summary>
    ///无效的关卡ID
    /// </summary>
    [pbr::OriginalName("InvalidLevelID")] InvalidLevelId = 77,
    /// <summary>
    ///前置关卡未完成
    /// </summary>
    [pbr::OriginalName("TowerAfterLevelNotFinish")] TowerAfterLevelNotFinish = 78,
    /// <summary>
    ///不能超过玩家的等级
    /// </summary>
    [pbr::OriginalName("SurpassPlayerLv")] SurpassPlayerLv = 79,
    /// <summary>
    ///失败的刷新开天牌商店
    /// </summary>
    [pbr::OriginalName("FailedToRefreshKTPShop")] FailedToRefreshKtpshop = 80,
    /// <summary>
    ///没有完成爬塔关卡
    /// </summary>
    [pbr::OriginalName("NotFinishTowerLevel")] NotFinishTowerLevel = 81,
    /// <summary>
    ///三消检测失败
    /// </summary>
    [pbr::OriginalName("FailedToCheckSanXiao")] FailedToCheckSanXiao = 82,
    /// <summary>
    ///进入战斗的英雄抄错配置
    /// </summary>
    [pbr::OriginalName("EmbattleHeroLimit")] EmbattleHeroLimit = 83,
    /// <summary>
    ///没有足够开天币
    /// </summary>
    [pbr::OriginalName("NotEnoughKTCoin")] NotEnoughKtcoin = 84,
    /// <summary>
    ///神器升级失败
    /// </summary>
    [pbr::OriginalName("FailedToGodLevelUp")] FailedToGodLevelUp = 85,
    /// <summary>
    ///对手的排名已经更改
    /// </summary>
    [pbr::OriginalName("OppoentRankInvalid")] OppoentRankInvalid = 86,
    /// <summary>
    ///没有找到战斗录像
    /// </summary>
    [pbr::OriginalName("NotFoundBattleVideo")] NotFoundBattleVideo = 87,
    /// <summary>
    ///神器升级失败
    /// </summary>
    [pbr::OriginalName("InvalidItemType")] InvalidItemType = 88,
    /// <summary>
    ///无效的三消Key
    /// </summary>
    [pbr::OriginalName("InvalidSanXiaoKey")] InvalidSanXiaoKey = 89,
    /// <summary>
    ///失败的保存三消结果
    /// </summary>
    [pbr::OriginalName("FailedSaveSanXiao")] FailedSaveSanXiao = 90,
    /// <summary>
    ///重连失败
    /// </summary>
    [pbr::OriginalName("FailedReconnnect")] FailedReconnnect = 91,
    /// <summary>
    ///没有找到上架的商品
    /// </summary>
    [pbr::OriginalName("NotFoundStoreItem")] NotFoundStoreItem = 92,
    /// <summary>
    ///没有足够的消耗品
    /// </summary>
    [pbr::OriginalName("NotEnoughConsumeItem")] NotEnoughConsumeItem = 93,
    /// <summary>
    ///失败的获得成就奖励
    /// </summary>
    [pbr::OriginalName("FailedToGetAchievementAward")] FailedToGetAchievementAward = 94,
    /// <summary>
    ///创建公会失败
    /// </summary>
    [pbr::OriginalName("FailedCreateGuild")] FailedCreateGuild = 95,
    /// <summary>
    ///玩家等级未达到
    /// </summary>
    [pbr::OriginalName("LevelNotReach")] LevelNotReach = 96,
    /// <summary>
    ///公会名字空
    /// </summary>
    [pbr::OriginalName("GuildNameEmpty")] GuildNameEmpty = 97,
    /// <summary>
    ///公会名字长度错误
    /// </summary>
    [pbr::OriginalName("GuildNameLengthError")] GuildNameLengthError = 98,
    /// <summary>
    ///公会名字已经存在
    /// </summary>
    [pbr::OriginalName("GuildNameAlreadyExist")] GuildNameAlreadyExist = 99,
    /// <summary>
    ///公会公告长度错误
    /// </summary>
    [pbr::OriginalName("GuildNoticeLengthError")] GuildNoticeLengthError = 100,
    /// <summary>
    ///创建公会道具不足
    /// </summary>
    [pbr::OriginalName("GuildItemNotEnough")] GuildItemNotEnough = 101,
    /// <summary>
    ///玩家已经加入公会
    /// </summary>
    [pbr::OriginalName("PlayerAlreadyJoinGuild")] PlayerAlreadyJoinGuild = 102,
    /// <summary>
    ///玩家未加入公会
    /// </summary>
    [pbr::OriginalName("PlayerNotJoinGuild")] PlayerNotJoinGuild = 103,
    /// <summary>
    /// 没有权限
    /// </summary>
    [pbr::OriginalName("GuildNoAuthority")] GuildNoAuthority = 104,
    /// <summary>
    /// 修改公会信息失败
    /// </summary>
    [pbr::OriginalName("GuildModifyError")] GuildModifyError = 105,
    /// <summary>
    /// 公会图标不存在
    /// </summary>
    [pbr::OriginalName("GuildIconNotExist")] GuildIconNotExist = 106,
    /// <summary>
    /// 公会图标未改变
    /// </summary>
    [pbr::OriginalName("GuildIconNoChange")] GuildIconNoChange = 107,
    /// <summary>
    /// 公会公告未改变
    /// </summary>
    [pbr::OriginalName("GuildNoticeNoChange")] GuildNoticeNoChange = 108,
    /// <summary>
    /// 玩家不在此公会
    /// </summary>
    [pbr::OriginalName("GuildPlayerNotIn")] GuildPlayerNotIn = 109,
    /// <summary>
    /// 错误的目标
    /// </summary>
    [pbr::OriginalName("GuildTargetError")] GuildTargetError = 110,
    /// <summary>
    /// 公会已解散
    /// </summary>
    [pbr::OriginalName("GuildAlreadyDisband")] GuildAlreadyDisband = 111,
    /// <summary>
    /// 公会解散中
    /// </summary>
    [pbr::OriginalName("GuildDisbanding")] GuildDisbanding = 112,
    /// <summary>
    /// 公会已正常
    /// </summary>
    [pbr::OriginalName("GuildAlreadyNormal")] GuildAlreadyNormal = 113,
    /// <summary>
    /// 公会不存在
    /// </summary>
    [pbr::OriginalName("GuildNotExist")] GuildNotExist = 114,
    /// <summary>
    /// 已经申请此公会
    /// </summary>
    [pbr::OriginalName("GuildAlreadyApplyThis")] GuildAlreadyApplyThis = 115,
    /// <summary>
    /// 公会人数已达上限
    /// </summary>
    [pbr::OriginalName("GuildOverMaxMember")] GuildOverMaxMember = 116,
    /// <summary>
    /// 玩家已经加入这个公会
    /// </summary>
    [pbr::OriginalName("GuildAlreadyInThis")] GuildAlreadyInThis = 117,
    /// <summary>
    /// 玩家不可以离开公会
    /// </summary>
    [pbr::OriginalName("GuildCanotLeave")] GuildCanotLeave = 118,
    /// <summary>
    ///不能踢掉自己
    /// </summary>
    [pbr::OriginalName("GuildCanotKickSelf")] GuildCanotKickSelf = 119,
    /// <summary>
    ///不能任命自己
    /// </summary>
    [pbr::OriginalName("GuildAppointSelf")] GuildAppointSelf = 120,
    /// <summary>
    ///不能操作自己
    /// </summary>
    [pbr::OriginalName("GuildOperateSelf")] GuildOperateSelf = 121,
    /// <summary>
    ///客户端传参错误
    /// </summary>
    [pbr::OriginalName("GuildParamsError")] GuildParamsError = 122,
    /// <summary>
    /// 玩家等级不满足入会条件
    /// </summary>
    [pbr::OriginalName("GuildPlayerLevelTooLow")] GuildPlayerLevelTooLow = 123,
    /// <summary>
    /// 战力不满足入会条件
    /// </summary>
    [pbr::OriginalName("GuildFightingTooLow")] GuildFightingTooLow = 124,
    /// <summary>
    /// 邮件内容为空
    /// </summary>
    [pbr::OriginalName("GuildMailEmpty")] GuildMailEmpty = 125,
    /// <summary>
    /// 邮件内容过长
    /// </summary>
    [pbr::OriginalName("GuildMailTooLarge")] GuildMailTooLarge = 126,
    /// <summary>
    /// 公会职务人数已满
    /// </summary>
    [pbr::OriginalName("GuildJobFull")] GuildJobFull = 127,
    /// <summary>
    /// 公会职务不存在
    /// </summary>
    [pbr::OriginalName("GuildJobNotExist")] GuildJobNotExist = 128,
    /// <summary>
    /// 已邀请该玩家
    /// </summary>
    [pbr::OriginalName("GuildAlreadyInvite")] GuildAlreadyInvite = 129,
    /// <summary>
    /// 邀请不存在
    /// </summary>
    [pbr::OriginalName("GuildInviteNotExist")] GuildInviteNotExist = 130,
    /// <summary>
    ///建筑不存在
    /// </summary>
    [pbr::OriginalName("GuildBuildingNotExist")] GuildBuildingNotExist = 131,
    /// <summary>
    ///建筑无法再升级
    /// </summary>
    [pbr::OriginalName("GuildBuildingAlreadyMax")] GuildBuildingAlreadyMax = 132,
    /// <summary>
    /// 公会等级不足
    /// </summary>
    [pbr::OriginalName("GuildLevelNoEnough")] GuildLevelNoEnough = 133,
    /// <summary>
    /// 公会金钱不足
    /// </summary>
    [pbr::OriginalName("GuildMoneyNoEnough")] GuildMoneyNoEnough = 134,
    /// <summary>
    /// 邮件群发CD中
    /// </summary>
    [pbr::OriginalName("GuildMailBroadcastCD")] GuildMailBroadcastCd = 135,
    /// <summary>
    /// 加入公会CD中
    /// </summary>
    [pbr::OriginalName("GuildRejoinCD")] GuildRejoinCd = 136,
    /// <summary>
    ///没有足够的挑战次数
    /// </summary>
    [pbr::OriginalName("NotEnoughChallengeNum")] NotEnoughChallengeNum = 137,
    /// <summary>
    ///失败的获取任务奖励
    /// </summary>
    [pbr::OriginalName("FailedToGetQuestAward")] FailedToGetQuestAward = 138,
    /// <summary>
    ///失败的获取活跃值奖励
    /// </summary>
    [pbr::OriginalName("FailedToGetActiveValueAward")] FailedToGetActiveValueAward = 139,
    /// <summary>
    ///列传传上来的参数不对
    /// </summary>
    [pbr::OriginalName("InvalidLieZhuanParm")] InvalidLieZhuanParm = 140,
    /// <summary>
    ///达到购买上限
    /// </summary>
    [pbr::OriginalName("AlreadyBuyLimit")] AlreadyBuyLimit = 141,
    /// <summary>
    /// redisKey错误
    /// </summary>
    [pbr::OriginalName("RedisKeyError")] RedisKeyError = 142,
    /// <summary>
    /// redis获取排行数据失败
    /// </summary>
    [pbr::OriginalName("RedisRankError")] RedisRankError = 143,
    /// <summary>
    /// redis数据为空
    /// </summary>
    [pbr::OriginalName("RedisDataEmpty")] RedisDataEmpty = 144,
    /// <summary>
    /// 远征关卡错误
    /// </summary>
    [pbr::OriginalName("ExpeditionLevelError")] ExpeditionLevelError = 145,
    /// <summary>
    /// 远征没有挑战次数
    /// </summary>
    [pbr::OriginalName("ExpeditionChallengeNoCount")] ExpeditionChallengeNoCount = 146,
    /// <summary>
    /// 远征关卡重置中
    /// </summary>
    [pbr::OriginalName("ExpeditionReseting")] ExpeditionReseting = 147,
    /// <summary>
    /// 远征挑战中
    /// </summary>
    [pbr::OriginalName("ExpeditionChallenging")] ExpeditionChallenging = 148,
    /// <summary>
    ///系统还未开启
    /// </summary>
    [pbr::OriginalName("NotSystemOpen")] NotSystemOpen = 149,
    /// <summary>
    ///清空数据库表
    /// </summary>
    [pbr::OriginalName("FailedToTruncateTable")] FailedToTruncateTable = 150,
    /// <summary>
    ///搜索好友失败
    /// </summary>
    [pbr::OriginalName("FailedToFindFriend")] FailedToFindFriend = 151,
    /// <summary>
    ///失败的进行ZRangeByScore
    /// </summary>
    [pbr::OriginalName("FailedToZRangeByScore")] FailedToZrangeByScore = 152,
    /// <summary>
    ///失败的存储事务
    /// </summary>
    [pbr::OriginalName("FailedToStoreAnyTable")] FailedToStoreAnyTable = 153,
    /// <summary>
    ///QueryDb失败
    /// </summary>
    [pbr::OriginalName("FailedToQueryDb")] FailedToQueryDb = 154,
    /// <summary>
    ///pb解析失败
    /// </summary>
    [pbr::OriginalName("FailedToDecodePbData")] FailedToDecodePbData = 155,
    /// <summary>
    ///QueryDb失败
    /// </summary>
    [pbr::OriginalName("QueryDb_NotData")] QueryDbNotData = 156,
    /// <summary>
    ///装饰不存在
    /// </summary>
    [pbr::OriginalName("HomeOrnamentNotExist")] HomeOrnamentNotExist = 157,
    /// <summary>
    ///装饰数量为0
    /// </summary>
    [pbr::OriginalName("HomeOrnamentEmpty")] HomeOrnamentEmpty = 158,
    /// <summary>
    ///家园建筑不存在
    /// </summary>
    [pbr::OriginalName("HomeBuildingNotExist")] HomeBuildingNotExist = 159,
    /// <summary>
    ///家园建筑已存在
    /// </summary>
    [pbr::OriginalName("HomeBuildingAlreadyExist")] HomeBuildingAlreadyExist = 160,
    /// <summary>
    ///家园建筑已经最大级
    /// </summary>
    [pbr::OriginalName("HomeBuildingAlreadyMax")] HomeBuildingAlreadyMax = 161,
    /// <summary>
    ///家园英雄不存在
    /// </summary>
    [pbr::OriginalName("HomeHeroNotExist")] HomeHeroNotExist = 162,
    /// <summary>
    ///家园英雄好剧情配置错误
    /// </summary>
    [pbr::OriginalName("HomeHeroStoryCfgError")] HomeHeroStoryCfgError = 163,
    /// <summary>
    ///家园英雄已在场景中
    /// </summary>
    [pbr::OriginalName("HomeHeroAlreayInScene")] HomeHeroAlreayInScene = 164,
    /// <summary>
    ///家园英与喜欢的饰物互动次数不足
    /// </summary>
    [pbr::OriginalName("HomeHeroInteractNumNoEnough")] HomeHeroInteractNumNoEnough = 165,
    /// <summary>
    ///异地登录
    /// </summary>
    [pbr::OriginalName("OtherPlatformLogin")] OtherPlatformLogin = 166,
    /// <summary>
    ///家园英雄放置数量超出上限
    /// </summary>
    [pbr::OriginalName("HomeHeroPlaceOverMax")] HomeHeroPlaceOverMax = 167,
    /// <summary>
    ///家园区域不存在
    /// </summary>
    [pbr::OriginalName("HomeRegionNotExist")] HomeRegionNotExist = 168,
    /// <summary>
    ///家园区域未解锁
    /// </summary>
    [pbr::OriginalName("HomeRegionNotUnlock")] HomeRegionNotUnlock = 169,
    /// <summary>
    /// 三消配置ID错误
    /// </summary>
    [pbr::OriginalName("SanxiaoCfgIDError")] SanxiaoCfgIderror = 170,
    /// <summary>
    /// 无尽试炼数据为空
    /// </summary>
    [pbr::OriginalName("TrialDataNil")] TrialDataNil = 172,
    /// <summary>
    /// 无尽试炼阵型错误
    /// </summary>
    [pbr::OriginalName("TrialFormationError")] TrialFormationError = 173,
    /// <summary>
    /// 无尽试炼前端关卡进度错误
    /// </summary>
    [pbr::OriginalName("TrialLevelCfgError")] TrialLevelCfgError = 174,
    /// <summary>
    /// 无尽试炼前端关卡进度错误
    /// </summary>
    [pbr::OriginalName("TrialClientLevelError")] TrialClientLevelError = 175,
    /// <summary>
    /// 无尽试炼战斗未开启
    /// </summary>
    [pbr::OriginalName("TrialBattleNotCreate")] TrialBattleNotCreate = 176,
    /// <summary>
    ///任务完成需要消耗的道具不足
    /// </summary>
    [pbr::OriginalName("QuestConsumeItemNotEnough")] QuestConsumeItemNotEnough = 177,
    /// <summary>
    ///任务不存在
    /// </summary>
    [pbr::OriginalName("QuestNotExist")] QuestNotExist = 178,
    /// <summary>
    ///新账号注册成功
    /// </summary>
    [pbr::OriginalName("AccountNew")] AccountNew = 179,
    /// <summary>
    ///代消发起请求达到上限
    /// </summary>
    [pbr::OriginalName("DaiXiaoReqLimit")] DaiXiaoReqLimit = 180,
    /// <summary>
    ///三消校验超时
    /// </summary>
    [pbr::OriginalName("SanXiaoCheckTimeout")] SanXiaoCheckTimeout = 181,
    /// <summary>
    ///玩家在线数达到峰值
    /// </summary>
    [pbr::OriginalName("PlayerOnlineLimit")] PlayerOnlineLimit = 182,
    /// <summary>
    ///服务器维护
    /// </summary>
    [pbr::OriginalName("ServerMaintain")] ServerMaintain = 183,
    /// <summary>
    ///创角名字长度错误
    /// </summary>
    [pbr::OriginalName("PlayerNameLengthError")] PlayerNameLengthError = 184,
    /// <summary>
    /// 远征无法扫荡
    /// </summary>
    [pbr::OriginalName("ExpeditionCannotSweep")] ExpeditionCannotSweep = 185,
    /// <summary>
    /// 远征扫荡奖励错误
    /// </summary>
    [pbr::OriginalName("ExpeditionSweepAwardError")] ExpeditionSweepAwardError = 186,
    /// <summary>
    ///英雄的星级不够
    /// </summary>
    [pbr::OriginalName("HeroStarNotEnough")] HeroStarNotEnough = 187,
    /// <summary>
    ///代消失效
    /// </summary>
    [pbr::OriginalName("DaiXiaoLoseEfficacy")] DaiXiaoLoseEfficacy = 189,
    /// <summary>
    ///开天牌技能已经装备
    /// </summary>
    [pbr::OriginalName("KTSkillAlreadyEquip")] KtskillAlreadyEquip = 192,
    /// <summary>
    ///开天牌技能槽位不足
    /// </summary>
    [pbr::OriginalName("KTSkillSlotNotEnough")] KtskillSlotNotEnough = 193,
    /// <summary>
    ///开天牌技能没有找到
    /// </summary>
    [pbr::OriginalName("KTSkillNotFound")] KtskillNotFound = 194,
    /// <summary>
    ///繁荣度不够
    /// </summary>
    [pbr::OriginalName("FanRongDuNotEnough")] FanRongDuNotEnough = 195,
    /// <summary>
    ///战斗版本号不匹配
    /// </summary>
    [pbr::OriginalName("BattleVerNotMatch")] BattleVerNotMatch = 196,
    /// <summary>
    ///三消版本号不匹配
    /// </summary>
    [pbr::OriginalName("SanXiaoVerNotMatch")] SanXiaoVerNotMatch = 197,
    /// <summary>
    ///开天牌槽位不足
    /// </summary>
    [pbr::OriginalName("KTSlotNotEnough")] KtslotNotEnough = 198,
    /// <summary>
    ///主角技能不存在
    /// </summary>
    [pbr::OriginalName("PlayerSkillNotFound")] PlayerSkillNotFound = 199,
    /// <summary>
    ///主角技能已经激活
    /// </summary>
    [pbr::OriginalName("PlayerSkillAlreadyActivate")] PlayerSkillAlreadyActivate = 200,
    /// <summary>
    ///主角属性激活失败 不符合激活条件	
    /// </summary>
    [pbr::OriginalName("ActivatePlayerAttrFail")] ActivatePlayerAttrFail = 201,
    /// <summary>
    ///主角配置无效
    /// </summary>
    [pbr::OriginalName("InvalidMainPlayerCfg")] InvalidMainPlayerCfg = 202,
    /// <summary>
    /// redis删除KEY失败
    /// </summary>
    [pbr::OriginalName("FAILED_REDIS_DEL_KEY")] FailedRedisDelKey = 203,
    /// <summary>
    ///这个区域需要三消
    /// </summary>
    [pbr::OriginalName("AreaNeedSanXiao")] AreaNeedSanXiao = 204,
    /// <summary>
    ///失败的获得每日爬塔奖励
    /// </summary>
    [pbr::OriginalName("FailedToGetDailyTowerAward")] FailedToGetDailyTowerAward = 205,
    /// <summary>
    ///商店刷新次数不足
    /// </summary>
    [pbr::OriginalName("StoreRefreshCountNotEnough")] StoreRefreshCountNotEnough = 206,
    /// <summary>
    ///玩家已经被禁言
    /// </summary>
    [pbr::OriginalName("ChatForbidden")] ChatForbidden = 207,
    /// <summary>
    ///玩家账号已经被封
    /// </summary>
    [pbr::OriginalName("PlayerAccountBlock")] PlayerAccountBlock = 208,
    /// <summary>
    ///主角技能升级失败
    /// </summary>
    [pbr::OriginalName("PlayerSkillLVUPFail")] PlayerSkillLvupfail = 209,
    /// <summary>
    ///公会捐献配置错误
    /// </summary>
    [pbr::OriginalName("GuildDonateCfgError")] GuildDonateCfgError = 210,
    /// <summary>
    /// 公会捐献所需道具不足	
    /// </summary>
    [pbr::OriginalName("GuildDonateItemNotEnough")] GuildDonateItemNotEnough = 211,
    /// <summary>
    /// 公会简介文本未发生更改
    /// </summary>
    [pbr::OriginalName("GuildIntroduceNoChange")] GuildIntroduceNoChange = 212,
    /// <summary>
    /// 公会简介文本长度错误
    /// </summary>
    [pbr::OriginalName("GuildIntroduceLengthError")] GuildIntroduceLengthError = 213,
    /// <summary>
    /// 公会权限数据错误
    /// </summary>
    [pbr::OriginalName("GuildAuthorityDataError")] GuildAuthorityDataError = 214,
    /// <summary>
    /// 公会建筑升级中
    /// </summary>
    [pbr::OriginalName("GuildBuildingInUpgrade")] GuildBuildingInUpgrade = 215,
    /// <summary>
    /// 公会拍卖没有物品
    /// </summary>
    [pbr::OriginalName("GuildAuctionNoItem")] GuildAuctionNoItem = 216,
    /// <summary>
    /// 公会拍卖未开始
    /// </summary>
    [pbr::OriginalName("GuildAuctionNoDoing")] GuildAuctionNoDoing = 217,
    /// <summary>
    /// 公会拍卖物品不存在
    /// </summary>
    [pbr::OriginalName("GuildAuctionItemNotExist")] GuildAuctionItemNotExist = 218,
    /// <summary>
    /// 公会拍卖重复竞价
    /// </summary>
    [pbr::OriginalName("GuildAuctionItemAlreayBid")] GuildAuctionItemAlreayBid = 219,
    /// <summary>
    /// 公会拍卖费用不足
    /// </summary>
    [pbr::OriginalName("GuildAuctionItemNotEnough")] GuildAuctionItemNotEnough = 220,
    /// <summary>
    /// 公会拍卖结束
    /// </summary>
    [pbr::OriginalName("GuildAuctionItemAlreadyFinished")] GuildAuctionItemAlreadyFinished = 221,
    /// <summary>
    /// 物品已竞拍成功
    /// </summary>
    [pbr::OriginalName("GuildAuctionItemAlreadyBuy")] GuildAuctionItemAlreadyBuy = 222,
    /// <summary>
    /// 公会等级已经是最大等级
    /// </summary>
    [pbr::OriginalName("GuildSkillAlreadyMax")] GuildSkillAlreadyMax = 223,
    /// <summary>
    /// 公会BOSS没有次数
    /// </summary>
    [pbr::OriginalName("GuildBossNoCount")] GuildBossNoCount = 224,
    /// <summary>
    /// 公会BOSS配置错误
    /// </summary>
    [pbr::OriginalName("GuildBossLevelCfgError")] GuildBossLevelCfgError = 225,
    /// <summary>
    /// 公会BOSS已死亡
    /// </summary>
    [pbr::OriginalName("GuildBossIsDead")] GuildBossIsDead = 226,
    /// <summary>
    /// 公会任务不存在
    /// </summary>
    [pbr::OriginalName("GuildQuestNotExist")] GuildQuestNotExist = 227,
    /// <summary>
    /// 公会任务未开启
    /// </summary>
    [pbr::OriginalName("GuildQuestNotOpen")] GuildQuestNotOpen = 228,
    /// <summary>
    /// 公会任务超出最大数量
    /// </summary>
    [pbr::OriginalName("GuildQuestOverMax")] GuildQuestOverMax = 229,
    /// <summary>
    ///引导达到上限
    /// </summary>
    [pbr::OriginalName("GuidanceLimit")] GuidanceLimit = 234,
    /// <summary>
    ///家园剧情上限
    /// </summary>
    [pbr::OriginalName("StoryProgressLimit")] StoryProgressLimit = 235,
    /// <summary>
    ///法相已经装备了英雄
    /// </summary>
    [pbr::OriginalName("AlreadyEquipHero")] AlreadyEquipHero = 236,
    /// <summary>
    ///共鸣英雄达到上限
    /// </summary>
    [pbr::OriginalName("GongMingHeroLimit")] GongMingHeroLimit = 237,
    /// <summary>
    ///法相升级失败
    /// </summary>
    [pbr::OriginalName("FailedToFXLevelUp")] FailedToFxlevelUp = 238,
    /// <summary>
    ///失败的获取主线关卡奖励
    /// </summary>
    [pbr::OriginalName("FailedGetLevelBox")] FailedGetLevelBox = 239,
    /// <summary>
    ///没有找到挑战者
    /// </summary>
    [pbr::OriginalName("NotFoundChallenger")] NotFoundChallenger = 240,
    /// <summary>
    ///阵营已设置
    /// </summary>
    [pbr::OriginalName("FactionTypeAlreadySet")] FactionTypeAlreadySet = 241,
    /// <summary>
    ///阵营类型错误
    /// </summary>
    [pbr::OriginalName("FactionTypeError")] FactionTypeError = 242,
    /// <summary>
    ///聊天请求超时
    /// </summary>
    [pbr::OriginalName("ChatReqTimeOut")] ChatReqTimeOut = 243,
    /// <summary>
    ///聊天频率受限
    /// </summary>
    [pbr::OriginalName("ChatFrequencyLimit")] ChatFrequencyLimit = 244,
    /// <summary>
    ///存储redis list 失败
    /// </summary>
    [pbr::OriginalName("RedisListStoreError")] RedisListStoreError = 245,
    /// <summary>
    ///失败的进行LRANGE
    /// </summary>
    [pbr::OriginalName("FailedToLRANGE")] FailedToLrange = 246,
    /// <summary>
    ///失败的获取聊天信息
    /// </summary>
    [pbr::OriginalName("FailedToGetChatMsgByRoomD")] FailedToGetChatMsgByRoomD = 247,
    /// <summary>
    ///失败签到
    /// </summary>
    [pbr::OriginalName("FailedToSignIn")] FailedToSignIn = 248,
    /// <summary>
    ///签到重置中
    /// </summary>
    [pbr::OriginalName("SignInReset")] SignInReset = 249,
    /// <summary>
    ///接受邀请失败 已有玩家率先进入协助
    /// </summary>
    [pbr::OriginalName("AcceptAssistFailLate")] AcceptAssistFailLate = 250,
    /// <summary>
    ///接受邀请失败 求助玩家已经过关
    /// </summary>
    [pbr::OriginalName("AcceptAssistFailPassLevel")] AcceptAssistFailPassLevel = 251,
    /// <summary>
    ///加入副本失败 已经在副本中
    /// </summary>
    [pbr::OriginalName("AssistEnterFailAlreadyIn")] AssistEnterFailAlreadyIn = 252,
    /// <summary>
    ///保存阵容失败
    /// </summary>
    [pbr::OriginalName("AssistSaveEmbattleInfoFail")] AssistSaveEmbattleInfoFail = 253,
    /// <summary>
    ///次数用尽
    /// </summary>
    [pbr::OriginalName("AssistNoTimes")] AssistNoTimes = 254,
    /// <summary>
    ///发出邀请失败
    /// </summary>
    [pbr::OriginalName("InviteAssistReqFail")] InviteAssistReqFail = 255,
    /// <summary>
    ///接受邀请失败 关卡等级不符合协助玩家自己的协助副本层数＜求助层数
    /// </summary>
    [pbr::OriginalName("AcceptAssistFailLevel")] AcceptAssistFailLevel = 256,
    /// <summary>
    ///接受邀请失败 玩家退出副本
    /// </summary>
    [pbr::OriginalName("AcceptAssistFailNoPlayer")] AcceptAssistFailNoPlayer = 257,
    /// <summary>
    ///加入副本失败 副本未开启
    /// </summary>
    [pbr::OriginalName("AssistEnterFailNotOpen")] AssistEnterFailNotOpen = 258,
    /// <summary>
    /// 邀请的玩家未准备就绪
    /// </summary>
    [pbr::OriginalName("AssistHelpPlayerNotReady")] AssistHelpPlayerNotReady = 259,
    /// <summary>
    ///不存在的玩家
    /// </summary>
    [pbr::OriginalName("AssistPlayerInValid")] AssistPlayerInValid = 260,
    /// <summary>
    ///协助副本扫荡失败 错误的等级
    /// </summary>
    [pbr::OriginalName("AssistSweepWrongLevel")] AssistSweepWrongLevel = 261,
    /// <summary>
    /// 玩家还未选择阵营
    /// </summary>
    [pbr::OriginalName("GuildPlayerNoFaction")] GuildPlayerNoFaction = 262,
    /// <summary>
    /// 公会阵营不一致
    /// </summary>
    [pbr::OriginalName("GuildFactionNotMatch")] GuildFactionNotMatch = 263,
    /// <summary>
    /// 不能加入这个公会阵营
    /// </summary>
    [pbr::OriginalName("GuildCanotApplyThisFaction")] GuildCanotApplyThisFaction = 264,
    /// <summary>
    /// 查找名字不合法
    /// </summary>
    [pbr::OriginalName("GuildSearchNameInvalid")] GuildSearchNameInvalid = 265,
    /// <summary>
    ///登录Token无效
    /// </summary>
    [pbr::OriginalName("LoginTokenInvaild")] LoginTokenInvaild = 266,
    /// <summary>
    ///喜讯点赞失败
    /// </summary>
    [pbr::OriginalName("FailedXiXunDianZan")] FailedXiXunDianZan = 267,
    /// <summary>
    ///陌生人聊天失败
    /// </summary>
    [pbr::OriginalName("FailedStangerChat")] FailedStangerChat = 268,
    /// <summary>
    ///失败的拉黑
    /// </summary>
    [pbr::OriginalName("FailedBlackFriend")] FailedBlackFriend = 269,
    /// <summary>
    /// 未实名验证
    /// </summary>
    [pbr::OriginalName("RealUserNotVerification")] RealUserNotVerification = 270,
    /// <summary>
    /// 未成年限制时间段
    /// </summary>
    [pbr::OriginalName("NonageCanotPlayTime")] NonageCanotPlayTime = 271,
    /// <summary>
    /// 未成年超出在线时长
    /// </summary>
    [pbr::OriginalName("NonageOverPlayTime")] NonageOverPlayTime = 272,
    /// <summary>
    ///支付请求超时
    /// </summary>
    [pbr::OriginalName("PayReqTimeOut")] PayReqTimeOut = 273,
    /// <summary>
    ///支付请求失败
    /// </summary>
    [pbr::OriginalName("PayReqFail")] PayReqFail = 274,
    /// <summary>
    ///爬塔战力错误
    /// </summary>
    [pbr::OriginalName("FailedTowerPower")] FailedTowerPower = 275,
    /// <summary>
    ///心跳超时
    /// </summary>
    [pbr::OriginalName("HeartbeatTimeout")] HeartbeatTimeout = 276,
    /// <summary>
    ///充值商品错误
    /// </summary>
    [pbr::OriginalName("RechargeStoreCfgError")] RechargeStoreCfgError = 277,
    /// <summary>
    ///购买抽卡券次数不足
    /// </summary>
    [pbr::OriginalName("BuyChoukaNoTimes")] BuyChoukaNoTimes = 278,
    /// <summary>
    ///未成人单次充值金额限制
    /// </summary>
    [pbr::OriginalName("RechargeNonageOnceLimit")] RechargeNonageOnceLimit = 279,
    /// <summary>
    ///未成人每月充值金额限制
    /// </summary>
    [pbr::OriginalName("RechargeNonageMonthLimit")] RechargeNonageMonthLimit = 280,
    /// <summary>
    ///爬塔战力错误
    /// </summary>
    [pbr::OriginalName("FailedExpeditionPower")] FailedExpeditionPower = 281,
    /// <summary>
    ///抽卡次数不足
    /// </summary>
    [pbr::OriginalName("NotEnoughChouKaCount")] NotEnoughChouKaCount = 282,
    /// <summary>
    /// 未成年登录年龄限制
    /// </summary>
    [pbr::OriginalName("NonageLoginAgeLimit")] NonageLoginAgeLimit = 283,
    /// <summary>
    /// GM踢下线
    /// </summary>
    [pbr::OriginalName("GMKickOut")] GmkickOut = 284,
    /// <summary>
    ///需要进行三消
    /// </summary>
    [pbr::OriginalName("NeedLieZhuanSanXiao")] NeedLieZhuanSanXiao = 285,
    /// <summary>
    ///星君领取奖励失败
    /// </summary>
    [pbr::OriginalName("XingJunRewardFail")] XingJunRewardFail = 286,
    /// <summary>
    ///玩家存储数据是吧
    /// </summary>
    [pbr::OriginalName("ServerDataReqFail")] ServerDataReqFail = 287,
    /// <summary>
    ///活动结束
    /// </summary>
    [pbr::OriginalName("RingActivityAlreadyEnd")] RingActivityAlreadyEnd = 288,
    /// <summary>
    ///活动未开启
    /// </summary>
    [pbr::OriginalName("RingActivityNotStart")] RingActivityNotStart = 289,
    /// <summary>
    ///活动未知错误
    /// </summary>
    [pbr::OriginalName("ActivityStateError")] ActivityStateError = 290,
    /// <summary>
    ///重复报名
    /// </summary>
    [pbr::OriginalName("RingRepeatApply")] RingRepeatApply = 291,
    /// <summary>
    /// 主线关卡未解锁
    /// </summary>
    [pbr::OriginalName("ChapterLevelNotOpen")] ChapterLevelNotOpen = 292,
    /// <summary>
    /// 玩家消除宝典数据错误
    /// </summary>
    [pbr::OriginalName("SanXiaoBaoDianDataError")] SanXiaoBaoDianDataError = 293,
    /// <summary>
    /// 玩家消除宝典排行数据错误
    /// </summary>
    [pbr::OriginalName("SanXiaoBaoDianRankDataError")] SanXiaoBaoDianRankDataError = 294,
    /// <summary>
    ///没有足够的挑战次数
    /// </summary>
    [pbr::OriginalName("RingNouEnoughChallengeNum")] RingNouEnoughChallengeNum = 295,
    /// <summary>
    ///擂台没有报名
    /// </summary>
    [pbr::OriginalName("RingNotApply")] RingNotApply = 296,
    /// <summary>
    /// 公会任务发布量不足
    /// </summary>
    [pbr::OriginalName("GuildQuestNotEnough")] GuildQuestNotEnough = 297,
    /// <summary>
    ///擂台报名达到上限
    /// </summary>
    [pbr::OriginalName("RingApplyLimit")] RingApplyLimit = 298,
    /// <summary>
    ///redis Get命令请求失败
    /// </summary>
    [pbr::OriginalName("RedisGetError")] RedisGetError = 299,
    /// <summary>
    ///redis Set命令请求失败
    /// </summary>
    [pbr::OriginalName("RedisSetError")] RedisSetError = 300,
    /// <summary>
    ///redis key 不存在
    /// </summary>
    [pbr::OriginalName("RedisKeyNotExist")] RedisKeyNotExist = 301,
    /// <summary>
    ///已经领取过FB奖励邮件
    /// </summary>
    [pbr::OriginalName("FBMailAlreadyGet")] FbmailAlreadyGet = 302,
    /// <summary>
    ///失败的插入DB
    /// </summary>
    [pbr::OriginalName("FailedToDBInsert")] FailedToDbinsert = 303,
    /// <summary>
    ///DBUpdate失败
    /// </summary>
    [pbr::OriginalName("FailedToDBUpdate")] FailedToDbupdate = 304,
    /// <summary>
    ///DB创建PlayerNameID失败
    /// </summary>
    [pbr::OriginalName("FailedToCreatePlayerNameID")] FailedToCreatePlayerNameId = 305,
    /// <summary>
    ///失败的获取七日奖励
    /// </summary>
    [pbr::OriginalName("FailedToGetSevenDayAward")] FailedToGetSevenDayAward = 306,
    /// <summary>
    ///兑换码已经使用
    /// </summary>
    [pbr::OriginalName("FailGetCodeUsed")] FailGetCodeUsed = 307,
    /// <summary>
    ///没有这个兑换码
    /// </summary>
    [pbr::OriginalName("FailGetCodeNone")] FailGetCodeNone = 308,
    /// <summary>
    ///秘籍未激活
    /// </summary>
    [pbr::OriginalName("PlayerBookNotAcctive")] PlayerBookNotAcctive = 309,
    /// <summary>
    ///秘籍ID错误
    /// </summary>
    [pbr::OriginalName("BookIdNotFind")] BookIdNotFind = 310,
    /// <summary>
    ///此秘籍不适配此心法
    /// </summary>
    [pbr::OriginalName("EquipBookFailNotMatch")] EquipBookFailNotMatch = 311,
    /// <summary>
    ///非法孔位
    /// </summary>
    [pbr::OriginalName("EquipBookllegalPosition")] EquipBookllegalPosition = 312,
    /// <summary>
    ///秘籍升级失败
    /// </summary>
    [pbr::OriginalName("PlayerBookLvUpFail")] PlayerBookLvUpFail = 313,
    /// <summary>
    ///秘籍洗练失败秘籍未机会
    /// </summary>
    [pbr::OriginalName("RefreshBookNotAcctive")] RefreshBookNotAcctive = 314,
    /// <summary>
    ///主角技能未激活
    /// </summary>
    [pbr::OriginalName("PlayerSkillNotAcctive")] PlayerSkillNotAcctive = 315,
    /// <summary>
    ///营地未解锁
    /// </summary>
    [pbr::OriginalName("CampNotUnlock")] CampNotUnlock = 316,
    /// <summary>
    ///营地位置已解锁
    /// </summary>
    [pbr::OriginalName("CampPosAlreadyUnlock")] CampPosAlreadyUnlock = 317,
    /// <summary>
    ///营地位置未解锁
    /// </summary>
    [pbr::OriginalName("CampPosNotUnlock")] CampPosNotUnlock = 318,
    /// <summary>
    ///营地位置解锁错误
    /// </summary>
    [pbr::OriginalName("CampPosUnlockError")] CampPosUnlockError = 319,
    /// <summary>
    ///营地位置没有放置幻灵
    /// </summary>
    [pbr::OriginalName("CampPosNoHero")] CampPosNoHero = 320,
    /// <summary>
    ///营地位置已放置幻灵
    /// </summary>
    [pbr::OriginalName("CampPosAlreadyHasHero")] CampPosAlreadyHasHero = 321,
    /// <summary>
    ///营地位置不能放置此幻灵
    /// </summary>
    [pbr::OriginalName("CampPosCannotPlaceHero")] CampPosCannotPlaceHero = 322,
    /// <summary>
    ///营地幻灵已放置
    /// </summary>
    [pbr::OriginalName("CampHeroAlreadyPlace")] CampHeroAlreadyPlace = 323,
    /// <summary>
    ///英雄星级为0
    /// </summary>
    [pbr::OriginalName("HeroStarEmpty")] HeroStarEmpty = 324,
    /// <summary>
    ///秘籍洗练失败 没有可以洗练的词条
    /// </summary>
    [pbr::OriginalName("RereshSkillBookFailNoEntry")] RereshSkillBookFailNoEntry = 325,
    /// <summary>
    /// 家园商店物品为空
    /// </summary>
    [pbr::OriginalName("HomeStoreItemEmpty")] HomeStoreItemEmpty = 326,
    /// <summary>
    /// 家园建筑配置错误
    /// </summary>
    [pbr::OriginalName("HomeBuildingCfgError")] HomeBuildingCfgError = 327,
    /// <summary>
    /// 家园拜访者已满
    /// </summary>
    [pbr::OriginalName("HomeCourtyardVisitorFull")] HomeCourtyardVisitorFull = 328,
    /// <summary>
    /// 家园被拜访次数不足
    /// </summary>
    [pbr::OriginalName("HomeCourtyardByVisitCountEmpty")] HomeCourtyardByVisitCountEmpty = 329,
    /// <summary>
    /// 家园拜访次数不足
    /// </summary>
    [pbr::OriginalName("HomeCourtyardVisitCountEmpty")] HomeCourtyardVisitCountEmpty = 330,
    /// <summary>
    /// 家园旅馆房间不存在
    /// </summary>
    [pbr::OriginalName("HomeHotelRoomNotExist")] HomeHotelRoomNotExist = 331,
    /// <summary>
    /// 英雄不在这个家园旅馆房间
    /// </summary>
    [pbr::OriginalName("HomeHotelRoomHeroNotExist")] HomeHotelRoomHeroNotExist = 332,
    /// <summary>
    /// 当前房间人数已满，升级舒适度可以增加上场人数
    /// </summary>
    [pbr::OriginalName("HomeHotelRoomHeroFull")] HomeHotelRoomHeroFull = 333,
    /// <summary>
    /// 不能进入这个家园旅馆房间
    /// </summary>
    [pbr::OriginalName("HomeHotelHeroCanotJoinThis")] HomeHotelHeroCanotJoinThis = 334,
    /// <summary>
    /// 家园奇遇次数不足
    /// </summary>
    [pbr::OriginalName("HomeAdventureCountNoEnough")] HomeAdventureCountNoEnough = 335,
    /// <summary>
    /// 家园奇遇节点配置错误
    /// </summary>
    [pbr::OriginalName("HomeAdventureNodeCfgError")] HomeAdventureNodeCfgError = 336,
    /// <summary>
    /// 家园奇遇未开始
    /// </summary>
    [pbr::OriginalName("HomeAdventureNotStart")] HomeAdventureNotStart = 337,
    /// <summary>
    /// 家园奇遇未结束
    /// </summary>
    [pbr::OriginalName("HomeAdventureNotFinished")] HomeAdventureNotFinished = 338,
    /// <summary>
    /// 家园奇遇不是战斗节点
    /// </summary>
    [pbr::OriginalName("HomeAdventureNotBattleNode")] HomeAdventureNotBattleNode = 339,
    /// <summary>
    /// 家园英雄已在种田中
    /// </summary>
    [pbr::OriginalName("HomeFarmHeroAlreadyBusy")] HomeFarmHeroAlreadyBusy = 340,
    /// <summary>
    /// 家园种田好友人数已满
    /// </summary>
    [pbr::OriginalName("HomeFarmFriendHeroOverMax")] HomeFarmFriendHeroOverMax = 341,
    /// <summary>
    /// 家园种田次数不足
    /// </summary>
    [pbr::OriginalName("HomeFarmWorkNoCount")] HomeFarmWorkNoCount = 342,
    /// <summary>
    /// 家园帮助好友种田次数不足
    /// </summary>
    [pbr::OriginalName("HomeFarmFriendWorkNoCount")] HomeFarmFriendWorkNoCount = 343,
    /// <summary>
    /// 家园英雄在好友家种田
    /// </summary>
    [pbr::OriginalName("HomeFarmHeroInFriendHome")] HomeFarmHeroInFriendHome = 344,
    /// <summary>
    /// 家园种田人数已满
    /// </summary>
    [pbr::OriginalName("HomeFarmHeroOverMax")] HomeFarmHeroOverMax = 345,
    /// <summary>
    /// 英雄已经进入旅馆房间
    /// </summary>
    [pbr::OriginalName("HomeHotelHeroAlreadyInRoom")] HomeHotelHeroAlreadyInRoom = 346,
    /// <summary>
    /// 家园旅馆英雄人数已满
    /// </summary>
    [pbr::OriginalName("HomeHotelHeroFull")] HomeHotelHeroFull = 347,
    /// <summary>
    /// 家园旅馆任务已完成
    /// </summary>
    [pbr::OriginalName("HomeHotelQuestFinished")] HomeHotelQuestFinished = 348,
    /// <summary>
    /// redis断连了
    /// </summary>
    [pbr::OriginalName("RedisDisconnect")] RedisDisconnect = 349,
    /// <summary>
    ///抽卡累计次数不足
    /// </summary>
    [pbr::OriginalName("NotEnoughDrawCardCount")] NotEnoughDrawCardCount = 350,
    /// <summary>
    ///觉醒等级错误
    /// </summary>
    [pbr::OriginalName("HeroAwakeWrongLevel")] HeroAwakeWrongLevel = 360,
    /// <summary>
    ///无效的开天牌技能ID
    /// </summary>
    [pbr::OriginalName("InvaildAbilityCfgID")] InvaildAbilityCfgId = 361,
    /// <summary>
    ///开天牌技能槽位不够
    /// </summary>
    [pbr::OriginalName("KTSkillEquipSlotNotEnough")] KtskillEquipSlotNotEnough = 362,
    /// <summary>
    ///幻灵品质不符合
    /// </summary>
    [pbr::OriginalName("HeroAwakeWrongHeroQuality")] HeroAwakeWrongHeroQuality = 363,
    /// <summary>
    ///潜能升级 错误等级
    /// </summary>
    [pbr::OriginalName("HeroPotentialAttrWrongLv")] HeroPotentialAttrWrongLv = 364,
    /// <summary>
    ///血脉之力不足
    /// </summary>
    [pbr::OriginalName("BloodPowerNotEnough")] BloodPowerNotEnough = 365,
    /// <summary>
    /// http请求错误
    /// </summary>
    [pbr::OriginalName("HttpReqError")] HttpReqError = 366,
    /// <summary>
    /// http请求超时  
    /// </summary>
    [pbr::OriginalName("HttpReqTimeout")] HttpReqTimeout = 367,
    /// <summary>
    /// http请求内容解析错误
    /// </summary>
    [pbr::OriginalName("HttpResDecodeError")] HttpResDecodeError = 368,
    /// <summary>
    ///兑换码请求错误
    /// </summary>
    [pbr::OriginalName("RedeemCodeReqError")] RedeemCodeReqError = 369,
    /// <summary>
    ///兑换码已兑换道具
    /// </summary>
    [pbr::OriginalName("RedeemCodeAlreadyGetItem")] RedeemCodeAlreadyGetItem = 370,
    /// <summary>
    ///兑换码正在兑换中
    /// </summary>
    [pbr::OriginalName("RedeemCodeDoing")] RedeemCodeDoing = 371,
    /// <summary>
    /// 请求DB操作超时
    /// </summary>
    [pbr::OriginalName("DBReqTimeout")] DbreqTimeout = 372,
    /// <summary>
    ///布阵失败
    /// </summary>
    [pbr::OriginalName("FailedToEmbattle")] FailedToEmbattle = 373,
    /// <summary>
    ///擂台报名失败
    /// </summary>
    [pbr::OriginalName("FailedToRingApply")] FailedToRingApply = 374,
    /// <summary>
    /// 公会BOSS奖励已领取
    /// </summary>
    [pbr::OriginalName("GuildBossAwardTaked")] GuildBossAwardTaked = 375,
    /// <summary>
    /// 公会BOSS购买次数超出上限
    /// </summary>
    [pbr::OriginalName("GuildBossBuyCountOverMax")] GuildBossBuyCountOverMax = 376,
    /// <summary>
    /// 公会信息KEY不存在
    /// </summary>
    [pbr::OriginalName("GuildInfoKeyNotExist")] GuildInfoKeyNotExist = 377,
    /// <summary>
    ///取消目标镇守失败 还不是目标
    /// </summary>
    [pbr::OriginalName("RemoveTargetGuardNotIs")] RemoveTargetGuardNotIs = 378,
    /// <summary>
    ///邀请镇守失败 在保护时间
    /// </summary>
    [pbr::OriginalName("InviteGuardProtectTime")] InviteGuardProtectTime = 379,
    /// <summary>
    ///邀请镇守失败 已经是本学社的镇守
    /// </summary>
    [pbr::OriginalName("InviteGuardAlreadyIs")] InviteGuardAlreadyIs = 380,
    /// <summary>
    ///邀请镇守失败 在解除绑定后的保护时间
    /// </summary>
    [pbr::OriginalName("InviteGuardRemoveProtectTime")] InviteGuardRemoveProtectTime = 381,
    /// <summary>
    ///邀请镇守失败 好友度不符合
    /// </summary>
    [pbr::OriginalName("InviteGuardFriend")] InviteGuardFriend = 382,
    /// <summary>
    ///邀请失败 工会威望不符合
    /// </summary>
    [pbr::OriginalName("InviteGuardPrestige")] InviteGuardPrestige = 383,
    /// <summary>
    ///未找到对应学社镇守信息
    /// </summary>
    [pbr::OriginalName("GuardNotFound")] GuardNotFound = 384,
    /// <summary>
    ///学社镇守诱惑失败 不能诱惑已经入住本学社的镇守
    /// </summary>
    [pbr::OriginalName("TmptGuardOwner")] TmptGuardOwner = 385,
    /// <summary>
    ///邀请镇守失败 概率失败
    /// </summary>
    [pbr::OriginalName("InviteGuardFail")] InviteGuardFail = 386,
    /// <summary>
    ///邀请镇守失败 每日邀请次数上限
    /// </summary>
    [pbr::OriginalName("InviteGuardNoTimes")] InviteGuardNoTimes = 387,
    /// <summary>
    ///设置目标镇守失败 已经达到最大个数
    /// </summary>
    [pbr::OriginalName("TargetGuardMaxNum")] TargetGuardMaxNum = 388,
    /// <summary>
    ///设置目标镇守失败 已经是目标
    /// </summary>
    [pbr::OriginalName("TargetGuardAlreadyIs")] TargetGuardAlreadyIs = 389,
    /// <summary>
    ///邀请镇守失败 学社拥有镇守已经最大数量
    /// </summary>
    [pbr::OriginalName("InviteGuardMaxNum")] InviteGuardMaxNum = 390,
    /// <summary>
    ///实名认证错误
    /// </summary>
    [pbr::OriginalName("SDKQueryRealNameError")] SdkqueryRealNameError = 391,
    /// <summary>
    ///三消目标错误
    /// </summary>
    [pbr::OriginalName("SanXiaoColletRewardError")] SanXiaoColletRewardError = 392,
    /// <summary>
    ///三消目标为空
    /// </summary>
    [pbr::OriginalName("SanXiaoColletRewardEmpty")] SanXiaoColletRewardEmpty = 393,
    /// <summary>
    ///学社招募道具不足
    /// </summary>
    [pbr::OriginalName("GuildRecruitItemNotEnough")] GuildRecruitItemNotEnough = 394,
    /// <summary>
    ///学社招募消息为空
    /// </summary>
    [pbr::OriginalName("GuildRecruitMsgEmpty")] GuildRecruitMsgEmpty = 395,
    /// <summary>
    ///学社招募消息超出长度
    /// </summary>
    [pbr::OriginalName("GuildRecruitMsgLengthError")] GuildRecruitMsgLengthError = 396,
    /// <summary>
    ///没有布阵英雄	
    /// </summary>
    [pbr::OriginalName("NotEmbattleHero")] NotEmbattleHero = 397,
    /// <summary>
    /// 家宴每日举办次数已用完
    /// </summary>
    [pbr::OriginalName("HomePartyDayHoldCountEmpty")] HomePartyDayHoldCountEmpty = 398,
    /// <summary>
    /// 家宴每周举办次数已用完
    /// </summary>
    [pbr::OriginalName("HomePartyWeekHoldCountEmpty")] HomePartyWeekHoldCountEmpty = 399,
    /// <summary>
    /// 家宴预约时间错误
    /// </summary>
    [pbr::OriginalName("HomePartySubscribeTimeError")] HomePartySubscribeTimeError = 400,
    /// <summary>
    /// 家宴不在开启时间范围
    /// </summary>
    [pbr::OriginalName("HomePartyNotOpenTime")] HomePartyNotOpenTime = 401,
    /// <summary>
    /// 家宴开启时间已过期
    /// </summary>
    [pbr::OriginalName("HomePartyIsExpired")] HomePartyIsExpired = 402,
    /// <summary>
    /// 家宴不存在
    /// </summary>
    [pbr::OriginalName("HomePartyNotExist")] HomePartyNotExist = 403,
    /// <summary>
    /// 没有家宴开启权限
    /// </summary>
    [pbr::OriginalName("HomePartyNoOpenAuthority")] HomePartyNoOpenAuthority = 404,
    /// <summary>
    /// 家宴礼物不存在
    /// </summary>
    [pbr::OriginalName("HomePartyGiftNotExist")] HomePartyGiftNotExist = 405,
    /// <summary>
    /// 家宴每日吃席次数已用完
    /// </summary>
    [pbr::OriginalName("HomePartyJoinCountEmpty")] HomePartyJoinCountEmpty = 406,
    /// <summary>
    /// 玩家未加入家宴
    /// </summary>
    [pbr::OriginalName("HomePartyPlayerNotJoin")] HomePartyPlayerNotJoin = 407,
    /// <summary>
    /// 玩家已送礼
    /// </summary>
    [pbr::OriginalName("HomePartyPlayerAlreadyGift")] HomePartyPlayerAlreadyGift = 408,
    /// <summary>
    /// 家宴已开启
    /// </summary>
    [pbr::OriginalName("HomePartyAlreadyOpen")] HomePartyAlreadyOpen = 409,
    /// <summary>
    /// 家宴已被拾取
    /// </summary>
    [pbr::OriginalName("HomePartyAlreadyGet")] HomePartyAlreadyGet = 410,
    /// <summary>
    /// 家宴玩家没有撒糖操作权限
    /// </summary>
    [pbr::OriginalName("HomePartyCannotScatterSugar")] HomePartyCannotScatterSugar = 411,
    /// <summary>
    /// 家宴参加人数已满
    /// </summary>
    [pbr::OriginalName("HomePartyPlayerCountFull")] HomePartyPlayerCountFull = 412,
    /// <summary>
    /// 家宴玩家正忙
    /// </summary>
    [pbr::OriginalName("HomePartyPlayerBusy")] HomePartyPlayerBusy = 413,
    /// <summary>
    /// 已邀请对方
    /// </summary>
    [pbr::OriginalName("HomePartyDanceAlreadyInvite")] HomePartyDanceAlreadyInvite = 414,
    /// <summary>
    /// 共舞邀请已过期
    /// </summary>
    [pbr::OriginalName("HomePartyDanceInviteExpired")] HomePartyDanceInviteExpired = 415,
    /// <summary>
    /// 烟花未放置
    /// </summary>
    [pbr::OriginalName("HomePartyFireworkNotPlace")] HomePartyFireworkNotPlace = 416,
    /// <summary>
    /// 已吃完菜
    /// </summary>
    [pbr::OriginalName("HomePartyAlreadyEatDish")] HomePartyAlreadyEatDish = 417,
    /// <summary>
    ///需要进行三消
    /// </summary>
    [pbr::OriginalName("NeedGuardBossSanXiao")] NeedGuardBossSanXiao = 418,
    /// <summary>
    ///邀请镇守失败 该镇守现在正在镇守BOSS活动中
    /// </summary>
    [pbr::OriginalName("InviteGuardInBossTime")] InviteGuardInBossTime = 419,
    /// <summary>
    ///公会消息侦查次数不足
    /// </summary>
    [pbr::OriginalName("GuildMsgInvestigateCountNotEnough")] GuildMsgInvestigateCountNotEnough = 420,
    /// <summary>
    ///镇守BOSS最大鼓舞次数
    /// </summary>
    [pbr::OriginalName("GuardBossInspireMaxNum")] GuardBossInspireMaxNum = 421,
    /// <summary>
    /// 获取镇守BOSS排行榜列表失败  活动状态错误
    /// </summary>
    [pbr::OriginalName("GetBossDamageRankListWrongState")] GetBossDamageRankListWrongState = 422,
    /// <summary>
    /// 公会建筑升级事件不存在
    /// </summary>
    [pbr::OriginalName("GuildBuildEventNotExist")] GuildBuildEventNotExist = 423,
    /// <summary>
    /// 公会建筑升级事件已结束
    /// </summary>
    [pbr::OriginalName("GuildBuildEventAreadyFinish")] GuildBuildEventAreadyFinish = 424,
    /// <summary>
    /// 获取宝箱失败 宝箱不存在
    /// </summary>
    [pbr::OriginalName("GetBossBoxNotExit")] GetBossBoxNotExit = 425,
    /// <summary>
    /// 家宴未开启
    /// </summary>
    [pbr::OriginalName("HomePartyNotOpen")] HomePartyNotOpen = 426,
    /// <summary>
    /// 公会拍卖分红已领取
    /// </summary>
    [pbr::OriginalName("GuildAuctionBonusAlreadyGet")] GuildAuctionBonusAlreadyGet = 427,
    /// <summary>
    /// 没有公会拍卖分红
    /// </summary>
    [pbr::OriginalName("GuildNoAuctionBonus")] GuildNoAuctionBonus = 428,
    /// <summary>
    /// 烟花不存在
    /// </summary>
    [pbr::OriginalName("HomePartyFireworkNotExist")] HomePartyFireworkNotExist = 429,
    /// <summary>
    /// 7-14日购买失败
    /// </summary>
    [pbr::OriginalName("FailedToSevenFourteenSaleItem")] FailedToSevenFourteenSaleItem = 430,
    /// <summary>
    /// 7-14日活跃值失败
    /// </summary>
    [pbr::OriginalName("FailedToSevenFourteenActiveItem")] FailedToSevenFourteenActiveItem = 431,
    /// <summary>
    ///获取兑换码礼包失败
    /// </summary>
    [pbr::OriginalName("FailedGetCodeReward")] FailedGetCodeReward = 432,
    /// <summary>
    /// redis错误 成员已经存在
    /// </summary>
    [pbr::OriginalName("RedisMemberExist")] RedisMemberExist = 433,
    /// <summary>
    /// </summary>
    [pbr::OriginalName("RedisSAddError")] RedisSaddError = 434,
    /// <summary>
    /// 工会状态非正常 不能参加镇守活动
    /// </summary>
    [pbr::OriginalName("InGuildWrongState")] InGuildWrongState = 435,
    /// <summary>
    ///镇守活动中
    /// </summary>
    [pbr::OriginalName("GuardInBossTime")] GuardInBossTime = 436,
    /// <summary>
    /// 家宴酿酒次数已用完
    /// </summary>
    [pbr::OriginalName("HomePartyNoWineCount")] HomePartyNoWineCount = 437,
    /// <summary>
    /// 家宴邀请玩家不存在
    /// </summary>
    [pbr::OriginalName("HomePartyInvitePlayerNotExist")] HomePartyInvitePlayerNotExist = 438,
    /// <summary>
    /// 强盗已经死亡
    /// </summary>
    [pbr::OriginalName("HomePartyRobberDied")] HomePartyRobberDied = 439,
    /// <summary>
    /// 家宴吃菜活动结束
    /// </summary>
    [pbr::OriginalName("HomePartyGameEatAlreadyFinish")] HomePartyGameEatAlreadyFinish = 440,
    /// <summary>
    /// 家宴集体气氛值奖励配置错误
    /// </summary>
    [pbr::OriginalName("HomePartyFinishAwardCfgError")] HomePartyFinishAwardCfgError = 441,
    /// <summary>
    /// 家宴游戏错误
    /// </summary>
    [pbr::OriginalName("HomePartyGameError")] HomePartyGameError = 442,
    /// <summary>
    /// 家宴个人气氛值奖励配置错误
    /// </summary>
    [pbr::OriginalName("HomePartyAtmosphereAchieveCfgError")] HomePartyAtmosphereAchieveCfgError = 443,
    /// <summary>
    /// 家宴个人气氛值不足
    /// </summary>
    [pbr::OriginalName("HomePartyAtmosphereNoEnough")] HomePartyAtmosphereNoEnough = 444,
    /// <summary>
    /// 家宴个人气氛值奖励已领取
    /// </summary>
    [pbr::OriginalName("HomePartyAtmosphereAchieveAwardAlreadyGet")] HomePartyAtmosphereAchieveAwardAlreadyGet = 445,
    /// <summary>
    /// 设置预设阵容失败
    /// </summary>
    [pbr::OriginalName("FailedToSetEmbattleIndex")] FailedToSetEmbattleIndex = 446,
    /// <summary>
    /// 没有找到玩家
    /// </summary>
    [pbr::OriginalName("NotFoundPlayerInfo")] NotFoundPlayerInfo = 447,
    /// <summary>
    /// 好友羁绊等级不足
    /// </summary>
    [pbr::OriginalName("FriendJiBanLvNoEnough")] FriendJiBanLvNoEnough = 448,
    /// <summary>
    /// 家宴集体气氛值奖励已领取
    /// </summary>
    [pbr::OriginalName("HomePartyAtmospherAwardAlreadyGet")] HomePartyAtmospherAwardAlreadyGet = 449,
    /// <summary>
    /// 已加入此宴会
    /// </summary>
    [pbr::OriginalName("HomePartyAlreadyJoin")] HomePartyAlreadyJoin = 450,
    /// <summary>
    /// 家宴活动结束
    /// </summary>
    [pbr::OriginalName("HomePartyAlreadyFinish")] HomePartyAlreadyFinish = 451,
    /// <summary>
    /// 公会妖兽难度未通关
    /// </summary>
    [pbr::OriginalName("GuildBossGroupNotPass")] GuildBossGroupNotPass = 452,
    /// <summary>
    /// 公会妖兽难度配置错误
    /// </summary>
    [pbr::OriginalName("GuildBossGroupCfgError")] GuildBossGroupCfgError = 453,
    /// <summary>
    ///代消未完成
    /// </summary>
    [pbr::OriginalName("DaiXiaoNotFinish")] DaiXiaoNotFinish = 454,
    /// <summary>
    ///代消已经失效
    /// </summary>
    [pbr::OriginalName("DaiXiaoNotInvalid")] DaiXiaoNotInvalid = 455,
    /// <summary>
    /// 家宴宾客数量超出最大数量
    /// </summary>
    [pbr::OriginalName("HomePartyGuestOverMax")] HomePartyGuestOverMax = 456,
    /// <summary>
    /// 家宴主宾客数量超出最大数量
    /// </summary>
    [pbr::OriginalName("HomePartyMainGuestOverMax")] HomePartyMainGuestOverMax = 457,
    /// <summary>
    ///领取战令奖励章节配置不存在
    /// </summary>
    [pbr::OriginalName("ZhangLingCfgNotExist")] ZhangLingCfgNotExist = 458,
    /// <summary>
    ///战令未解锁
    /// </summary>
    [pbr::OriginalName("ZhangLingNotUnlock")] ZhangLingNotUnlock = 459,
    /// <summary>
    ///已经领取过
    /// </summary>
    [pbr::OriginalName("ZhangLingAlreadyGet")] ZhangLingAlreadyGet = 460,
    /// <summary>
    ///账号平台绑定奖励已经领取过
    /// </summary>
    [pbr::OriginalName("AccountBindRewardGetAlready")] AccountBindRewardGetAlready = 461,
    /// <summary>
    ///账号平台绑定奖励领取失败
    /// </summary>
    [pbr::OriginalName("AccountBindRewardGetFail")] AccountBindRewardGetFail = 462,
    /// <summary>
    /// 上古遗迹无效的关卡
    /// </summary>
    [pbr::OriginalName("ShangGuYiJiInvalidLevelID")] ShangGuYiJiInvalidLevelId = 463,
    /// <summary>
    /// 上古遗迹快捷奖励次数不足
    /// </summary>
    [pbr::OriginalName("ShangGuShortcutNotEnough")] ShangGuShortcutNotEnough = 464,
    /// <summary>
    /// 支付订单错误
    /// </summary>
    [pbr::OriginalName("RechargeOrderError")] RechargeOrderError = 465,
    /// <summary>
    ///战斗录像已经过期
    /// </summary>
    [pbr::OriginalName("BattleVideoExpire")] BattleVideoExpire = 466,
    /// <summary>
    ///任务未完成
    /// </summary>
    [pbr::OriginalName("QuestNotFinished")] QuestNotFinished = 467,
    /// <summary>
    ///全服战令购买次数未达标
    /// </summary>
    [pbr::OriginalName("ZhangLingPayCountNotEnough")] ZhangLingPayCountNotEnough = 468,
    /// <summary>
    ///战令购买条件不符合
    /// </summary>
    [pbr::OriginalName("ZhangLingPayCheckError")] ZhangLingPayCheckError = 469,
    /// <summary>
    ///战令未付款
    /// </summary>
    [pbr::OriginalName("ZhangLingNotPay")] ZhangLingNotPay = 470,
    /// <summary>
    ///印记已经装备
    /// </summary>
    [pbr::OriginalName("AlreadyEquipStamp")] AlreadyEquipStamp = 471,
    /// <summary>
    ///印记锁住了
    /// </summary>
    [pbr::OriginalName("StampLock")] StampLock = 472,
    /// <summary>
    ///月卡过期 
    /// </summary>
    [pbr::OriginalName("YueKaOutOfTime")] YueKaOutOfTime = 473,
    /// <summary>
    ///当日月卡已经领取过
    /// </summary>
    [pbr::OriginalName("YueKaRewardAlreadyGet")] YueKaRewardAlreadyGet = 474,
    /// <summary>
    ///月卡购买条件不符合
    /// </summary>
    [pbr::OriginalName("YueKaPayCheckError")] YueKaPayCheckError = 475,
    /// <summary>
    ///月卡未购买 领取奖励失败
    /// </summary>
    [pbr::OriginalName("YueKaNotBuy")] YueKaNotBuy = 476,
    /// <summary>
    ///爬塔每日挑战次数用完
    /// </summary>
    [pbr::OriginalName("ClimbTowerNoTimes")] ClimbTowerNoTimes = 477,
    /// <summary>
    ///家园农场槽位错误
    /// </summary>
    [pbr::OriginalName("HomeFarmPosError")] HomeFarmPosError = 478,
    /// <summary>
    ///家园农场种田已完成
    /// </summary>
    [pbr::OriginalName("HomeFarmAlreadyComplete")] HomeFarmAlreadyComplete = 479,
    /// <summary>
    ///家园农场种田未完成
    /// </summary>
    [pbr::OriginalName("HomeFarmNotComplete")] HomeFarmNotComplete = 480,
    /// <summary>
    /// 好友农田外派位置已经被别人占领
    /// </summary>
    [pbr::OriginalName("HomeFarmPosAlreadyUsed")] HomeFarmPosAlreadyUsed = 481,
    /// <summary>
    /// 每个好友家只能派遣一个幻灵，请到其他好友农田中继续
    /// </summary>
    [pbr::OriginalName("HomeFarmOneFriendHeroOverMax")] HomeFarmOneFriendHeroOverMax = 482,
    /// <summary>
    ///家园农场槽位没有幻灵在种田
    /// </summary>
    [pbr::OriginalName("HomeFarmPosNoHero")] HomeFarmPosNoHero = 483,
    /// <summary>
    ///支付金额不足不能祈福
    /// </summary>
    [pbr::OriginalName("QiFuPayCountNotEnough")] QiFuPayCountNotEnough = 484,
    /// <summary>
    ///当日祈福次数用完
    /// </summary>
    [pbr::OriginalName("QiFuNoTimes")] QiFuNoTimes = 485,
    /// <summary>
    ///每日优惠奖励 今日已经领取过
    /// </summary>
    [pbr::OriginalName("DailyDealRewardAlreadyGet")] DailyDealRewardAlreadyGet = 486,
    /// <summary>
    ///每日特惠购买条件不符合
    /// </summary>
    [pbr::OriginalName("DailyDealPayCheckError")] DailyDealPayCheckError = 487,
    /// <summary>
    ///周礼包支付失败
    /// </summary>
    [pbr::OriginalName("WeekGiftPackagePayCheckError")] WeekGiftPackagePayCheckError = 488,
    /// <summary>
    ///每日礼包支付失败
    /// </summary>
    [pbr::OriginalName("DayGiftPackagePayCheckError")] DayGiftPackagePayCheckError = 489,
    /// <summary>
    ///每周购买上限
    /// </summary>
    [pbr::OriginalName("RechargeWeekLimit")] RechargeWeekLimit = 490,
    /// <summary>
    ///每日购买上限
    /// </summary>
    [pbr::OriginalName("RechargeDayLimit")] RechargeDayLimit = 491,
    /// <summary>
    ///该七日奖励已经领取过
    /// </summary>
    [pbr::OriginalName("SevenDayRewardAlreadyGet")] SevenDayRewardAlreadyGet = 492,
    /// <summary>
    ///未达成 不可领取
    /// </summary>
    [pbr::OriginalName("SevenDayRewardNotReached")] SevenDayRewardNotReached = 493,
    /// <summary>
    ///永久购买上限
    /// </summary>
    [pbr::OriginalName("RechargeLiveLimit")] RechargeLiveLimit = 494,
    /// <summary>
    /// 玩家未充值过
    /// </summary>
    [pbr::OriginalName("PlayerNoRechargeCount")] PlayerNoRechargeCount = 495,
    /// <summary>
    /// 首充奖励已领取
    /// </summary>
    [pbr::OriginalName("FirstRechargeAwardAlreadyGet")] FirstRechargeAwardAlreadyGet = 496,
    /// <summary>
    /// 领取天下觉灵奖励失败 没有足够的觉灵值
    /// </summary>
    [pbr::OriginalName("GetStarAwakenFailNotEnoughPoint")] GetStarAwakenFailNotEnoughPoint = 497,
    /// <summary>
    /// 购买觉灵奖励失败  需要物品不足
    /// </summary>
    [pbr::OriginalName("GetStarAwakenFailNotEnoughItem")] GetStarAwakenFailNotEnoughItem = 498,
    /// <summary>
    ///推送礼包支付失败
    /// </summary>
    [pbr::OriginalName("PickGiftRechargeError")] PickGiftRechargeError = 499,
    /// <summary>
    ///没有推送礼包
    /// </summary>
    [pbr::OriginalName("PickGiftPackageNotHave")] PickGiftPackageNotHave = 500,
    /// <summary>
    ///称号激活失败 没有获得
    /// </summary>
    [pbr::OriginalName("TitleActiveFailNotGet")] TitleActiveFailNotGet = 501,
    /// <summary>
    ///称号激活失败 没有在配置表中找到ID
    /// </summary>
    [pbr::OriginalName("TitleActiveFailNoID")] TitleActiveFailNoId = 502,
    /// <summary>
    ///称号装备失败 没有激活
    /// </summary>
    [pbr::OriginalName("TitleEquipFailNotActive")] TitleEquipFailNotActive = 503,
    /// <summary>
    ///营地不能升级
    /// </summary>
    [pbr::OriginalName("CampLevelCanotUp")] CampLevelCanotUp = 504,
    /// <summary>
    ///没有邀请次数
    /// </summary>
    [pbr::OriginalName("HomeFarmInviteNoCount")] HomeFarmInviteNoCount = 505,
    /// <summary>
    ///1000抽失败 条件不符合
    /// </summary>
    [pbr::OriginalName("ThousandDrawCardUnLock")] ThousandDrawCardUnLock = 506,
    /// <summary>
    ///1000抽失败 无效的INDEX
    /// </summary>
    [pbr::OriginalName("ThousandDrawCardNoIndex")] ThousandDrawCardNoIndex = 507,
    /// <summary>
    /// 未拥有此头像
    /// </summary>
    [pbr::OriginalName("NoHasThisHeadIcon")] NoHasThisHeadIcon = 508,
    /// <summary>
    ///未拥有此头像框
    /// </summary>
    [pbr::OriginalName("NoHasThisHeadIconFrame")] NoHasThisHeadIconFrame = 509,
    /// <summary>
    ///VIP等级未达到
    /// </summary>
    [pbr::OriginalName("VIPLevelNotReach")] ViplevelNotReach = 510,
    /// <summary>
    ///VIP等级奖励已经领取过
    /// </summary>
    [pbr::OriginalName("VIPAwardAlreadyGet")] VipawardAlreadyGet = 511,
    /// <summary>
    ///下载包奖励已经领取过
    /// </summary>
    [pbr::OriginalName("DownloadAwardAlreadyGet")] DownloadAwardAlreadyGet = 512,
    /// <summary>
    ///家园农场没有幻灵在种田
    /// </summary>
    [pbr::OriginalName("HomeFarmNoHeroWork")] HomeFarmNoHeroWork = 513,
    /// <summary>
    ///每日体力已经领取过
    /// </summary>
    [pbr::OriginalName("DailyPhysicalAlreadyGet")] DailyPhysicalAlreadyGet = 514,
    /// <summary>
    ///累计充值活动配置错误
    /// </summary>
    [pbr::OriginalName("RechargeTotalMomenyCfgError")] RechargeTotalMomenyCfgError = 515,
    /// <summary>
    ///累计充值奖励已领取
    /// </summary>
    [pbr::OriginalName("RechargeTotalMomenyAwardAlreadyGet")] RechargeTotalMomenyAwardAlreadyGet = 516,
    /// <summary>
    ///累计充值不足
    /// </summary>
    [pbr::OriginalName("RechargeTotalMomenyNoEnough")] RechargeTotalMomenyNoEnough = 517,
    /// <summary>
    /// 幻灵任务未完成
    /// </summary>
    [pbr::OriginalName("HeroQuestNotAllFinished")] HeroQuestNotAllFinished = 518,
    /// <summary>
    /// 幻灵任务奖励已领取
    /// </summary>
    [pbr::OriginalName("HeroQuestAwardAlreadyGet")] HeroQuestAwardAlreadyGet = 519,
    /// <summary>
    ///累计充值活动未开启
    /// </summary>
    [pbr::OriginalName("RechargeTotalMomenyNotExist")] RechargeTotalMomenyNotExist = 520,
    /// <summary>
    ///招财进宝达到最大次数
    /// </summary>
    [pbr::OriginalName("RollMoneyTreeMaxTimes")] RollMoneyTreeMaxTimes = 521,
    /// <summary>
    ///招财进宝次数奖励已经领取
    /// </summary>
    [pbr::OriginalName("RollMoneyTreeAwardAlready")] RollMoneyTreeAwardAlready = 522,
    /// <summary>
    ///破冰奖励已经领取
    /// </summary>
    [pbr::OriginalName("PoBingAwardAlreadyGet")] PoBingAwardAlreadyGet = 523,
    /// <summary>
    ///装备精炼失败 品质不符合
    /// </summary>
    [pbr::OriginalName("FXEquipRefineFailQuality")] FxequipRefineFailQuality = 524,
    /// <summary>
    ///匹配对手失败
    /// </summary>
    [pbr::OriginalName("FailedMatchOpponent")] FailedMatchOpponent = 525,
    /// <summary>
    /// 任务奖励已领取
    /// </summary>
    [pbr::OriginalName("QuestAwardAleadyGet")] QuestAwardAleadyGet = 526,
    /// <summary>
    /// 公会发展章节任务未完成
    /// </summary>
    [pbr::OriginalName("GuildDevelopChapterNotFinish")] GuildDevelopChapterNotFinish = 527,
    /// <summary>
    /// 公会发展章节奖励已领取
    /// </summary>
    [pbr::OriginalName("GuildDevelopChapterAwardAleadyGet")] GuildDevelopChapterAwardAleadyGet = 528,
    /// <summary>
    ///学社镇守膜拜没有次数
    /// </summary>
    [pbr::OriginalName("GuildGuardWorshipNoTimes")] GuildGuardWorshipNoTimes = 529,
    /// <summary>
    /// </summary>
    [pbr::OriginalName("ZINTERSTOREErr")] Zinterstoreerr = 530,
    /// <summary>
    ///协助副本选择的三消数据的玩家ID不对
    /// </summary>
    [pbr::OriginalName("AssistSanXiaoPlayerIDWrong")] AssistSanXiaoPlayerIdwrong = 531,
    /// <summary>
    ///先设置心愿再抽卡
    /// </summary>
    [pbr::OriginalName("MingGeDrawCardNoXinYuan")] MingGeDrawCardNoXinYuan = 532,
    /// <summary>
    ///匹配赛段位奖励领取失败
    /// </summary>
    [pbr::OriginalName("FailedToWorldMatchSeasonScoreAward")] FailedToWorldMatchSeasonScoreAward = 533,
    /// <summary>
    /// </summary>
    [pbr::OriginalName("YMPDrawCardNoXinYuan")] YmpdrawCardNoXinYuan = 534,
    /// <summary>
    /// 相片不存在
    /// </summary>
    [pbr::OriginalName("PhotoNotExist")] PhotoNotExist = 535,
    /// <summary>
    /// 相片数量超出上限
    /// </summary>
    [pbr::OriginalName("PhotoOverMaxCount")] PhotoOverMaxCount = 536,
    /// <summary>
    /// 没有相片点赞次数
    /// </summary>
    [pbr::OriginalName("PhotoLikeNoCount")] PhotoLikeNoCount = 537,
    /// <summary>
    /// 相片地址为空
    /// </summary>
    [pbr::OriginalName("PhotoURLEmpty")] PhotoUrlempty = 538,
    /// <summary>
    /// 相册位置已上传相片
    /// </summary>
    [pbr::OriginalName("PhotoPosAlreadyExist")] PhotoPosAlreadyExist = 539,
    /// <summary>
    ///请求幻灵战略失败 没有heroid
    /// </summary>
    [pbr::OriginalName("StrategyFailNoHeroID")] StrategyFailNoHeroId = 540,
    /// <summary>
    ///系统三消错误
    /// </summary>
    [pbr::OriginalName("SysSanXiaoErr")] SysSanXiaoErr = 541,
    /// <summary>
    /// 等级奖励已领取
    /// </summary>
    [pbr::OriginalName("LevelAwardAleadyGet")] LevelAwardAleadyGet = 542,
    /// <summary>
    /// 等级奖励不存在
    /// </summary>
    [pbr::OriginalName("LevelAwardNoExist")] LevelAwardNoExist = 543,
    /// <summary>
    /// 密卷合成消耗配置错误
    /// </summary>
    [pbr::OriginalName("ComposeItemCostCfgError")] ComposeItemCostCfgError = 544,
    /// <summary>
    /// 代金券不足
    /// </summary>
    [pbr::OriginalName("VoucherItemNoEnough")] VoucherItemNoEnough = 545,
    /// <summary>
    ///敏感字
    /// </summary>
    [pbr::OriginalName("SensitiveWords")] SensitiveWords = 1000,
  }

  #endregion

}

#endregion Designer generated code
