// <auto-generated>
//     Generated by the protocol buffer compiler.  DO NOT EDIT!
//     source: errorNo.proto
// </auto-generated>
#pragma warning disable 1591, 0612, 3021
#region Designer generated code

using pb = global::Google.Protobuf;
using pbc = global::Google.Protobuf.Collections;
using pbr = global::Google.Protobuf.Reflection;
using scg = global::System.Collections.Generic;
namespace ErrorNo {

  /// <summary>Holder for reflection information generated from errorNo.proto</summary>
  public static partial class ErrorNoReflection {

    #region Descriptor
    /// <summary>File descriptor for errorNo.proto</summary>
    public static pbr::FileDescriptor Descriptor {
      get { return descriptor; }
    }
    private static pbr::FileDescriptor descriptor;

    static ErrorNoReflection() {
      byte[] descriptorData = global::System.Convert.FromBase64String(
          string.Concat(
            "Cg1lcnJvck5vLnByb3RvEgdlcnJvck5vKtFrCgdFcnJvck5vEgsKB1N1Y2Nl",
            "c3MQABIPCgtGYWlsZWRMb2dpbhABEhAKDEluY29ycmVjdFBXRBACEhcKE0Zh",
            "aWxlZENyZWF0ZUFjY291bnQQAxIWChJGYWlsZWRDcmVhdGVQbGF5ZXIQBBIT",
            "Cg9Ob3RGb3VuZEFjY291bnQQBRIVChFDcmVhdGVQbGF5ZXJMaW1pdBAGEhYK",
            "EkZhaWxlZFVwZGF0ZURCRGF0YRAHEhIKDk5vdEZvdW5kUGxheWVyEAgSFAoQ",
            "RmFpbGVkSW5pdFBsYXllchAJEhQKEE5vdEZvdW5kTWF0Y2hTcnYQChIUChBO",
            "b3RGb3VuZFNjZW5lU3J2EAsSFgoSRmFpbGVkQ3JlYXRlQmF0dGxlEAwSDwoL",
            "Tm90SW5DZW50ZXIQDRISCg5OYW1lQWxyZWFkeVVzZRAOEhQKEEZhaWxlZENy",
            "ZWF0ZU5hbWUQDxIUChBOb3RGb3VuZExvZ2luS2V5EBASEQoNTmFtZUlzSW5W",
            "YWxpZBAREhUKEUZhaWxlZExvZ2luQmF0dGxlEBISFgoSTm90Rm91bmRCYXR0",
            "bGVSb29tEBMSEAoMQWxyZWFkeUZpZ2h0EBQSGgoWTm90Rm91bmRQbGF5ZXJJ",
            "bkJhdHRsZRAVEg8KC0ludmFsaWRJdGVtEBYSEgoOSGFzQWxyZWFkeUl0ZW0Q",
            "FxIRCg1JbnZhbGlkSGVyb0lkEBgSCwoHQmFnRnVsbBAZEhAKDE1hdGNoVGlt",
            "ZW91dBAaEhIKDkludmFsaWRTa2lsbElEEBsSEQoNTm90Rm91bmRJbkJhZxAd",
            "Eg0KCUZhaWxlZENNRBAeEhEKDU5vdEVub3VnaEl0ZW0QIxIRCg1GYWlsZWRV",
            "c2VJdGVtECQSEAoMQWxyZWFkeU1heEx2ECUSEgoORmFpbGVkRXF1aXBHZW0Q",
            "JhIUChBGYWlsZWRVbmVxdWlwR2VtECcSDwoLRmFpbGVkR2VtTFYQKBISCg5G",
            "YWlsZWRFcXVpcEFueRAqEhQKEEZhaWxlZFVuZXF1aXBBbnkQKxINCglOb3RP",
            "bmxpbmUQMRIXChNGYWlsZWRUb1BsYXllckxvZ2luEDISEAoMTm90Rm91bmRI",
            "ZXJvEDMSEAoMSGVyb1N0YXJGdWxsEDQSEQoNQmF0dGxlVGltZW91dBA1EhkK",
            "FUZhaWxlZENyZWF0ZVBWRUJhdHRsZRA2EhkKFVBsYXllckFscmVhZHlJbkJh",
            "dHRsZRA3EhcKE0ZhaWxlZFRvQ2hlY2tSZXBvcnQQOBIUChBBdGxhc0FjdGl2",
            "ZUxpbWl0EDkSFAoQRmFpbGVkVG9Mb2NrSXRlbRA6EgsKB0hhc0hlcm8QOxIZ",
            "ChVJbnN1ZmZpY2llbnRDb25kaXRpb24QPBISCg5Ob3RFbm91Z2hTdGFycxA9",
            "EhIKDk5vdEVub3VnaFBvd2VyED4SEgoOTm90RW5vdWdoTGV2ZWwQPxITCg9G",
            "YWlsZWRUb0RlbERhdGEQQBIXChNGYWlsZWRUb0dldE1haWxJdGVtEEESFAoQ",
            "RmFpbGVkRXF1aXBTdGFtcBBCEhYKEkZhaWxlZFVuZXF1aXBTdGFtcBBDEhUK",
            "EUZhaWxlZFN0YW1wVXBTdGFyEEQSEAoMU3RhbXBTdGFyTWF4EEUSEAoMTm90",
            "RW5vdWdoR2VtEEYSEgoOQWxyZWFkeUVxdWlwS1QQRxITCg9GYWlsZWRTZWxs",
            "VG9TeXMQSBIQCgxBbHJlYWR5QnV5S1QQSRIOCgpLVEJhZ0xpbWl0EEoSFQoR",
            "RmFpbGVkVG9FcXVpcEx2VXAQSxIQCgxOZWVkRW1iYXR0bGUQTBISCg5JbnZh",
            "bGlkTGV2ZWxJRBBNEhwKGFRvd2VyQWZ0ZXJMZXZlbE5vdEZpbmlzaBBOEhMK",
            "D1N1cnBhc3NQbGF5ZXJMdhBPEhoKFkZhaWxlZFRvUmVmcmVzaEtUUFNob3AQ",
            "UBIXChNOb3RGaW5pc2hUb3dlckxldmVsEFESFQoRRW1iYXR0bGVIZXJvTGlt",
            "aXQQUxITCg9Ob3RFbm91Z2hLVENvaW4QVBIWChJGYWlsZWRUb0dvZExldmVs",
            "VXAQVRIWChJPcHBvZW50UmFua0ludmFsaWQQVhIXChNOb3RGb3VuZEJhdHRs",
            "ZVZpZGVvEFcSEwoPSW52YWxpZEl0ZW1UeXBlEFgSFQoRR2V0Q2hhcHRlckJv",
            "eEZhaWwQWRIUChBGYWlsZWRSZWNvbm5uZWN0EFsSFQoRTm90Rm91bmRTdG9y",
            "ZUl0ZW0QXBIYChROb3RFbm91Z2hDb25zdW1lSXRlbRBdEh8KG0ZhaWxlZFRv",
            "R2V0QWNoaWV2ZW1lbnRBd2FyZBBeEhUKEUZhaWxlZENyZWF0ZUd1aWxkEF8S",
            "EQoNTGV2ZWxOb3RSZWFjaBBgEhIKDkd1aWxkTmFtZUVtcHR5EGESGAoUR3Vp",
            "bGROYW1lTGVuZ3RoRXJyb3IQYhIZChVHdWlsZE5hbWVBbHJlYWR5RXhpc3QQ",
            "YxIaChZHdWlsZE5vdGljZUxlbmd0aEVycm9yEGQSFgoSR3VpbGRJdGVtTm90",
            "RW5vdWdoEGUSGgoWUGxheWVyQWxyZWFkeUpvaW5HdWlsZBBmEhYKElBsYXll",
            "ck5vdEpvaW5HdWlsZBBnEhQKEEd1aWxkTm9BdXRob3JpdHkQaBIUChBHdWls",
            "ZE1vZGlmeUVycm9yEGkSFQoRR3VpbGRJY29uTm90RXhpc3QQahIVChFHdWls",
            "ZEljb25Ob0NoYW5nZRBrEhcKE0d1aWxkTm90aWNlTm9DaGFuZ2UQbBIUChBH",
            "dWlsZFBsYXllck5vdEluEG0SFAoQR3VpbGRUYXJnZXRFcnJvchBuEhcKE0d1",
            "aWxkQWxyZWFkeURpc2JhbmQQbxITCg9HdWlsZERpc2JhbmRpbmcQcBIWChJH",
            "dWlsZEFscmVhZHlOb3JtYWwQcRIRCg1HdWlsZE5vdEV4aXN0EHISGQoVR3Vp",
            "bGRBbHJlYWR5QXBwbHlUaGlzEHMSFgoSR3VpbGRPdmVyTWF4TWVtYmVyEHQS",
            "FgoSR3VpbGRBbHJlYWR5SW5UaGlzEHUSEwoPR3VpbGRDYW5vdExlYXZlEHYS",
            "FgoSR3VpbGRDYW5vdEtpY2tTZWxmEHcSFAoQR3VpbGRBcHBvaW50U2VsZhB4",
            "EhQKEEd1aWxkT3BlcmF0ZVNlbGYQeRIUChBHdWlsZFBhcmFtc0Vycm9yEHoS",
            "GgoWR3VpbGRQbGF5ZXJMZXZlbFRvb0xvdxB7EhcKE0d1aWxkRmlnaHRpbmdU",
            "b29Mb3cQfBISCg5HdWlsZE1haWxFbXB0eRB9EhUKEUd1aWxkTWFpbFRvb0xh",
            "cmdlEH4SEAoMR3VpbGRKb2JGdWxsEH8SFQoQR3VpbGRKb2JOb3RFeGlzdBCA",
            "ARIXChJHdWlsZEFscmVhZHlJbnZpdGUQgQESGAoTR3VpbGRJbnZpdGVOb3RF",
            "eGlzdBCCARIaChVHdWlsZEJ1aWxkaW5nTm90RXhpc3QQgwESHAoXR3VpbGRC",
            "dWlsZGluZ0FscmVhZHlNYXgQhAESFwoSR3VpbGRMZXZlbE5vRW5vdWdoEIUB",
            "EhcKEkd1aWxkTW9uZXlOb0Vub3VnaBCGARIZChRHdWlsZE1haWxCcm9hZGNh",
            "c3RDRBCHARISCg1HdWlsZFJlam9pbkNEEIgBEhoKFU5vdEVub3VnaENoYWxs",
            "ZW5nZU51bRCJARIaChVGYWlsZWRUb0dldFF1ZXN0QXdhcmQQigESIAobRmFp",
            "bGVkVG9HZXRBY3RpdmVWYWx1ZUF3YXJkEIsBEhgKE0ludmFsaWRMaWVaaHVh",
            "blBhcm0QjAESFAoPQWxyZWFkeUJ1eUxpbWl0EI0BEhIKDVJlZGlzS2V5RXJy",
            "b3IQjgESEwoOUmVkaXNSYW5rRXJyb3IQjwESEwoOUmVkaXNEYXRhRW1wdHkQ",
            "kAESGQoURXhwZWRpdGlvbkxldmVsRXJyb3IQkQESHwoaRXhwZWRpdGlvbkNo",
            "YWxsZW5nZU5vQ291bnQQkgESFwoSRXhwZWRpdGlvblJlc2V0aW5nEJMBEhoK",
            "FUV4cGVkaXRpb25DaGFsbGVuZ2luZxCUARISCg1Ob3RTeXN0ZW1PcGVuEJUB",
            "EhoKFUZhaWxlZFRvVHJ1bmNhdGVUYWJsZRCWARIXChJGYWlsZWRUb0ZpbmRG",
            "cmllbmQQlwESGgoVRmFpbGVkVG9aUmFuZ2VCeVNjb3JlEJgBEhoKFUZhaWxl",
            "ZFRvU3RvcmVBbnlUYWJsZRCZARIUCg9GYWlsZWRUb1F1ZXJ5RGIQmgESGQoU",
            "RmFpbGVkVG9EZWNvZGVQYkRhdGEQmwESFAoPUXVlcnlEYl9Ob3REYXRhEJwB",
            "EhkKFEhvbWVPcm5hbWVudE5vdEV4aXN0EJ0BEhYKEUhvbWVPcm5hbWVudEVt",
            "cHR5EJ4BEhkKFEhvbWVCdWlsZGluZ05vdEV4aXN0EJ8BEh0KGEhvbWVCdWls",
            "ZGluZ0FscmVhZHlFeGlzdBCgARIbChZIb21lQnVpbGRpbmdBbHJlYWR5TWF4",
            "EKEBEhUKEEhvbWVIZXJvTm90RXhpc3QQogESGgoVSG9tZUhlcm9TdG9yeUNm",
            "Z0Vycm9yEKMBEhoKFUhvbWVIZXJvQWxyZWF5SW5TY2VuZRCkARIgChtIb21l",
            "SGVyb0ludGVyYWN0TnVtTm9Fbm91Z2gQpQESFwoST3RoZXJQbGF0Zm9ybUxv",
            "Z2luEKYBEhkKFEhvbWVIZXJvUGxhY2VPdmVyTWF4EKcBEhcKEkhvbWVSZWdp",
            "b25Ob3RFeGlzdBCoARIYChNIb21lUmVnaW9uTm90VW5sb2NrEKkBEhYKEVNh",
            "bnhpYW9DZmdJREVycm9yEKoBEhEKDFRyaWFsRGF0YU5pbBCsARIYChNUcmlh",
            "bEZvcm1hdGlvbkVycm9yEK0BEhcKElRyaWFsTGV2ZWxDZmdFcnJvchCuARIa",
            "ChVUcmlhbENsaWVudExldmVsRXJyb3IQrwESGQoUVHJpYWxCYXR0bGVOb3RD",
            "cmVhdGUQsAESHgoZUXVlc3RDb25zdW1lSXRlbU5vdEVub3VnaBCxARISCg1R",
            "dWVzdE5vdEV4aXN0ELIBEg8KCkFjY291bnROZXcQswESFAoPRGFpWGlhb1Jl",
            "cUxpbWl0ELQBEhgKE1NhblhpYW9DaGVja1RpbWVvdXQQtQESFgoRUGxheWVy",
            "T25saW5lTGltaXQQtgESEwoOU2VydmVyTWFpbnRhaW4QtwESGgoVUGxheWVy",
            "TmFtZUxlbmd0aEVycm9yELgBEhoKFUV4cGVkaXRpb25DYW5ub3RTd2VlcBC5",
            "ARIeChlFeHBlZGl0aW9uU3dlZXBBd2FyZEVycm9yELoBEhYKEUhlcm9TdGFy",
            "Tm90RW5vdWdoELsBEhgKE0RhaVhpYW9Mb3NlRWZmaWNhY3kQvQESGAoTS1RT",
            "a2lsbEFscmVhZHlFcXVpcBDAARIZChRLVFNraWxsU2xvdE5vdEVub3VnaBDB",
            "ARIUCg9LVFNraWxsTm90Rm91bmQQwgESFwoSRmFuUm9uZ0R1Tm90RW5vdWdo",
            "EMMBEhYKEUJhdHRsZVZlck5vdE1hdGNoEMQBEhcKElNhblhpYW9WZXJOb3RN",
            "YXRjaBDFARIUCg9LVFNsb3ROb3RFbm91Z2gQxgESGAoTUGxheWVyU2tpbGxO",
            "b3RGb3VuZBDHARIfChpQbGF5ZXJTa2lsbEFscmVhZHlBY3RpdmF0ZRDIARIb",
            "ChZBY3RpdmF0ZVBsYXllckF0dHJGYWlsEMkBEhkKFEludmFsaWRNYWluUGxh",
            "eWVyQ2ZnEMoBEhkKFEZBSUxFRF9SRURJU19ERUxfS0VZEMsBEhQKD0FyZWFO",
            "ZWVkU2FuWGlhbxDMARIfChpGYWlsZWRUb0dldERhaWx5VG93ZXJBd2FyZBDN",
            "ARIfChpTdG9yZVJlZnJlc2hDb3VudE5vdEVub3VnaBDOARISCg1DaGF0Rm9y",
            "YmlkZGVuEM8BEhcKElBsYXllckFjY291bnRCbG9jaxDQARIYChNQbGF5ZXJT",
            "a2lsbExWVVBGYWlsENEBEhgKE0d1aWxkRG9uYXRlQ2ZnRXJyb3IQ0gESHQoY",
            "R3VpbGREb25hdGVJdGVtTm90RW5vdWdoENMBEhsKFkd1aWxkSW50cm9kdWNl",
            "Tm9DaGFuZ2UQ1AESHgoZR3VpbGRJbnRyb2R1Y2VMZW5ndGhFcnJvchDVARIc",
            "ChdHdWlsZEF1dGhvcml0eURhdGFFcnJvchDWARIbChZHdWlsZEJ1aWxkaW5n",
            "SW5VcGdyYWRlENcBEhcKEkd1aWxkQXVjdGlvbk5vSXRlbRDYARIYChNHdWls",
            "ZEF1Y3Rpb25Ob0RvaW5nENkBEh0KGEd1aWxkQXVjdGlvbkl0ZW1Ob3RFeGlz",
            "dBDaARIeChlHdWlsZEF1Y3Rpb25JdGVtQWxyZWF5QmlkENsBEh4KGUd1aWxk",
            "QXVjdGlvbkl0ZW1Ob3RFbm91Z2gQ3AESJAofR3VpbGRBdWN0aW9uSXRlbUFs",
            "cmVhZHlGaW5pc2hlZBDdARIfChpHdWlsZEF1Y3Rpb25JdGVtQWxyZWFkeUJ1",
            "eRDeARIZChRHdWlsZFNraWxsQWxyZWFkeU1heBDfARIVChBHdWlsZEJvc3NO",
            "b0NvdW50EOABEhsKFkd1aWxkQm9zc0xldmVsQ2ZnRXJyb3IQ4QESFAoPR3Vp",
            "bGRCb3NzSXNEZWFkEOIBEhcKEkd1aWxkUXVlc3ROb3RFeGlzdBDjARIWChFH",
            "dWlsZFF1ZXN0Tm90T3BlbhDkARIWChFHdWlsZFF1ZXN0T3Zlck1heBDlARIS",
            "Cg1HdWlkYW5jZUxpbWl0EOoBEhcKElN0b3J5UHJvZ3Jlc3NMaW1pdBDrARIV",
            "ChBBbHJlYWR5RXF1aXBIZXJvEOwBEhYKEUdvbmdNaW5nSGVyb0xpbWl0EO0B",
            "EhYKEUZhaWxlZFRvRlhMZXZlbFVwEO4BEhYKEUZhaWxlZEdldExldmVsQm94",
            "EO8BEhcKEk5vdEZvdW5kQ2hhbGxlbmdlchDwARIaChVGYWN0aW9uVHlwZUFs",
            "cmVhZHlTZXQQ8QESFQoQRmFjdGlvblR5cGVFcnJvchDyARITCg5DaGF0UmVx",
            "VGltZU91dBDzARIXChJDaGF0RnJlcXVlbmN5TGltaXQQ9AESGAoTUmVkaXNM",
            "aXN0U3RvcmVFcnJvchD1ARITCg5GYWlsZWRUb0xSQU5HRRD2ARIeChlGYWls",
            "ZWRUb0dldENoYXRNc2dCeVJvb21EEPcBEhMKDkZhaWxlZFRvU2lnbkluEPgB",
            "EhAKC1NpZ25JblJlc2V0EPkBEhkKFEFjY2VwdEFzc2lzdEZhaWxMYXRlEPoB",
            "Eh4KGUFjY2VwdEFzc2lzdEZhaWxQYXNzTGV2ZWwQ+wESHQoYQXNzaXN0RW50",
            "ZXJGYWlsQWxyZWFkeUluEPwBEh8KGkFzc2lzdFNhdmVFbWJhdHRsZUluZm9G",
            "YWlsEP0BEhIKDUFzc2lzdE5vVGltZXMQ/gESGAoTSW52aXRlQXNzaXN0UmVx",
            "RmFpbBD/ARIaChVBY2NlcHRBc3Npc3RGYWlsTGV2ZWwQgAISHQoYQWNjZXB0",
            "QXNzaXN0RmFpbE5vUGxheWVyEIECEhsKFkFzc2lzdEVudGVyRmFpbE5vdE9w",
            "ZW4QggISHQoYQXNzaXN0SGVscFBsYXllck5vdFJlYWR5EIMCEhgKE0Fzc2lz",
            "dFBsYXllckluVmFsaWQQhAISGgoVQXNzaXN0U3dlZXBXcm9uZ0xldmVsEIUC",
            "EhkKFEd1aWxkUGxheWVyTm9GYWN0aW9uEIYCEhkKFEd1aWxkRmFjdGlvbk5v",
            "dE1hdGNoEIcCEh8KGkd1aWxkQ2Fub3RBcHBseVRoaXNGYWN0aW9uEIgCEhsK",
            "Fkd1aWxkU2VhcmNoTmFtZUludmFsaWQQiQISFgoRTG9naW5Ub2tlbkludmFp",
            "bGQQigISFwoSRmFpbGVkWGlYdW5EaWFuWmFuEIsCEhYKEUZhaWxlZFN0YW5n",
            "ZXJDaGF0EIwCEhYKEUZhaWxlZEJsYWNrRnJpZW5kEI0CEhwKF1JlYWxVc2Vy",
            "Tm90VmVyaWZpY2F0aW9uEI4CEhgKE05vbmFnZUNhbm90UGxheVRpbWUQjwIS",
            "FwoSTm9uYWdlT3ZlclBsYXlUaW1lEJACEhIKDVBheVJlcVRpbWVPdXQQkQIS",
            "DwoKUGF5UmVxRmFpbBCSAhIVChBGYWlsZWRUb3dlclBvd2VyEJMCEhUKEEhl",
            "YXJ0YmVhdFRpbWVvdXQQlAISGgoVUmVjaGFyZ2VTdG9yZUNmZ0Vycm9yEJUC",
            "EhUKEEJ1eUNob3VrYU5vVGltZXMQlgISHAoXUmVjaGFyZ2VOb25hZ2VPbmNl",
            "TGltaXQQlwISHQoYUmVjaGFyZ2VOb25hZ2VNb250aExpbWl0EJgCEhoKFUZh",
            "aWxlZEV4cGVkaXRpb25Qb3dlchCZAhIZChROb3RFbm91Z2hDaG91S2FDb3Vu",
            "dBCaAhIYChNOb25hZ2VMb2dpbkFnZUxpbWl0EJsCEg4KCUdNS2lja091dBCc",
            "AhIYChNOZWVkTGllWmh1YW5TYW5YaWFvEJ0CEhYKEVhpbmdKdW5SZXdhcmRG",
            "YWlsEJ4CEhYKEVNlcnZlckRhdGFSZXFGYWlsEJ8CEhsKFlJpbmdBY3Rpdml0",
            "eUFscmVhZHlFbmQQoAISGQoUUmluZ0FjdGl2aXR5Tm90U3RhcnQQoQISFwoS",
            "QWN0aXZpdHlTdGF0ZUVycm9yEKICEhQKD1JpbmdSZXBlYXRBcHBseRCjAhIY",
            "ChNDaGFwdGVyTGV2ZWxOb3RPcGVuEKQCEhwKF1NhblhpYW9CYW9EaWFuRGF0",
            "YUVycm9yEKUCEiAKG1NhblhpYW9CYW9EaWFuUmFua0RhdGFFcnJvchCmAhIe",
            "ChlSaW5nTm91RW5vdWdoQ2hhbGxlbmdlTnVtEKcCEhEKDFJpbmdOb3RBcHBs",
            "eRCoAhIYChNHdWlsZFF1ZXN0Tm90RW5vdWdoEKkCEhMKDlJpbmdBcHBseUxp",
            "bWl0EKoCEhIKDVJlZGlzR2V0RXJyb3IQqwISEgoNUmVkaXNTZXRFcnJvchCs",
            "AhIVChBSZWRpc0tleU5vdEV4aXN0EK0CEhUKEEZCTWFpbEFscmVhZHlHZXQQ",
            "rgISFQoQRmFpbGVkVG9EQkluc2VydBCvAhIVChBGYWlsZWRUb0RCVXBkYXRl",
            "ELACEh8KGkZhaWxlZFRvQ3JlYXRlUGxheWVyTmFtZUlEELECEh0KGEZhaWxl",
            "ZFRvR2V0U2V2ZW5EYXlBd2FyZBCyAhIUCg9GYWlsR2V0Q29kZVVzZWQQswIS",
            "FAoPRmFpbEdldENvZGVOb25lELQCEhkKFFBsYXllckJvb2tOb3RBY2N0aXZl",
            "ELUCEhIKDUJvb2tJZE5vdEZpbmQQtgISGgoVRXF1aXBCb29rRmFpbE5vdE1h",
            "dGNoELcCEhwKF0VxdWlwQm9va2xsZWdhbFBvc2l0aW9uELgCEhcKElBsYXll",
            "ckJvb2tMdlVwRmFpbBC5AhIaChVSZWZyZXNoQm9va05vdEFjY3RpdmUQugIS",
            "GgoVUGxheWVyU2tpbGxOb3RBY2N0aXZlELsCEhIKDUNhbXBOb3RVbmxvY2sQ",
            "vAISGQoUQ2FtcFBvc0FscmVhZHlVbmxvY2sQvQISFQoQQ2FtcFBvc05vdFVu",
            "bG9jaxC+AhIXChJDYW1wUG9zVW5sb2NrRXJyb3IQvwISEgoNQ2FtcFBvc05v",
            "SGVybxDAAhIaChVDYW1wUG9zQWxyZWFkeUhhc0hlcm8QwQISGwoWQ2FtcFBv",
            "c0Nhbm5vdFBsYWNlSGVybxDCAhIZChRDYW1wSGVyb0FscmVhZHlQbGFjZRDD",
            "AhISCg1IZXJvU3RhckVtcHR5EMQCEh8KGlJlcmVzaFNraWxsQm9va0ZhaWxO",
            "b0VudHJ5EMUCEhcKEkhvbWVTdG9yZUl0ZW1FbXB0eRDGAhIZChRIb21lQnVp",
            "bGRpbmdDZmdFcnJvchDHAhIdChhIb21lQ291cnR5YXJkVmlzaXRvckZ1bGwQ",
            "yAISIwoeSG9tZUNvdXJ0eWFyZEJ5VmlzaXRDb3VudEVtcHR5EMkCEiEKHEhv",
            "bWVDb3VydHlhcmRWaXNpdENvdW50RW1wdHkQygISGgoVSG9tZUhvdGVsUm9v",
            "bU5vdEV4aXN0EMsCEh4KGUhvbWVIb3RlbFJvb21IZXJvTm90RXhpc3QQzAIS",
            "GgoVSG9tZUhvdGVsUm9vbUhlcm9GdWxsEM0CEh8KGkhvbWVIb3RlbEhlcm9D",
            "YW5vdEpvaW5UaGlzEM4CEh8KGkhvbWVBZHZlbnR1cmVDb3VudE5vRW5vdWdo",
            "EM8CEh4KGUhvbWVBZHZlbnR1cmVOb2RlQ2ZnRXJyb3IQ0AISGgoVSG9tZUFk",
            "dmVudHVyZU5vdFN0YXJ0ENECEh0KGEhvbWVBZHZlbnR1cmVOb3RGaW5pc2hl",
            "ZBDSAhIfChpIb21lQWR2ZW50dXJlTm90QmF0dGxlTm9kZRDTAhIcChdIb21l",
            "RmFybUhlcm9BbHJlYWR5QnVzeRDUAhIeChlIb21lRmFybUZyaWVuZEhlcm9P",
            "dmVyTWF4ENUCEhgKE0hvbWVGYXJtV29ya05vQ291bnQQ1gISHgoZSG9tZUZh",
            "cm1GcmllbmRXb3JrTm9Db3VudBDXAhIdChhIb21lRmFybUhlcm9JbkZyaWVu",
            "ZEhvbWUQ2AISGAoTSG9tZUZhcm1IZXJvT3Zlck1heBDZAhIfChpIb21lSG90",
            "ZWxIZXJvQWxyZWFkeUluUm9vbRDaAhIWChFIb21lSG90ZWxIZXJvRnVsbBDb",
            "AhIbChZIb21lSG90ZWxRdWVzdEZpbmlzaGVkENwCEhQKD1JlZGlzRGlzY29u",
            "bmVjdBDdAhIbChZOb3RFbm91Z2hEcmF3Q2FyZENvdW50EN4CEhgKE0hlcm9B",
            "d2FrZVdyb25nTGV2ZWwQ6AISGAoTSW52YWlsZEFiaWxpdHlDZmdJRBDpAhIe",
            "ChlLVFNraWxsRXF1aXBTbG90Tm90RW5vdWdoEOoCEh4KGUhlcm9Bd2FrZVdy",
            "b25nSGVyb1F1YWxpdHkQ6wISHQoYSGVyb1BvdGVudGlhbEF0dHJXcm9uZ0x2",
            "EOwCEhgKE0Jsb29kUG93ZXJOb3RFbm91Z2gQ7QISEQoMSHR0cFJlcUVycm9y",
            "EO4CEhMKDkh0dHBSZXFUaW1lb3V0EO8CEhcKEkh0dHBSZXNEZWNvZGVFcnJv",
            "chDwAhIXChJSZWRlZW1Db2RlUmVxRXJyb3IQ8QISHQoYUmVkZWVtQ29kZUFs",
            "cmVhZHlHZXRJdGVtEPICEhQKD1JlZGVlbUNvZGVEb2luZxDzAhIRCgxEQlJl",
            "cVRpbWVvdXQQ9AISFQoQRmFpbGVkVG9FbWJhdHRsZRD1AhIWChFGYWlsZWRU",
            "b1JpbmdBcHBseRD2AhIYChNHdWlsZEJvc3NBd2FyZFRha2VkEPcCEh0KGEd1",
            "aWxkQm9zc0J1eUNvdW50T3Zlck1heBD4AhIZChRHdWlsZEluZm9LZXlOb3RF",
            "eGlzdBD5AhIbChZSZW1vdmVUYXJnZXRHdWFyZE5vdElzEPoCEhsKFkludml0",
            "ZUd1YXJkUHJvdGVjdFRpbWUQ+wISGQoUSW52aXRlR3VhcmRBbHJlYWR5SXMQ",
            "/AISIQocSW52aXRlR3VhcmRSZW1vdmVQcm90ZWN0VGltZRD9AhIWChFJbnZp",
            "dGVHdWFyZEZyaWVuZBD+AhIYChNJbnZpdGVHdWFyZFByZXN0aWdlEP8CEhIK",
            "DUd1YXJkTm90Rm91bmQQgAMSEwoOVG1wdEd1YXJkT3duZXIQgQMSFAoPSW52",
            "aXRlR3VhcmRGYWlsEIIDEhcKEkludml0ZUd1YXJkTm9UaW1lcxCDAxIWChFU",
            "YXJnZXRHdWFyZE1heE51bRCEAxIZChRUYXJnZXRHdWFyZEFscmVhZHlJcxCF",
            "AxIWChFJbnZpdGVHdWFyZE1heE51bRCGAxIaChVTREtRdWVyeVJlYWxOYW1l",
            "RXJyb3IQhwMSHQoYU2FuWGlhb0NvbGxldFJld2FyZEVycm9yEIgDEh0KGFNh",
            "blhpYW9Db2xsZXRSZXdhcmRFbXB0eRCJAxIeChlHdWlsZFJlY3J1aXRJdGVt",
            "Tm90RW5vdWdoEIoDEhkKFEd1aWxkUmVjcnVpdE1zZ0VtcHR5EIsDEh8KGkd1",
            "aWxkUmVjcnVpdE1zZ0xlbmd0aEVycm9yEIwDEhQKD05vdEVtYmF0dGxlSGVy",
            "bxCNAxIfChpIb21lUGFydHlEYXlIb2xkQ291bnRFbXB0eRCOAxIgChtIb21l",
            "UGFydHlXZWVrSG9sZENvdW50RW1wdHkQjwMSIAobSG9tZVBhcnR5U3Vic2Ny",
            "aWJlVGltZUVycm9yEJADEhkKFEhvbWVQYXJ0eU5vdE9wZW5UaW1lEJEDEhcK",
            "EkhvbWVQYXJ0eUlzRXhwaXJlZBCSAxIWChFIb21lUGFydHlOb3RFeGlzdBCT",
            "AxIdChhIb21lUGFydHlOb09wZW5BdXRob3JpdHkQlAMSGgoVSG9tZVBhcnR5",
            "R2lmdE5vdEV4aXN0EJUDEhwKF0hvbWVQYXJ0eUpvaW5Db3VudEVtcHR5EJYD",
            "EhsKFkhvbWVQYXJ0eVBsYXllck5vdEpvaW4QlwMSHwoaSG9tZVBhcnR5UGxh",
            "eWVyQWxyZWFkeUdpZnQQmAMSGQoUSG9tZVBhcnR5QWxyZWFkeU9wZW4QmQMS",
            "GAoTSG9tZVBhcnR5QWxyZWFkeUdldBCaAxIgChtIb21lUGFydHlDYW5ub3RT",
            "Y2F0dGVyU3VnYXIQmwMSHQoYSG9tZVBhcnR5UGxheWVyQ291bnRGdWxsEJwD",
            "EhgKE0hvbWVQYXJ0eVBsYXllckJ1c3kQnQMSIAobSG9tZVBhcnR5RGFuY2VB",
            "bHJlYWR5SW52aXRlEJ4DEiAKG0hvbWVQYXJ0eURhbmNlSW52aXRlRXhwaXJl",
            "ZBCfAxIeChlIb21lUGFydHlGaXJld29ya05vdFBsYWNlEKADEhwKF0hvbWVQ",
            "YXJ0eUFscmVhZHlFYXREaXNoEKEDEhkKFE5lZWRHdWFyZEJvc3NTYW5YaWFv",
            "EKIDEhoKFUludml0ZUd1YXJkSW5Cb3NzVGltZRCjAxImCiFHdWlsZE1zZ0lu",
            "dmVzdGlnYXRlQ291bnROb3RFbm91Z2gQpAMSGwoWR3VhcmRCb3NzSW5zcGly",
            "ZU1heE51bRClAxIkCh9HZXRCb3NzRGFtYWdlUmFua0xpc3RXcm9uZ1N0YXRl",
            "EKYDEhwKF0d1aWxkQnVpbGRFdmVudE5vdEV4aXN0EKcDEiAKG0d1aWxkQnVp",
            "bGRFdmVudEFyZWFkeUZpbmlzaBCoAxIWChFHZXRCb3NzQm94Tm90RXhpdBCp",
            "AxIVChBIb21lUGFydHlOb3RPcGVuEKoDEiAKG0d1aWxkQXVjdGlvbkJvbnVz",
            "QWxyZWFkeUdldBCrAxIYChNHdWlsZE5vQXVjdGlvbkJvbnVzEKwDEh4KGUhv",
            "bWVQYXJ0eUZpcmV3b3JrTm90RXhpc3QQrQMSIgodRmFpbGVkVG9TZXZlbkZv",
            "dXJ0ZWVuU2FsZUl0ZW0QrgMSJAofRmFpbGVkVG9TZXZlbkZvdXJ0ZWVuQWN0",
            "aXZlSXRlbRCvAxIYChNGYWlsZWRHZXRDb2RlUmV3YXJkELADEhUKEFJlZGlz",
            "TWVtYmVyRXhpc3QQsQMSEwoOUmVkaXNTQWRkRXJyb3IQsgMSFgoRSW5HdWls",
            "ZFdyb25nU3RhdGUQswMSFAoPR3VhcmRJbkJvc3NUaW1lELQDEhkKFEhvbWVQ",
            "YXJ0eU5vV2luZUNvdW50ELUDEiIKHUhvbWVQYXJ0eUludml0ZVBsYXllck5v",
            "dEV4aXN0ELYDEhgKE0hvbWVQYXJ0eVJvYmJlckRpZWQQtwMSIgodSG9tZVBh",
            "cnR5R2FtZUVhdEFscmVhZHlGaW5pc2gQuAMSIQocSG9tZVBhcnR5RmluaXNo",
            "QXdhcmRDZmdFcnJvchC5AxIXChJIb21lUGFydHlHYW1lRXJyb3IQugMSJwoi",
            "SG9tZVBhcnR5QXRtb3NwaGVyZUFjaGlldmVDZmdFcnJvchC7AxIgChtIb21l",
            "UGFydHlBdG1vc3BoZXJlTm9Fbm91Z2gQvAMSLgopSG9tZVBhcnR5QXRtb3Nw",
            "aGVyZUFjaGlldmVBd2FyZEFscmVhZHlHZXQQvQMSHQoYRmFpbGVkVG9TZXRF",
            "bWJhdHRsZUluZGV4EL4DEhcKEk5vdEZvdW5kUGxheWVySW5mbxC/AxIaChVG",
            "cmllbmRKaUJhbkx2Tm9Fbm91Z2gQwAMSJgohSG9tZVBhcnR5QXRtb3NwaGVy",
            "QXdhcmRBbHJlYWR5R2V0EMEDEhkKFEhvbWVQYXJ0eUFscmVhZHlKb2luEMID",
            "EhsKFkhvbWVQYXJ0eUFscmVhZHlGaW5pc2gQwwMSGgoVR3VpbGRCb3NzR3Jv",
            "dXBOb3RQYXNzEMQDEhsKFkd1aWxkQm9zc0dyb3VwQ2ZnRXJyb3IQxQMSFQoQ",
            "RGFpWGlhb05vdEZpbmlzaBDGAxIWChFEYWlYaWFvTm90SW52YWxpZBDHAxIa",
            "ChVIb21lUGFydHlHdWVzdE92ZXJNYXgQyAMSHgoZSG9tZVBhcnR5TWFpbkd1",
            "ZXN0T3Zlck1heBDJAxIZChRaaGFuZ0xpbmdDZmdOb3RFeGlzdBDKAxIXChJa",
            "aGFuZ0xpbmdOb3RVbmxvY2sQywMSGAoTWmhhbmdMaW5nQWxyZWFkeUdldBDM",
            "AxIgChtBY2NvdW50QmluZFJld2FyZEdldEFscmVhZHkQzQMSHQoYQWNjb3Vu",
            "dEJpbmRSZXdhcmRHZXRGYWlsEM4DEh4KGVNoYW5nR3VZaUppSW52YWxpZExl",
            "dmVsSUQQzwMSHQoYU2hhbmdHdVNob3J0Y3V0Tm90RW5vdWdoENADEhcKElJl",
            "Y2hhcmdlT3JkZXJFcnJvchDRAxIWChFCYXR0bGVWaWRlb0V4cGlyZRDSAxIV",
            "ChBRdWVzdE5vdEZpbmlzaGVkENMDEh8KGlpoYW5nTGluZ1BheUNvdW50Tm90",
            "RW5vdWdoENQDEhsKFlpoYW5nTGluZ1BheUNoZWNrRXJyb3IQ1QMSFAoPWmhh",
            "bmdMaW5nTm90UGF5ENYDEhYKEUFscmVhZHlFcXVpcFN0YW1wENcDEg4KCVN0",
            "YW1wTG9jaxDYAxITCg5ZdWVLYU91dE9mVGltZRDZAxIaChVZdWVLYVJld2Fy",
            "ZEFscmVhZHlHZXQQ2gMSFwoSWXVlS2FQYXlDaGVja0Vycm9yENsDEhAKC1l1",
            "ZUthTm90QnV5ENwDEhYKEUNsaW1iVG93ZXJOb1RpbWVzEN0DEhUKEEhvbWVG",
            "YXJtUG9zRXJyb3IQ3gMSHAoXSG9tZUZhcm1BbHJlYWR5Q29tcGxldGUQ3wMS",
            "GAoTSG9tZUZhcm1Ob3RDb21wbGV0ZRDgAxIbChZIb21lRmFybVBvc0FscmVh",
            "ZHlVc2VkEOEDEiEKHEhvbWVGYXJtT25lRnJpZW5kSGVyb092ZXJNYXgQ4gMS",
            "FgoRSG9tZUZhcm1Qb3NOb0hlcm8Q4wMSGgoVUWlGdVBheUNvdW50Tm90RW5v",
            "dWdoEOQDEhAKC1FpRnVOb1RpbWVzEOUDEh4KGURhaWx5RGVhbFJld2FyZEFs",
            "cmVhZHlHZXQQ5gMSGwoWRGFpbHlEZWFsUGF5Q2hlY2tFcnJvchDnAxIhChxX",
            "ZWVrR2lmdFBhY2thZ2VQYXlDaGVja0Vycm9yEOgDEiAKG0RheUdpZnRQYWNr",
            "YWdlUGF5Q2hlY2tFcnJvchDpAxIWChFSZWNoYXJnZVdlZWtMaW1pdBDqAxIV",
            "ChBSZWNoYXJnZURheUxpbWl0EOsDEh0KGFNldmVuRGF5UmV3YXJkQWxyZWFk",
            "eUdldBDsAxIdChhTZXZlbkRheVJld2FyZE5vdFJlYWNoZWQQ7QMSFgoRUmVj",
            "aGFyZ2VMaXZlTGltaXQQ7gMSGgoVUGxheWVyTm9SZWNoYXJnZUNvdW50EO8D",
            "EiEKHEZpcnN0UmVjaGFyZ2VBd2FyZEFscmVhZHlHZXQQ8AMSJAofR2V0U3Rh",
            "ckF3YWtlbkZhaWxOb3RFbm91Z2hQb2ludBDxAxIjCh5HZXRTdGFyQXdha2Vu",
            "RmFpbE5vdEVub3VnaEl0ZW0Q8gMSGgoVUGlja0dpZnRSZWNoYXJnZUVycm9y",
            "EPMDEhsKFlBpY2tHaWZ0UGFja2FnZU5vdEhhdmUQ9AMSGgoVVGl0bGVBY3Rp",
            "dmVGYWlsTm90R2V0EPUDEhgKE1RpdGxlQWN0aXZlRmFpbE5vSUQQ9gMSHAoX",
            "VGl0bGVFcXVpcEZhaWxOb3RBY3RpdmUQ9wMSFQoQQ2FtcExldmVsQ2Fub3RV",
            "cBD4AxIaChVIb21lRmFybUludml0ZU5vQ291bnQQ+QMSGwoWVGhvdXNhbmRE",
            "cmF3Q2FyZFVuTG9jaxD6AxIcChdUaG91c2FuZERyYXdDYXJkTm9JbmRleBD7",
            "AxIWChFOb0hhc1RoaXNIZWFkSWNvbhD8AxIbChZOb0hhc1RoaXNIZWFkSWNv",
            "bkZyYW1lEP0DEhUKEFZJUExldmVsTm90UmVhY2gQ/gMSFwoSVklQQXdhcmRB",
            "bHJlYWR5R2V0EP8DEhwKF0Rvd25sb2FkQXdhcmRBbHJlYWR5R2V0EIAEEhcK",
            "EkhvbWVGYXJtTm9IZXJvV29yaxCBBBIcChdEYWlseVBoeXNpY2FsQWxyZWFk",
            "eUdldBCCBBIgChtSZWNoYXJnZVRvdGFsTW9tZW55Q2ZnRXJyb3IQgwQSJwoi",
            "UmVjaGFyZ2VUb3RhbE1vbWVueUF3YXJkQWxyZWFkeUdldBCEBBIgChtSZWNo",
            "YXJnZVRvdGFsTW9tZW55Tm9Fbm91Z2gQhQQSHAoXSGVyb1F1ZXN0Tm90QWxs",
            "RmluaXNoZWQQhgQSHQoYSGVyb1F1ZXN0QXdhcmRBbHJlYWR5R2V0EIcEEiAK",
            "G1JlY2hhcmdlVG90YWxNb21lbnlOb3RFeGlzdBCIBBIaChVSb2xsTW9uZXlU",
            "cmVlTWF4VGltZXMQiQQSHgoZUm9sbE1vbmV5VHJlZUF3YXJkQWxyZWFkeRCK",
            "BBIaChVQb0JpbmdBd2FyZEFscmVhZHlHZXQQiwQSHQoYRlhFcXVpcFJlZmlu",
            "ZUZhaWxRdWFsaXR5EIwEEhgKE0ZhaWxlZE1hdGNoT3Bwb25lbnQQjQQSGAoT",
            "UXVlc3RBd2FyZEFsZWFkeUdldBCOBBIhChxHdWlsZERldmVsb3BDaGFwdGVy",
            "Tm90RmluaXNoEI8EEiYKIUd1aWxkRGV2ZWxvcENoYXB0ZXJBd2FyZEFsZWFk",
            "eUdldBCQBBIdChhHdWlsZEd1YXJkV29yc2hpcE5vVGltZXMQkQQSEwoOWklO",
            "VEVSU1RPUkVFcnIQkgQSHwoaQXNzaXN0U2FuWGlhb1BsYXllcklEV3JvbmcQ",
            "kwQSHAoXTWluZ0dlRHJhd0NhcmROb1hpbll1YW4QlAQSJwoiRmFpbGVkVG9X",
            "b3JsZE1hdGNoU2Vhc29uU2NvcmVBd2FyZBCVBBIZChRZTVBEcmF3Q2FyZE5v",
            "WGluWXVhbhCWBBISCg1QaG90b05vdEV4aXN0EJcEEhYKEVBob3RvT3Zlck1h",
            "eENvdW50EJgEEhUKEFBob3RvTGlrZU5vQ291bnQQmQQSEgoNUGhvdG9VUkxF",
            "bXB0eRCaBBIZChRQaG90b1Bvc0FscmVhZHlFeGlzdBCbBBIZChRTdHJhdGVn",
            "eUZhaWxOb0hlcm9JRBCcBBISCg1TeXNTYW5YaWFvRXJyEJ0EEhgKE0xldmVs",
            "QXdhcmRBbGVhZHlHZXQQngQSFgoRTGV2ZWxBd2FyZE5vRXhpc3QQnwQSHAoX",
            "Q29tcG9zZUl0ZW1Db3N0Q2ZnRXJyb3IQoAQSGAoTVm91Y2hlckl0ZW1Ob0Vu",
            "b3VnaBChBBIYChNIYW5kQ2FyZENmZ05vdEV4aXN0EKIEEiAKG0hhbmRDYXJk",
            "UG9zaXRpb25DZmdOb3RFeGlzdBCjBBIgChtIYW5kQ2FyZFBvc2l0aW9uTm90",
            "VW5Mb2NrZWQQpAQSFgoRSGFuZENhcmRUeXBlTGltaXQQpQQSIAobSGFuZENh",
            "cmRQb3NpdGlvbk5vdEhhdmVIZXJvEKYEEiUKIEhhbmRDYXJkQWxyZWFkeUF0",
            "VGhlSGlnaGVzdExldmVsELAEEh0KGEhhbmRDYXJkVXBMZXZlbE5vdEVub3Vn",
            "aBCxBBIdChhIYW5kQ2FyZEN1clBvc2l0aW9uTm90SEMQsgQSFQoQSGFuZENh",
            "cmROb3RFeGlzdBCzBBITCg5TZW5zaXRpdmVXb3JkcxDoB2IGcHJvdG8z"));
      descriptor = pbr::FileDescriptor.FromGeneratedCode(descriptorData,
          new pbr::FileDescriptor[] { },
          new pbr::GeneratedClrTypeInfo(new[] {typeof(global::ErrorNo.ErrorNo), }, null, null));
    }
    #endregion

  }
  #region Enums
  public enum ErrorNo {
    [pbr::OriginalName("Success")] Success = 0,
    [pbr::OriginalName("FailedLogin")] FailedLogin = 1,
    [pbr::OriginalName("IncorrectPWD")] IncorrectPwd = 2,
    [pbr::OriginalName("FailedCreateAccount")] FailedCreateAccount = 3,
    [pbr::OriginalName("FailedCreatePlayer")] FailedCreatePlayer = 4,
    [pbr::OriginalName("NotFoundAccount")] NotFoundAccount = 5,
    [pbr::OriginalName("CreatePlayerLimit")] CreatePlayerLimit = 6,
    [pbr::OriginalName("FailedUpdateDBData")] FailedUpdateDbdata = 7,
    [pbr::OriginalName("NotFoundPlayer")] NotFoundPlayer = 8,
    [pbr::OriginalName("FailedInitPlayer")] FailedInitPlayer = 9,
    [pbr::OriginalName("NotFoundMatchSrv")] NotFoundMatchSrv = 10,
    [pbr::OriginalName("NotFoundSceneSrv")] NotFoundSceneSrv = 11,
    [pbr::OriginalName("FailedCreateBattle")] FailedCreateBattle = 12,
    [pbr::OriginalName("NotInCenter")] NotInCenter = 13,
    [pbr::OriginalName("NameAlreadyUse")] NameAlreadyUse = 14,
    [pbr::OriginalName("FailedCreateName")] FailedCreateName = 15,
    [pbr::OriginalName("NotFoundLoginKey")] NotFoundLoginKey = 16,
    [pbr::OriginalName("NameIsInValid")] NameIsInValid = 17,
    [pbr::OriginalName("FailedLoginBattle")] FailedLoginBattle = 18,
    [pbr::OriginalName("NotFoundBattleRoom")] NotFoundBattleRoom = 19,
    [pbr::OriginalName("AlreadyFight")] AlreadyFight = 20,
    [pbr::OriginalName("NotFoundPlayerInBattle")] NotFoundPlayerInBattle = 21,
    [pbr::OriginalName("InvalidItem")] InvalidItem = 22,
    [pbr::OriginalName("HasAlreadyItem")] HasAlreadyItem = 23,
    [pbr::OriginalName("InvalidHeroId")] InvalidHeroId = 24,
    [pbr::OriginalName("BagFull")] BagFull = 25,
    [pbr::OriginalName("MatchTimeout")] MatchTimeout = 26,
    [pbr::OriginalName("InvalidSkillID")] InvalidSkillId = 27,
    [pbr::OriginalName("NotFoundInBag")] NotFoundInBag = 29,
    [pbr::OriginalName("FailedCMD")] FailedCmd = 30,
    /// <summary>
    ///没有足够道具
    /// </summary>
    [pbr::OriginalName("NotEnoughItem")] NotEnoughItem = 35,
    [pbr::OriginalName("FailedUseItem")] FailedUseItem = 36,
    /// <summary>
    ///已经到达最大级
    /// </summary>
    [pbr::OriginalName("AlreadyMaxLv")] AlreadyMaxLv = 37,
    /// <summary>
    ///装备宝石失败
    /// </summary>
    [pbr::OriginalName("FailedEquipGem")] FailedEquipGem = 38,
    /// <summary>
    ///卸下装备宝石失败
    /// </summary>
    [pbr::OriginalName("FailedUnequipGem")] FailedUnequipGem = 39,
    /// <summary>
    ///宝石升级失败
    /// </summary>
    [pbr::OriginalName("FailedGemLV")] FailedGemLv = 40,
    /// <summary>
    ///穿装备失败
    /// </summary>
    [pbr::OriginalName("FailedEquipAny")] FailedEquipAny = 42,
    /// <summary>
    ///卸装备失败
    /// </summary>
    [pbr::OriginalName("FailedUnequipAny")] FailedUnequipAny = 43,
    [pbr::OriginalName("NotOnline")] NotOnline = 49,
    [pbr::OriginalName("FailedToPlayerLogin")] FailedToPlayerLogin = 50,
    /// <summary>
    ///没有找到英雄
    /// </summary>
    [pbr::OriginalName("NotFoundHero")] NotFoundHero = 51,
    /// <summary>
    ///英雄星际以及升满
    /// </summary>
    [pbr::OriginalName("HeroStarFull")] HeroStarFull = 52,
    /// <summary>
    ///战斗超时
    /// </summary>
    [pbr::OriginalName("BattleTimeout")] BattleTimeout = 53,
    /// <summary>
    ///创建PVE战斗失败
    /// </summary>
    [pbr::OriginalName("FailedCreatePVEBattle")] FailedCreatePvebattle = 54,
    /// <summary>
    ///正在战斗中
    /// </summary>
    [pbr::OriginalName("PlayerAlreadyInBattle")] PlayerAlreadyInBattle = 55,
    /// <summary>
    ///战斗校验失败,退出战斗
    /// </summary>
    [pbr::OriginalName("FailedToCheckReport")] FailedToCheckReport = 56,
    /// <summary>
    ///图集激活达到上限
    /// </summary>
    [pbr::OriginalName("AtlasActiveLimit")] AtlasActiveLimit = 57,
    /// <summary>
    ///锁道具失败
    /// </summary>
    [pbr::OriginalName("FailedToLockItem")] FailedToLockItem = 58,
    /// <summary>
    ///已经拥有此英雄
    /// </summary>
    [pbr::OriginalName("HasHero")] HasHero = 59,
    /// <summary>
    ///PVE关卡条件不足
    /// </summary>
    [pbr::OriginalName("InsufficientCondition")] InsufficientCondition = 60,
    /// <summary>
    ///没有足够的星星
    /// </summary>
    [pbr::OriginalName("NotEnoughStars")] NotEnoughStars = 61,
    /// <summary>
    ///没有足够的体力
    /// </summary>
    [pbr::OriginalName("NotEnoughPower")] NotEnoughPower = 62,
    /// <summary>
    ///等级不足
    /// </summary>
    [pbr::OriginalName("NotEnoughLevel")] NotEnoughLevel = 63,
    /// <summary>
    ///失败删除数据
    /// </summary>
    [pbr::OriginalName("FailedToDelData")] FailedToDelData = 64,
    /// <summary>
    ///失败的获取邮件内容
    /// </summary>
    [pbr::OriginalName("FailedToGetMailItem")] FailedToGetMailItem = 65,
    /// <summary>
    ///装备印记失败
    /// </summary>
    [pbr::OriginalName("FailedEquipStamp")] FailedEquipStamp = 66,
    /// <summary>
    ///装备印记失败
    /// </summary>
    [pbr::OriginalName("FailedUnequipStamp")] FailedUnequipStamp = 67,
    /// <summary>
    ///印记强化失败
    /// </summary>
    [pbr::OriginalName("FailedStampUpStar")] FailedStampUpStar = 68,
    /// <summary>
    ///印记强化到上限
    /// </summary>
    [pbr::OriginalName("StampStarMax")] StampStarMax = 69,
    /// <summary>
    ///没有足够宝石
    /// </summary>
    [pbr::OriginalName("NotEnoughGem")] NotEnoughGem = 70,
    /// <summary>
    ///开天牌已经装备
    /// </summary>
    [pbr::OriginalName("AlreadyEquipKT")] AlreadyEquipKt = 71,
    /// <summary>
    ///销售给系统道具失败
    /// </summary>
    [pbr::OriginalName("FailedSellToSys")] FailedSellToSys = 72,
    /// <summary>
    ///已经买过次开天牌
    /// </summary>
    [pbr::OriginalName("AlreadyBuyKT")] AlreadyBuyKt = 73,
    /// <summary>
    ///开天牌达到上限
    /// </summary>
    [pbr::OriginalName("KTBagLimit")] KtbagLimit = 74,
    /// <summary>
    ///失败的强化装备槽位
    /// </summary>
    [pbr::OriginalName("FailedToEquipLvUp")] FailedToEquipLvUp = 75,
    /// <summary>
    ///请先布阵
    /// </summary>
    [pbr::OriginalName("NeedEmbattle")] NeedEmbattle = 76,
    /// <summary>
    ///无效的关卡ID
    /// </summary>
    [pbr::OriginalName("InvalidLevelID")] InvalidLevelId = 77,
    /// <summary>
    ///前置关卡未完成
    /// </summary>
    [pbr::OriginalName("TowerAfterLevelNotFinish")] TowerAfterLevelNotFinish = 78,
    /// <summary>
    ///不能超过玩家的等级
    /// </summary>
    [pbr::OriginalName("SurpassPlayerLv")] SurpassPlayerLv = 79,
    /// <summary>
    ///失败的刷新开天牌商店
    /// </summary>
    [pbr::OriginalName("FailedToRefreshKTPShop")] FailedToRefreshKtpshop = 80,
    /// <summary>
    ///没有完成爬塔关卡
    /// </summary>
    [pbr::OriginalName("NotFinishTowerLevel")] NotFinishTowerLevel = 81,
    /// <summary>
    ///进入战斗的英雄抄错配置
    /// </summary>
    [pbr::OriginalName("EmbattleHeroLimit")] EmbattleHeroLimit = 83,
    /// <summary>
    ///没有足够开天币
    /// </summary>
    [pbr::OriginalName("NotEnoughKTCoin")] NotEnoughKtcoin = 84,
    /// <summary>
    ///神器升级失败
    /// </summary>
    [pbr::OriginalName("FailedToGodLevelUp")] FailedToGodLevelUp = 85,
    /// <summary>
    ///对手的排名已经更改
    /// </summary>
    [pbr::OriginalName("OppoentRankInvalid")] OppoentRankInvalid = 86,
    /// <summary>
    ///没有找到战斗录像
    /// </summary>
    [pbr::OriginalName("NotFoundBattleVideo")] NotFoundBattleVideo = 87,
    /// <summary>
    ///神器升级失败
    /// </summary>
    [pbr::OriginalName("InvalidItemType")] InvalidItemType = 88,
    /// <summary>
    ///领取章节宝箱失败
    /// </summary>
    [pbr::OriginalName("GetChapterBoxFail")] GetChapterBoxFail = 89,
    /// <summary>
    ///重连失败
    /// </summary>
    [pbr::OriginalName("FailedReconnnect")] FailedReconnnect = 91,
    /// <summary>
    ///没有找到上架的商品
    /// </summary>
    [pbr::OriginalName("NotFoundStoreItem")] NotFoundStoreItem = 92,
    /// <summary>
    ///没有足够的消耗品
    /// </summary>
    [pbr::OriginalName("NotEnoughConsumeItem")] NotEnoughConsumeItem = 93,
    /// <summary>
    ///失败的获得成就奖励
    /// </summary>
    [pbr::OriginalName("FailedToGetAchievementAward")] FailedToGetAchievementAward = 94,
    /// <summary>
    ///创建公会失败
    /// </summary>
    [pbr::OriginalName("FailedCreateGuild")] FailedCreateGuild = 95,
    /// <summary>
    ///玩家等级未达到
    /// </summary>
    [pbr::OriginalName("LevelNotReach")] LevelNotReach = 96,
    /// <summary>
    ///公会名字空
    /// </summary>
    [pbr::OriginalName("GuildNameEmpty")] GuildNameEmpty = 97,
    /// <summary>
    ///公会名字长度错误
    /// </summary>
    [pbr::OriginalName("GuildNameLengthError")] GuildNameLengthError = 98,
    /// <summary>
    ///公会名字已经存在
    /// </summary>
    [pbr::OriginalName("GuildNameAlreadyExist")] GuildNameAlreadyExist = 99,
    /// <summary>
    ///公会公告长度错误
    /// </summary>
    [pbr::OriginalName("GuildNoticeLengthError")] GuildNoticeLengthError = 100,
    /// <summary>
    ///创建公会道具不足
    /// </summary>
    [pbr::OriginalName("GuildItemNotEnough")] GuildItemNotEnough = 101,
    /// <summary>
    ///玩家已经加入公会
    /// </summary>
    [pbr::OriginalName("PlayerAlreadyJoinGuild")] PlayerAlreadyJoinGuild = 102,
    /// <summary>
    ///玩家未加入公会
    /// </summary>
    [pbr::OriginalName("PlayerNotJoinGuild")] PlayerNotJoinGuild = 103,
    /// <summary>
    /// 没有权限
    /// </summary>
    [pbr::OriginalName("GuildNoAuthority")] GuildNoAuthority = 104,
    /// <summary>
    /// 修改公会信息失败
    /// </summary>
    [pbr::OriginalName("GuildModifyError")] GuildModifyError = 105,
    /// <summary>
    /// 公会图标不存在
    /// </summary>
    [pbr::OriginalName("GuildIconNotExist")] GuildIconNotExist = 106,
    /// <summary>
    /// 公会图标未改变
    /// </summary>
    [pbr::OriginalName("GuildIconNoChange")] GuildIconNoChange = 107,
    /// <summary>
    /// 公会公告未改变
    /// </summary>
    [pbr::OriginalName("GuildNoticeNoChange")] GuildNoticeNoChange = 108,
    /// <summary>
    /// 玩家不在此公会
    /// </summary>
    [pbr::OriginalName("GuildPlayerNotIn")] GuildPlayerNotIn = 109,
    /// <summary>
    /// 错误的目标
    /// </summary>
    [pbr::OriginalName("GuildTargetError")] GuildTargetError = 110,
    /// <summary>
    /// 公会已解散
    /// </summary>
    [pbr::OriginalName("GuildAlreadyDisband")] GuildAlreadyDisband = 111,
    /// <summary>
    /// 公会解散中
    /// </summary>
    [pbr::OriginalName("GuildDisbanding")] GuildDisbanding = 112,
    /// <summary>
    /// 公会已正常
    /// </summary>
    [pbr::OriginalName("GuildAlreadyNormal")] GuildAlreadyNormal = 113,
    /// <summary>
    /// 公会不存在
    /// </summary>
    [pbr::OriginalName("GuildNotExist")] GuildNotExist = 114,
    /// <summary>
    /// 已经申请此公会
    /// </summary>
    [pbr::OriginalName("GuildAlreadyApplyThis")] GuildAlreadyApplyThis = 115,
    /// <summary>
    /// 公会人数已达上限
    /// </summary>
    [pbr::OriginalName("GuildOverMaxMember")] GuildOverMaxMember = 116,
    /// <summary>
    /// 玩家已经加入这个公会
    /// </summary>
    [pbr::OriginalName("GuildAlreadyInThis")] GuildAlreadyInThis = 117,
    /// <summary>
    /// 玩家不可以离开公会
    /// </summary>
    [pbr::OriginalName("GuildCanotLeave")] GuildCanotLeave = 118,
    /// <summary>
    ///不能踢掉自己
    /// </summary>
    [pbr::OriginalName("GuildCanotKickSelf")] GuildCanotKickSelf = 119,
    /// <summary>
    ///不能任命自己
    /// </summary>
    [pbr::OriginalName("GuildAppointSelf")] GuildAppointSelf = 120,
    /// <summary>
    ///不能操作自己
    /// </summary>
    [pbr::OriginalName("GuildOperateSelf")] GuildOperateSelf = 121,
    /// <summary>
    ///客户端传参错误
    /// </summary>
    [pbr::OriginalName("GuildParamsError")] GuildParamsError = 122,
    /// <summary>
    /// 玩家等级不满足入会条件
    /// </summary>
    [pbr::OriginalName("GuildPlayerLevelTooLow")] GuildPlayerLevelTooLow = 123,
    /// <summary>
    /// 战力不满足入会条件
    /// </summary>
    [pbr::OriginalName("GuildFightingTooLow")] GuildFightingTooLow = 124,
    /// <summary>
    /// 邮件内容为空
    /// </summary>
    [pbr::OriginalName("GuildMailEmpty")] GuildMailEmpty = 125,
    /// <summary>
    /// 邮件内容过长
    /// </summary>
    [pbr::OriginalName("GuildMailTooLarge")] GuildMailTooLarge = 126,
    /// <summary>
    /// 公会职务人数已满
    /// </summary>
    [pbr::OriginalName("GuildJobFull")] GuildJobFull = 127,
    /// <summary>
    /// 公会职务不存在
    /// </summary>
    [pbr::OriginalName("GuildJobNotExist")] GuildJobNotExist = 128,
    /// <summary>
    /// 已邀请该玩家
    /// </summary>
    [pbr::OriginalName("GuildAlreadyInvite")] GuildAlreadyInvite = 129,
    /// <summary>
    /// 邀请不存在
    /// </summary>
    [pbr::OriginalName("GuildInviteNotExist")] GuildInviteNotExist = 130,
    /// <summary>
    ///建筑不存在
    /// </summary>
    [pbr::OriginalName("GuildBuildingNotExist")] GuildBuildingNotExist = 131,
    /// <summary>
    ///建筑无法再升级
    /// </summary>
    [pbr::OriginalName("GuildBuildingAlreadyMax")] GuildBuildingAlreadyMax = 132,
    /// <summary>
    /// 公会等级不足
    /// </summary>
    [pbr::OriginalName("GuildLevelNoEnough")] GuildLevelNoEnough = 133,
    /// <summary>
    /// 公会金钱不足
    /// </summary>
    [pbr::OriginalName("GuildMoneyNoEnough")] GuildMoneyNoEnough = 134,
    /// <summary>
    /// 邮件群发CD中
    /// </summary>
    [pbr::OriginalName("GuildMailBroadcastCD")] GuildMailBroadcastCd = 135,
    /// <summary>
    /// 加入公会CD中
    /// </summary>
    [pbr::OriginalName("GuildRejoinCD")] GuildRejoinCd = 136,
    /// <summary>
    ///没有足够的挑战次数
    /// </summary>
    [pbr::OriginalName("NotEnoughChallengeNum")] NotEnoughChallengeNum = 137,
    /// <summary>
    ///失败的获取任务奖励
    /// </summary>
    [pbr::OriginalName("FailedToGetQuestAward")] FailedToGetQuestAward = 138,
    /// <summary>
    ///失败的获取活跃值奖励
    /// </summary>
    [pbr::OriginalName("FailedToGetActiveValueAward")] FailedToGetActiveValueAward = 139,
    /// <summary>
    ///列传传上来的参数不对
    /// </summary>
    [pbr::OriginalName("InvalidLieZhuanParm")] InvalidLieZhuanParm = 140,
    /// <summary>
    ///达到购买上限
    /// </summary>
    [pbr::OriginalName("AlreadyBuyLimit")] AlreadyBuyLimit = 141,
    /// <summary>
    /// redisKey错误
    /// </summary>
    [pbr::OriginalName("RedisKeyError")] RedisKeyError = 142,
    /// <summary>
    /// redis获取排行数据失败
    /// </summary>
    [pbr::OriginalName("RedisRankError")] RedisRankError = 143,
    /// <summary>
    /// redis数据为空
    /// </summary>
    [pbr::OriginalName("RedisDataEmpty")] RedisDataEmpty = 144,
    /// <summary>
    /// 远征关卡错误
    /// </summary>
    [pbr::OriginalName("ExpeditionLevelError")] ExpeditionLevelError = 145,
    /// <summary>
    /// 远征没有挑战次数
    /// </summary>
    [pbr::OriginalName("ExpeditionChallengeNoCount")] ExpeditionChallengeNoCount = 146,
    /// <summary>
    /// 远征关卡重置中
    /// </summary>
    [pbr::OriginalName("ExpeditionReseting")] ExpeditionReseting = 147,
    /// <summary>
    /// 远征挑战中
    /// </summary>
    [pbr::OriginalName("ExpeditionChallenging")] ExpeditionChallenging = 148,
    /// <summary>
    ///系统还未开启
    /// </summary>
    [pbr::OriginalName("NotSystemOpen")] NotSystemOpen = 149,
    /// <summary>
    ///清空数据库表
    /// </summary>
    [pbr::OriginalName("FailedToTruncateTable")] FailedToTruncateTable = 150,
    /// <summary>
    ///搜索好友失败
    /// </summary>
    [pbr::OriginalName("FailedToFindFriend")] FailedToFindFriend = 151,
    /// <summary>
    ///失败的进行ZRangeByScore
    /// </summary>
    [pbr::OriginalName("FailedToZRangeByScore")] FailedToZrangeByScore = 152,
    /// <summary>
    ///失败的存储事务
    /// </summary>
    [pbr::OriginalName("FailedToStoreAnyTable")] FailedToStoreAnyTable = 153,
    /// <summary>
    ///QueryDb失败
    /// </summary>
    [pbr::OriginalName("FailedToQueryDb")] FailedToQueryDb = 154,
    /// <summary>
    ///pb解析失败
    /// </summary>
    [pbr::OriginalName("FailedToDecodePbData")] FailedToDecodePbData = 155,
    /// <summary>
    ///QueryDb失败
    /// </summary>
    [pbr::OriginalName("QueryDb_NotData")] QueryDbNotData = 156,
    /// <summary>
    ///装饰不存在
    /// </summary>
    [pbr::OriginalName("HomeOrnamentNotExist")] HomeOrnamentNotExist = 157,
    /// <summary>
    ///装饰数量为0
    /// </summary>
    [pbr::OriginalName("HomeOrnamentEmpty")] HomeOrnamentEmpty = 158,
    /// <summary>
    ///家园建筑不存在
    /// </summary>
    [pbr::OriginalName("HomeBuildingNotExist")] HomeBuildingNotExist = 159,
    /// <summary>
    ///家园建筑已存在
    /// </summary>
    [pbr::OriginalName("HomeBuildingAlreadyExist")] HomeBuildingAlreadyExist = 160,
    /// <summary>
    ///家园建筑已经最大级
    /// </summary>
    [pbr::OriginalName("HomeBuildingAlreadyMax")] HomeBuildingAlreadyMax = 161,
    /// <summary>
    ///家园英雄不存在
    /// </summary>
    [pbr::OriginalName("HomeHeroNotExist")] HomeHeroNotExist = 162,
    /// <summary>
    ///家园英雄好剧情配置错误
    /// </summary>
    [pbr::OriginalName("HomeHeroStoryCfgError")] HomeHeroStoryCfgError = 163,
    /// <summary>
    ///家园英雄已在场景中
    /// </summary>
    [pbr::OriginalName("HomeHeroAlreayInScene")] HomeHeroAlreayInScene = 164,
    /// <summary>
    ///家园英与喜欢的饰物互动次数不足
    /// </summary>
    [pbr::OriginalName("HomeHeroInteractNumNoEnough")] HomeHeroInteractNumNoEnough = 165,
    /// <summary>
    ///异地登录
    /// </summary>
    [pbr::OriginalName("OtherPlatformLogin")] OtherPlatformLogin = 166,
    /// <summary>
    ///家园英雄放置数量超出上限
    /// </summary>
    [pbr::OriginalName("HomeHeroPlaceOverMax")] HomeHeroPlaceOverMax = 167,
    /// <summary>
    ///家园区域不存在
    /// </summary>
    [pbr::OriginalName("HomeRegionNotExist")] HomeRegionNotExist = 168,
    /// <summary>
    ///家园区域未解锁
    /// </summary>
    [pbr::OriginalName("HomeRegionNotUnlock")] HomeRegionNotUnlock = 169,
    /// <summary>
    /// 三消配置ID错误
    /// </summary>
    [pbr::OriginalName("SanxiaoCfgIDError")] SanxiaoCfgIderror = 170,
    /// <summary>
    /// 无尽试炼数据为空
    /// </summary>
    [pbr::OriginalName("TrialDataNil")] TrialDataNil = 172,
    /// <summary>
    /// 无尽试炼阵型错误
    /// </summary>
    [pbr::OriginalName("TrialFormationError")] TrialFormationError = 173,
    /// <summary>
    /// 无尽试炼前端关卡进度错误
    /// </summary>
    [pbr::OriginalName("TrialLevelCfgError")] TrialLevelCfgError = 174,
    /// <summary>
    /// 无尽试炼前端关卡进度错误
    /// </summary>
    [pbr::OriginalName("TrialClientLevelError")] TrialClientLevelError = 175,
    /// <summary>
    /// 无尽试炼战斗未开启
    /// </summary>
    [pbr::OriginalName("TrialBattleNotCreate")] TrialBattleNotCreate = 176,
    /// <summary>
    ///任务完成需要消耗的道具不足
    /// </summary>
    [pbr::OriginalName("QuestConsumeItemNotEnough")] QuestConsumeItemNotEnough = 177,
    /// <summary>
    ///任务不存在
    /// </summary>
    [pbr::OriginalName("QuestNotExist")] QuestNotExist = 178,
    /// <summary>
    ///新账号注册成功
    /// </summary>
    [pbr::OriginalName("AccountNew")] AccountNew = 179,
    /// <summary>
    ///代消发起请求达到上限
    /// </summary>
    [pbr::OriginalName("DaiXiaoReqLimit")] DaiXiaoReqLimit = 180,
    /// <summary>
    ///三消校验超时
    /// </summary>
    [pbr::OriginalName("SanXiaoCheckTimeout")] SanXiaoCheckTimeout = 181,
    /// <summary>
    ///玩家在线数达到峰值
    /// </summary>
    [pbr::OriginalName("PlayerOnlineLimit")] PlayerOnlineLimit = 182,
    /// <summary>
    ///服务器维护
    /// </summary>
    [pbr::OriginalName("ServerMaintain")] ServerMaintain = 183,
    /// <summary>
    ///创角名字长度错误
    /// </summary>
    [pbr::OriginalName("PlayerNameLengthError")] PlayerNameLengthError = 184,
    /// <summary>
    /// 远征无法扫荡
    /// </summary>
    [pbr::OriginalName("ExpeditionCannotSweep")] ExpeditionCannotSweep = 185,
    /// <summary>
    /// 远征扫荡奖励错误
    /// </summary>
    [pbr::OriginalName("ExpeditionSweepAwardError")] ExpeditionSweepAwardError = 186,
    /// <summary>
    ///英雄的星级不够
    /// </summary>
    [pbr::OriginalName("HeroStarNotEnough")] HeroStarNotEnough = 187,
    /// <summary>
    ///代消失效
    /// </summary>
    [pbr::OriginalName("DaiXiaoLoseEfficacy")] DaiXiaoLoseEfficacy = 189,
    /// <summary>
    ///开天牌技能已经装备
    /// </summary>
    [pbr::OriginalName("KTSkillAlreadyEquip")] KtskillAlreadyEquip = 192,
    /// <summary>
    ///开天牌技能槽位不足
    /// </summary>
    [pbr::OriginalName("KTSkillSlotNotEnough")] KtskillSlotNotEnough = 193,
    /// <summary>
    ///开天牌技能没有找到
    /// </summary>
    [pbr::OriginalName("KTSkillNotFound")] KtskillNotFound = 194,
    /// <summary>
    ///繁荣度不够
    /// </summary>
    [pbr::OriginalName("FanRongDuNotEnough")] FanRongDuNotEnough = 195,
    /// <summary>
    ///战斗版本号不匹配
    /// </summary>
    [pbr::OriginalName("BattleVerNotMatch")] BattleVerNotMatch = 196,
    /// <summary>
    ///三消版本号不匹配
    /// </summary>
    [pbr::OriginalName("SanXiaoVerNotMatch")] SanXiaoVerNotMatch = 197,
    /// <summary>
    ///开天牌槽位不足
    /// </summary>
    [pbr::OriginalName("KTSlotNotEnough")] KtslotNotEnough = 198,
    /// <summary>
    ///主角技能不存在
    /// </summary>
    [pbr::OriginalName("PlayerSkillNotFound")] PlayerSkillNotFound = 199,
    /// <summary>
    ///主角技能已经激活
    /// </summary>
    [pbr::OriginalName("PlayerSkillAlreadyActivate")] PlayerSkillAlreadyActivate = 200,
    /// <summary>
    ///主角属性激活失败 不符合激活条件	
    /// </summary>
    [pbr::OriginalName("ActivatePlayerAttrFail")] ActivatePlayerAttrFail = 201,
    /// <summary>
    ///主角配置无效
    /// </summary>
    [pbr::OriginalName("InvalidMainPlayerCfg")] InvalidMainPlayerCfg = 202,
    /// <summary>
    /// redis删除KEY失败
    /// </summary>
    [pbr::OriginalName("FAILED_REDIS_DEL_KEY")] FailedRedisDelKey = 203,
    /// <summary>
    ///这个区域需要三消
    /// </summary>
    [pbr::OriginalName("AreaNeedSanXiao")] AreaNeedSanXiao = 204,
    /// <summary>
    ///失败的获得每日爬塔奖励
    /// </summary>
    [pbr::OriginalName("FailedToGetDailyTowerAward")] FailedToGetDailyTowerAward = 205,
    /// <summary>
    ///商店刷新次数不足
    /// </summary>
    [pbr::OriginalName("StoreRefreshCountNotEnough")] StoreRefreshCountNotEnough = 206,
    /// <summary>
    ///玩家已经被禁言
    /// </summary>
    [pbr::OriginalName("ChatForbidden")] ChatForbidden = 207,
    /// <summary>
    ///玩家账号已经被封
    /// </summary>
    [pbr::OriginalName("PlayerAccountBlock")] PlayerAccountBlock = 208,
    /// <summary>
    ///主角技能升级失败
    /// </summary>
    [pbr::OriginalName("PlayerSkillLVUPFail")] PlayerSkillLvupfail = 209,
    /// <summary>
    ///公会捐献配置错误
    /// </summary>
    [pbr::OriginalName("GuildDonateCfgError")] GuildDonateCfgError = 210,
    /// <summary>
    /// 公会捐献所需道具不足	
    /// </summary>
    [pbr::OriginalName("GuildDonateItemNotEnough")] GuildDonateItemNotEnough = 211,
    /// <summary>
    /// 公会简介文本未发生更改
    /// </summary>
    [pbr::OriginalName("GuildIntroduceNoChange")] GuildIntroduceNoChange = 212,
    /// <summary>
    /// 公会简介文本长度错误
    /// </summary>
    [pbr::OriginalName("GuildIntroduceLengthError")] GuildIntroduceLengthError = 213,
    /// <summary>
    /// 公会权限数据错误
    /// </summary>
    [pbr::OriginalName("GuildAuthorityDataError")] GuildAuthorityDataError = 214,
    /// <summary>
    /// 公会建筑升级中
    /// </summary>
    [pbr::OriginalName("GuildBuildingInUpgrade")] GuildBuildingInUpgrade = 215,
    /// <summary>
    /// 公会拍卖没有物品
    /// </summary>
    [pbr::OriginalName("GuildAuctionNoItem")] GuildAuctionNoItem = 216,
    /// <summary>
    /// 公会拍卖未开始
    /// </summary>
    [pbr::OriginalName("GuildAuctionNoDoing")] GuildAuctionNoDoing = 217,
    /// <summary>
    /// 公会拍卖物品不存在
    /// </summary>
    [pbr::OriginalName("GuildAuctionItemNotExist")] GuildAuctionItemNotExist = 218,
    /// <summary>
    /// 公会拍卖重复竞价
    /// </summary>
    [pbr::OriginalName("GuildAuctionItemAlreayBid")] GuildAuctionItemAlreayBid = 219,
    /// <summary>
    /// 公会拍卖费用不足
    /// </summary>
    [pbr::OriginalName("GuildAuctionItemNotEnough")] GuildAuctionItemNotEnough = 220,
    /// <summary>
    /// 公会拍卖结束
    /// </summary>
    [pbr::OriginalName("GuildAuctionItemAlreadyFinished")] GuildAuctionItemAlreadyFinished = 221,
    /// <summary>
    /// 物品已竞拍成功
    /// </summary>
    [pbr::OriginalName("GuildAuctionItemAlreadyBuy")] GuildAuctionItemAlreadyBuy = 222,
    /// <summary>
    /// 公会等级已经是最大等级
    /// </summary>
    [pbr::OriginalName("GuildSkillAlreadyMax")] GuildSkillAlreadyMax = 223,
    /// <summary>
    /// 公会BOSS没有次数
    /// </summary>
    [pbr::OriginalName("GuildBossNoCount")] GuildBossNoCount = 224,
    /// <summary>
    /// 公会BOSS配置错误
    /// </summary>
    [pbr::OriginalName("GuildBossLevelCfgError")] GuildBossLevelCfgError = 225,
    /// <summary>
    /// 公会BOSS已死亡
    /// </summary>
    [pbr::OriginalName("GuildBossIsDead")] GuildBossIsDead = 226,
    /// <summary>
    /// 公会任务不存在
    /// </summary>
    [pbr::OriginalName("GuildQuestNotExist")] GuildQuestNotExist = 227,
    /// <summary>
    /// 公会任务未开启
    /// </summary>
    [pbr::OriginalName("GuildQuestNotOpen")] GuildQuestNotOpen = 228,
    /// <summary>
    /// 公会任务超出最大数量
    /// </summary>
    [pbr::OriginalName("GuildQuestOverMax")] GuildQuestOverMax = 229,
    /// <summary>
    ///引导达到上限
    /// </summary>
    [pbr::OriginalName("GuidanceLimit")] GuidanceLimit = 234,
    /// <summary>
    ///家园剧情上限
    /// </summary>
    [pbr::OriginalName("StoryProgressLimit")] StoryProgressLimit = 235,
    /// <summary>
    ///法相已经装备了英雄
    /// </summary>
    [pbr::OriginalName("AlreadyEquipHero")] AlreadyEquipHero = 236,
    /// <summary>
    ///共鸣英雄达到上限
    /// </summary>
    [pbr::OriginalName("GongMingHeroLimit")] GongMingHeroLimit = 237,
    /// <summary>
    ///法相升级失败
    /// </summary>
    [pbr::OriginalName("FailedToFXLevelUp")] FailedToFxlevelUp = 238,
    /// <summary>
    ///失败的获取主线关卡奖励
    /// </summary>
    [pbr::OriginalName("FailedGetLevelBox")] FailedGetLevelBox = 239,
    /// <summary>
    ///没有找到挑战者
    /// </summary>
    [pbr::OriginalName("NotFoundChallenger")] NotFoundChallenger = 240,
    /// <summary>
    ///阵营已设置
    /// </summary>
    [pbr::OriginalName("FactionTypeAlreadySet")] FactionTypeAlreadySet = 241,
    /// <summary>
    ///阵营类型错误
    /// </summary>
    [pbr::OriginalName("FactionTypeError")] FactionTypeError = 242,
    /// <summary>
    ///聊天请求超时
    /// </summary>
    [pbr::OriginalName("ChatReqTimeOut")] ChatReqTimeOut = 243,
    /// <summary>
    ///聊天频率受限
    /// </summary>
    [pbr::OriginalName("ChatFrequencyLimit")] ChatFrequencyLimit = 244,
    /// <summary>
    ///存储redis list 失败
    /// </summary>
    [pbr::OriginalName("RedisListStoreError")] RedisListStoreError = 245,
    /// <summary>
    ///失败的进行LRANGE
    /// </summary>
    [pbr::OriginalName("FailedToLRANGE")] FailedToLrange = 246,
    /// <summary>
    ///失败的获取聊天信息
    /// </summary>
    [pbr::OriginalName("FailedToGetChatMsgByRoomD")] FailedToGetChatMsgByRoomD = 247,
    /// <summary>
    ///失败签到
    /// </summary>
    [pbr::OriginalName("FailedToSignIn")] FailedToSignIn = 248,
    /// <summary>
    ///签到重置中
    /// </summary>
    [pbr::OriginalName("SignInReset")] SignInReset = 249,
    /// <summary>
    ///接受邀请失败 已有玩家率先进入协助
    /// </summary>
    [pbr::OriginalName("AcceptAssistFailLate")] AcceptAssistFailLate = 250,
    /// <summary>
    ///接受邀请失败 求助玩家已经过关
    /// </summary>
    [pbr::OriginalName("AcceptAssistFailPassLevel")] AcceptAssistFailPassLevel = 251,
    /// <summary>
    ///加入副本失败 已经在副本中
    /// </summary>
    [pbr::OriginalName("AssistEnterFailAlreadyIn")] AssistEnterFailAlreadyIn = 252,
    /// <summary>
    ///保存阵容失败
    /// </summary>
    [pbr::OriginalName("AssistSaveEmbattleInfoFail")] AssistSaveEmbattleInfoFail = 253,
    /// <summary>
    ///次数用尽
    /// </summary>
    [pbr::OriginalName("AssistNoTimes")] AssistNoTimes = 254,
    /// <summary>
    ///发出邀请失败
    /// </summary>
    [pbr::OriginalName("InviteAssistReqFail")] InviteAssistReqFail = 255,
    /// <summary>
    ///接受邀请失败 关卡等级不符合协助玩家自己的协助副本层数＜求助层数
    /// </summary>
    [pbr::OriginalName("AcceptAssistFailLevel")] AcceptAssistFailLevel = 256,
    /// <summary>
    ///接受邀请失败 玩家退出副本
    /// </summary>
    [pbr::OriginalName("AcceptAssistFailNoPlayer")] AcceptAssistFailNoPlayer = 257,
    /// <summary>
    ///加入副本失败 副本未开启
    /// </summary>
    [pbr::OriginalName("AssistEnterFailNotOpen")] AssistEnterFailNotOpen = 258,
    /// <summary>
    /// 邀请的玩家未准备就绪
    /// </summary>
    [pbr::OriginalName("AssistHelpPlayerNotReady")] AssistHelpPlayerNotReady = 259,
    /// <summary>
    ///不存在的玩家
    /// </summary>
    [pbr::OriginalName("AssistPlayerInValid")] AssistPlayerInValid = 260,
    /// <summary>
    ///协助副本扫荡失败 错误的等级
    /// </summary>
    [pbr::OriginalName("AssistSweepWrongLevel")] AssistSweepWrongLevel = 261,
    /// <summary>
    /// 玩家还未选择阵营
    /// </summary>
    [pbr::OriginalName("GuildPlayerNoFaction")] GuildPlayerNoFaction = 262,
    /// <summary>
    /// 公会阵营不一致
    /// </summary>
    [pbr::OriginalName("GuildFactionNotMatch")] GuildFactionNotMatch = 263,
    /// <summary>
    /// 不能加入这个公会阵营
    /// </summary>
    [pbr::OriginalName("GuildCanotApplyThisFaction")] GuildCanotApplyThisFaction = 264,
    /// <summary>
    /// 查找名字不合法
    /// </summary>
    [pbr::OriginalName("GuildSearchNameInvalid")] GuildSearchNameInvalid = 265,
    /// <summary>
    ///登录Token无效
    /// </summary>
    [pbr::OriginalName("LoginTokenInvaild")] LoginTokenInvaild = 266,
    /// <summary>
    ///喜讯点赞失败
    /// </summary>
    [pbr::OriginalName("FailedXiXunDianZan")] FailedXiXunDianZan = 267,
    /// <summary>
    ///陌生人聊天失败
    /// </summary>
    [pbr::OriginalName("FailedStangerChat")] FailedStangerChat = 268,
    /// <summary>
    ///失败的拉黑
    /// </summary>
    [pbr::OriginalName("FailedBlackFriend")] FailedBlackFriend = 269,
    /// <summary>
    /// 未实名验证
    /// </summary>
    [pbr::OriginalName("RealUserNotVerification")] RealUserNotVerification = 270,
    /// <summary>
    /// 未成年限制时间段
    /// </summary>
    [pbr::OriginalName("NonageCanotPlayTime")] NonageCanotPlayTime = 271,
    /// <summary>
    /// 未成年超出在线时长
    /// </summary>
    [pbr::OriginalName("NonageOverPlayTime")] NonageOverPlayTime = 272,
    /// <summary>
    ///支付请求超时
    /// </summary>
    [pbr::OriginalName("PayReqTimeOut")] PayReqTimeOut = 273,
    /// <summary>
    ///支付请求失败
    /// </summary>
    [pbr::OriginalName("PayReqFail")] PayReqFail = 274,
    /// <summary>
    ///爬塔战力错误
    /// </summary>
    [pbr::OriginalName("FailedTowerPower")] FailedTowerPower = 275,
    /// <summary>
    ///心跳超时
    /// </summary>
    [pbr::OriginalName("HeartbeatTimeout")] HeartbeatTimeout = 276,
    /// <summary>
    ///充值商品错误
    /// </summary>
    [pbr::OriginalName("RechargeStoreCfgError")] RechargeStoreCfgError = 277,
    /// <summary>
    ///购买抽卡券次数不足
    /// </summary>
    [pbr::OriginalName("BuyChoukaNoTimes")] BuyChoukaNoTimes = 278,
    /// <summary>
    ///未成人单次充值金额限制
    /// </summary>
    [pbr::OriginalName("RechargeNonageOnceLimit")] RechargeNonageOnceLimit = 279,
    /// <summary>
    ///未成人每月充值金额限制
    /// </summary>
    [pbr::OriginalName("RechargeNonageMonthLimit")] RechargeNonageMonthLimit = 280,
    /// <summary>
    ///爬塔战力错误
    /// </summary>
    [pbr::OriginalName("FailedExpeditionPower")] FailedExpeditionPower = 281,
    /// <summary>
    ///抽卡次数不足
    /// </summary>
    [pbr::OriginalName("NotEnoughChouKaCount")] NotEnoughChouKaCount = 282,
    /// <summary>
    /// 未成年登录年龄限制
    /// </summary>
    [pbr::OriginalName("NonageLoginAgeLimit")] NonageLoginAgeLimit = 283,
    /// <summary>
    /// GM踢下线
    /// </summary>
    [pbr::OriginalName("GMKickOut")] GmkickOut = 284,
    /// <summary>
    ///需要进行三消
    /// </summary>
    [pbr::OriginalName("NeedLieZhuanSanXiao")] NeedLieZhuanSanXiao = 285,
    /// <summary>
    ///星君领取奖励失败
    /// </summary>
    [pbr::OriginalName("XingJunRewardFail")] XingJunRewardFail = 286,
    /// <summary>
    ///玩家存储数据是吧
    /// </summary>
    [pbr::OriginalName("ServerDataReqFail")] ServerDataReqFail = 287,
    /// <summary>
    ///活动结束
    /// </summary>
    [pbr::OriginalName("RingActivityAlreadyEnd")] RingActivityAlreadyEnd = 288,
    /// <summary>
    ///活动未开启
    /// </summary>
    [pbr::OriginalName("RingActivityNotStart")] RingActivityNotStart = 289,
    /// <summary>
    ///活动未知错误
    /// </summary>
    [pbr::OriginalName("ActivityStateError")] ActivityStateError = 290,
    /// <summary>
    ///重复报名
    /// </summary>
    [pbr::OriginalName("RingRepeatApply")] RingRepeatApply = 291,
    /// <summary>
    /// 主线关卡未解锁
    /// </summary>
    [pbr::OriginalName("ChapterLevelNotOpen")] ChapterLevelNotOpen = 292,
    /// <summary>
    /// 玩家消除宝典数据错误
    /// </summary>
    [pbr::OriginalName("SanXiaoBaoDianDataError")] SanXiaoBaoDianDataError = 293,
    /// <summary>
    /// 玩家消除宝典排行数据错误
    /// </summary>
    [pbr::OriginalName("SanXiaoBaoDianRankDataError")] SanXiaoBaoDianRankDataError = 294,
    /// <summary>
    ///没有足够的挑战次数
    /// </summary>
    [pbr::OriginalName("RingNouEnoughChallengeNum")] RingNouEnoughChallengeNum = 295,
    /// <summary>
    ///擂台没有报名
    /// </summary>
    [pbr::OriginalName("RingNotApply")] RingNotApply = 296,
    /// <summary>
    /// 公会任务发布量不足
    /// </summary>
    [pbr::OriginalName("GuildQuestNotEnough")] GuildQuestNotEnough = 297,
    /// <summary>
    ///擂台报名达到上限
    /// </summary>
    [pbr::OriginalName("RingApplyLimit")] RingApplyLimit = 298,
    /// <summary>
    ///redis Get命令请求失败
    /// </summary>
    [pbr::OriginalName("RedisGetError")] RedisGetError = 299,
    /// <summary>
    ///redis Set命令请求失败
    /// </summary>
    [pbr::OriginalName("RedisSetError")] RedisSetError = 300,
    /// <summary>
    ///redis key 不存在
    /// </summary>
    [pbr::OriginalName("RedisKeyNotExist")] RedisKeyNotExist = 301,
    /// <summary>
    ///已经领取过FB奖励邮件
    /// </summary>
    [pbr::OriginalName("FBMailAlreadyGet")] FbmailAlreadyGet = 302,
    /// <summary>
    ///失败的插入DB
    /// </summary>
    [pbr::OriginalName("FailedToDBInsert")] FailedToDbinsert = 303,
    /// <summary>
    ///DBUpdate失败
    /// </summary>
    [pbr::OriginalName("FailedToDBUpdate")] FailedToDbupdate = 304,
    /// <summary>
    ///DB创建PlayerNameID失败
    /// </summary>
    [pbr::OriginalName("FailedToCreatePlayerNameID")] FailedToCreatePlayerNameId = 305,
    /// <summary>
    ///失败的获取七日奖励
    /// </summary>
    [pbr::OriginalName("FailedToGetSevenDayAward")] FailedToGetSevenDayAward = 306,
    /// <summary>
    ///兑换码已经使用
    /// </summary>
    [pbr::OriginalName("FailGetCodeUsed")] FailGetCodeUsed = 307,
    /// <summary>
    ///没有这个兑换码
    /// </summary>
    [pbr::OriginalName("FailGetCodeNone")] FailGetCodeNone = 308,
    /// <summary>
    ///秘籍未激活
    /// </summary>
    [pbr::OriginalName("PlayerBookNotAcctive")] PlayerBookNotAcctive = 309,
    /// <summary>
    ///秘籍ID错误
    /// </summary>
    [pbr::OriginalName("BookIdNotFind")] BookIdNotFind = 310,
    /// <summary>
    ///此秘籍不适配此心法
    /// </summary>
    [pbr::OriginalName("EquipBookFailNotMatch")] EquipBookFailNotMatch = 311,
    /// <summary>
    ///非法孔位
    /// </summary>
    [pbr::OriginalName("EquipBookllegalPosition")] EquipBookllegalPosition = 312,
    /// <summary>
    ///秘籍升级失败
    /// </summary>
    [pbr::OriginalName("PlayerBookLvUpFail")] PlayerBookLvUpFail = 313,
    /// <summary>
    ///秘籍洗练失败秘籍未机会
    /// </summary>
    [pbr::OriginalName("RefreshBookNotAcctive")] RefreshBookNotAcctive = 314,
    /// <summary>
    ///主角技能未激活
    /// </summary>
    [pbr::OriginalName("PlayerSkillNotAcctive")] PlayerSkillNotAcctive = 315,
    /// <summary>
    ///营地未解锁
    /// </summary>
    [pbr::OriginalName("CampNotUnlock")] CampNotUnlock = 316,
    /// <summary>
    ///营地位置已解锁
    /// </summary>
    [pbr::OriginalName("CampPosAlreadyUnlock")] CampPosAlreadyUnlock = 317,
    /// <summary>
    ///营地位置未解锁
    /// </summary>
    [pbr::OriginalName("CampPosNotUnlock")] CampPosNotUnlock = 318,
    /// <summary>
    ///营地位置解锁错误
    /// </summary>
    [pbr::OriginalName("CampPosUnlockError")] CampPosUnlockError = 319,
    /// <summary>
    ///营地位置没有放置幻灵
    /// </summary>
    [pbr::OriginalName("CampPosNoHero")] CampPosNoHero = 320,
    /// <summary>
    ///营地位置已放置幻灵
    /// </summary>
    [pbr::OriginalName("CampPosAlreadyHasHero")] CampPosAlreadyHasHero = 321,
    /// <summary>
    ///营地位置不能放置此幻灵
    /// </summary>
    [pbr::OriginalName("CampPosCannotPlaceHero")] CampPosCannotPlaceHero = 322,
    /// <summary>
    ///营地幻灵已放置
    /// </summary>
    [pbr::OriginalName("CampHeroAlreadyPlace")] CampHeroAlreadyPlace = 323,
    /// <summary>
    ///英雄星级为0
    /// </summary>
    [pbr::OriginalName("HeroStarEmpty")] HeroStarEmpty = 324,
    /// <summary>
    ///秘籍洗练失败 没有可以洗练的词条
    /// </summary>
    [pbr::OriginalName("RereshSkillBookFailNoEntry")] RereshSkillBookFailNoEntry = 325,
    /// <summary>
    /// 家园商店物品为空
    /// </summary>
    [pbr::OriginalName("HomeStoreItemEmpty")] HomeStoreItemEmpty = 326,
    /// <summary>
    /// 家园建筑配置错误
    /// </summary>
    [pbr::OriginalName("HomeBuildingCfgError")] HomeBuildingCfgError = 327,
    /// <summary>
    /// 家园拜访者已满
    /// </summary>
    [pbr::OriginalName("HomeCourtyardVisitorFull")] HomeCourtyardVisitorFull = 328,
    /// <summary>
    /// 家园被拜访次数不足
    /// </summary>
    [pbr::OriginalName("HomeCourtyardByVisitCountEmpty")] HomeCourtyardByVisitCountEmpty = 329,
    /// <summary>
    /// 家园拜访次数不足
    /// </summary>
    [pbr::OriginalName("HomeCourtyardVisitCountEmpty")] HomeCourtyardVisitCountEmpty = 330,
    /// <summary>
    /// 家园旅馆房间不存在
    /// </summary>
    [pbr::OriginalName("HomeHotelRoomNotExist")] HomeHotelRoomNotExist = 331,
    /// <summary>
    /// 英雄不在这个家园旅馆房间
    /// </summary>
    [pbr::OriginalName("HomeHotelRoomHeroNotExist")] HomeHotelRoomHeroNotExist = 332,
    /// <summary>
    /// 当前房间人数已满，升级舒适度可以增加上场人数
    /// </summary>
    [pbr::OriginalName("HomeHotelRoomHeroFull")] HomeHotelRoomHeroFull = 333,
    /// <summary>
    /// 不能进入这个家园旅馆房间
    /// </summary>
    [pbr::OriginalName("HomeHotelHeroCanotJoinThis")] HomeHotelHeroCanotJoinThis = 334,
    /// <summary>
    /// 家园奇遇次数不足
    /// </summary>
    [pbr::OriginalName("HomeAdventureCountNoEnough")] HomeAdventureCountNoEnough = 335,
    /// <summary>
    /// 家园奇遇节点配置错误
    /// </summary>
    [pbr::OriginalName("HomeAdventureNodeCfgError")] HomeAdventureNodeCfgError = 336,
    /// <summary>
    /// 家园奇遇未开始
    /// </summary>
    [pbr::OriginalName("HomeAdventureNotStart")] HomeAdventureNotStart = 337,
    /// <summary>
    /// 家园奇遇未结束
    /// </summary>
    [pbr::OriginalName("HomeAdventureNotFinished")] HomeAdventureNotFinished = 338,
    /// <summary>
    /// 家园奇遇不是战斗节点
    /// </summary>
    [pbr::OriginalName("HomeAdventureNotBattleNode")] HomeAdventureNotBattleNode = 339,
    /// <summary>
    /// 家园英雄已在种田中
    /// </summary>
    [pbr::OriginalName("HomeFarmHeroAlreadyBusy")] HomeFarmHeroAlreadyBusy = 340,
    /// <summary>
    /// 家园种田好友人数已满
    /// </summary>
    [pbr::OriginalName("HomeFarmFriendHeroOverMax")] HomeFarmFriendHeroOverMax = 341,
    /// <summary>
    /// 家园种田次数不足
    /// </summary>
    [pbr::OriginalName("HomeFarmWorkNoCount")] HomeFarmWorkNoCount = 342,
    /// <summary>
    /// 家园帮助好友种田次数不足
    /// </summary>
    [pbr::OriginalName("HomeFarmFriendWorkNoCount")] HomeFarmFriendWorkNoCount = 343,
    /// <summary>
    /// 家园英雄在好友家种田
    /// </summary>
    [pbr::OriginalName("HomeFarmHeroInFriendHome")] HomeFarmHeroInFriendHome = 344,
    /// <summary>
    /// 家园种田人数已满
    /// </summary>
    [pbr::OriginalName("HomeFarmHeroOverMax")] HomeFarmHeroOverMax = 345,
    /// <summary>
    /// 英雄已经进入旅馆房间
    /// </summary>
    [pbr::OriginalName("HomeHotelHeroAlreadyInRoom")] HomeHotelHeroAlreadyInRoom = 346,
    /// <summary>
    /// 家园旅馆英雄人数已满
    /// </summary>
    [pbr::OriginalName("HomeHotelHeroFull")] HomeHotelHeroFull = 347,
    /// <summary>
    /// 家园旅馆任务已完成
    /// </summary>
    [pbr::OriginalName("HomeHotelQuestFinished")] HomeHotelQuestFinished = 348,
    /// <summary>
    /// redis断连了
    /// </summary>
    [pbr::OriginalName("RedisDisconnect")] RedisDisconnect = 349,
    /// <summary>
    ///抽卡累计次数不足
    /// </summary>
    [pbr::OriginalName("NotEnoughDrawCardCount")] NotEnoughDrawCardCount = 350,
    /// <summary>
    ///觉醒等级错误
    /// </summary>
    [pbr::OriginalName("HeroAwakeWrongLevel")] HeroAwakeWrongLevel = 360,
    /// <summary>
    ///无效的开天牌技能ID
    /// </summary>
    [pbr::OriginalName("InvaildAbilityCfgID")] InvaildAbilityCfgId = 361,
    /// <summary>
    ///开天牌技能槽位不够
    /// </summary>
    [pbr::OriginalName("KTSkillEquipSlotNotEnough")] KtskillEquipSlotNotEnough = 362,
    /// <summary>
    ///幻灵品质不符合
    /// </summary>
    [pbr::OriginalName("HeroAwakeWrongHeroQuality")] HeroAwakeWrongHeroQuality = 363,
    /// <summary>
    ///潜能升级 错误等级
    /// </summary>
    [pbr::OriginalName("HeroPotentialAttrWrongLv")] HeroPotentialAttrWrongLv = 364,
    /// <summary>
    ///血脉之力不足
    /// </summary>
    [pbr::OriginalName("BloodPowerNotEnough")] BloodPowerNotEnough = 365,
    /// <summary>
    /// http请求错误
    /// </summary>
    [pbr::OriginalName("HttpReqError")] HttpReqError = 366,
    /// <summary>
    /// http请求超时  
    /// </summary>
    [pbr::OriginalName("HttpReqTimeout")] HttpReqTimeout = 367,
    /// <summary>
    /// http请求内容解析错误
    /// </summary>
    [pbr::OriginalName("HttpResDecodeError")] HttpResDecodeError = 368,
    /// <summary>
    ///兑换码请求错误
    /// </summary>
    [pbr::OriginalName("RedeemCodeReqError")] RedeemCodeReqError = 369,
    /// <summary>
    ///兑换码已兑换道具
    /// </summary>
    [pbr::OriginalName("RedeemCodeAlreadyGetItem")] RedeemCodeAlreadyGetItem = 370,
    /// <summary>
    ///兑换码正在兑换中
    /// </summary>
    [pbr::OriginalName("RedeemCodeDoing")] RedeemCodeDoing = 371,
    /// <summary>
    /// 请求DB操作超时
    /// </summary>
    [pbr::OriginalName("DBReqTimeout")] DbreqTimeout = 372,
    /// <summary>
    ///布阵失败
    /// </summary>
    [pbr::OriginalName("FailedToEmbattle")] FailedToEmbattle = 373,
    /// <summary>
    ///擂台报名失败
    /// </summary>
    [pbr::OriginalName("FailedToRingApply")] FailedToRingApply = 374,
    /// <summary>
    /// 公会BOSS奖励已领取
    /// </summary>
    [pbr::OriginalName("GuildBossAwardTaked")] GuildBossAwardTaked = 375,
    /// <summary>
    /// 公会BOSS购买次数超出上限
    /// </summary>
    [pbr::OriginalName("GuildBossBuyCountOverMax")] GuildBossBuyCountOverMax = 376,
    /// <summary>
    /// 公会信息KEY不存在
    /// </summary>
    [pbr::OriginalName("GuildInfoKeyNotExist")] GuildInfoKeyNotExist = 377,
    /// <summary>
    ///取消目标镇守失败 还不是目标
    /// </summary>
    [pbr::OriginalName("RemoveTargetGuardNotIs")] RemoveTargetGuardNotIs = 378,
    /// <summary>
    ///邀请镇守失败 在保护时间
    /// </summary>
    [pbr::OriginalName("InviteGuardProtectTime")] InviteGuardProtectTime = 379,
    /// <summary>
    ///邀请镇守失败 已经是本学社的镇守
    /// </summary>
    [pbr::OriginalName("InviteGuardAlreadyIs")] InviteGuardAlreadyIs = 380,
    /// <summary>
    ///邀请镇守失败 在解除绑定后的保护时间
    /// </summary>
    [pbr::OriginalName("InviteGuardRemoveProtectTime")] InviteGuardRemoveProtectTime = 381,
    /// <summary>
    ///邀请镇守失败 好友度不符合
    /// </summary>
    [pbr::OriginalName("InviteGuardFriend")] InviteGuardFriend = 382,
    /// <summary>
    ///邀请失败 工会威望不符合
    /// </summary>
    [pbr::OriginalName("InviteGuardPrestige")] InviteGuardPrestige = 383,
    /// <summary>
    ///未找到对应学社镇守信息
    /// </summary>
    [pbr::OriginalName("GuardNotFound")] GuardNotFound = 384,
    /// <summary>
    ///学社镇守诱惑失败 不能诱惑已经入住本学社的镇守
    /// </summary>
    [pbr::OriginalName("TmptGuardOwner")] TmptGuardOwner = 385,
    /// <summary>
    ///邀请镇守失败 概率失败
    /// </summary>
    [pbr::OriginalName("InviteGuardFail")] InviteGuardFail = 386,
    /// <summary>
    ///邀请镇守失败 每日邀请次数上限
    /// </summary>
    [pbr::OriginalName("InviteGuardNoTimes")] InviteGuardNoTimes = 387,
    /// <summary>
    ///设置目标镇守失败 已经达到最大个数
    /// </summary>
    [pbr::OriginalName("TargetGuardMaxNum")] TargetGuardMaxNum = 388,
    /// <summary>
    ///设置目标镇守失败 已经是目标
    /// </summary>
    [pbr::OriginalName("TargetGuardAlreadyIs")] TargetGuardAlreadyIs = 389,
    /// <summary>
    ///邀请镇守失败 学社拥有镇守已经最大数量
    /// </summary>
    [pbr::OriginalName("InviteGuardMaxNum")] InviteGuardMaxNum = 390,
    /// <summary>
    ///实名认证错误
    /// </summary>
    [pbr::OriginalName("SDKQueryRealNameError")] SdkqueryRealNameError = 391,
    /// <summary>
    ///三消目标错误
    /// </summary>
    [pbr::OriginalName("SanXiaoColletRewardError")] SanXiaoColletRewardError = 392,
    /// <summary>
    ///三消目标为空
    /// </summary>
    [pbr::OriginalName("SanXiaoColletRewardEmpty")] SanXiaoColletRewardEmpty = 393,
    /// <summary>
    ///学社招募道具不足
    /// </summary>
    [pbr::OriginalName("GuildRecruitItemNotEnough")] GuildRecruitItemNotEnough = 394,
    /// <summary>
    ///学社招募消息为空
    /// </summary>
    [pbr::OriginalName("GuildRecruitMsgEmpty")] GuildRecruitMsgEmpty = 395,
    /// <summary>
    ///学社招募消息超出长度
    /// </summary>
    [pbr::OriginalName("GuildRecruitMsgLengthError")] GuildRecruitMsgLengthError = 396,
    /// <summary>
    ///没有布阵英雄	
    /// </summary>
    [pbr::OriginalName("NotEmbattleHero")] NotEmbattleHero = 397,
    /// <summary>
    /// 家宴每日举办次数已用完
    /// </summary>
    [pbr::OriginalName("HomePartyDayHoldCountEmpty")] HomePartyDayHoldCountEmpty = 398,
    /// <summary>
    /// 家宴每周举办次数已用完
    /// </summary>
    [pbr::OriginalName("HomePartyWeekHoldCountEmpty")] HomePartyWeekHoldCountEmpty = 399,
    /// <summary>
    /// 家宴预约时间错误
    /// </summary>
    [pbr::OriginalName("HomePartySubscribeTimeError")] HomePartySubscribeTimeError = 400,
    /// <summary>
    /// 家宴不在开启时间范围
    /// </summary>
    [pbr::OriginalName("HomePartyNotOpenTime")] HomePartyNotOpenTime = 401,
    /// <summary>
    /// 家宴开启时间已过期
    /// </summary>
    [pbr::OriginalName("HomePartyIsExpired")] HomePartyIsExpired = 402,
    /// <summary>
    /// 家宴不存在
    /// </summary>
    [pbr::OriginalName("HomePartyNotExist")] HomePartyNotExist = 403,
    /// <summary>
    /// 没有家宴开启权限
    /// </summary>
    [pbr::OriginalName("HomePartyNoOpenAuthority")] HomePartyNoOpenAuthority = 404,
    /// <summary>
    /// 家宴礼物不存在
    /// </summary>
    [pbr::OriginalName("HomePartyGiftNotExist")] HomePartyGiftNotExist = 405,
    /// <summary>
    /// 家宴每日吃席次数已用完
    /// </summary>
    [pbr::OriginalName("HomePartyJoinCountEmpty")] HomePartyJoinCountEmpty = 406,
    /// <summary>
    /// 玩家未加入家宴
    /// </summary>
    [pbr::OriginalName("HomePartyPlayerNotJoin")] HomePartyPlayerNotJoin = 407,
    /// <summary>
    /// 玩家已送礼
    /// </summary>
    [pbr::OriginalName("HomePartyPlayerAlreadyGift")] HomePartyPlayerAlreadyGift = 408,
    /// <summary>
    /// 家宴已开启
    /// </summary>
    [pbr::OriginalName("HomePartyAlreadyOpen")] HomePartyAlreadyOpen = 409,
    /// <summary>
    /// 家宴已被拾取
    /// </summary>
    [pbr::OriginalName("HomePartyAlreadyGet")] HomePartyAlreadyGet = 410,
    /// <summary>
    /// 家宴玩家没有撒糖操作权限
    /// </summary>
    [pbr::OriginalName("HomePartyCannotScatterSugar")] HomePartyCannotScatterSugar = 411,
    /// <summary>
    /// 家宴参加人数已满
    /// </summary>
    [pbr::OriginalName("HomePartyPlayerCountFull")] HomePartyPlayerCountFull = 412,
    /// <summary>
    /// 家宴玩家正忙
    /// </summary>
    [pbr::OriginalName("HomePartyPlayerBusy")] HomePartyPlayerBusy = 413,
    /// <summary>
    /// 已邀请对方
    /// </summary>
    [pbr::OriginalName("HomePartyDanceAlreadyInvite")] HomePartyDanceAlreadyInvite = 414,
    /// <summary>
    /// 共舞邀请已过期
    /// </summary>
    [pbr::OriginalName("HomePartyDanceInviteExpired")] HomePartyDanceInviteExpired = 415,
    /// <summary>
    /// 烟花未放置
    /// </summary>
    [pbr::OriginalName("HomePartyFireworkNotPlace")] HomePartyFireworkNotPlace = 416,
    /// <summary>
    /// 已吃完菜
    /// </summary>
    [pbr::OriginalName("HomePartyAlreadyEatDish")] HomePartyAlreadyEatDish = 417,
    /// <summary>
    ///需要进行三消
    /// </summary>
    [pbr::OriginalName("NeedGuardBossSanXiao")] NeedGuardBossSanXiao = 418,
    /// <summary>
    ///邀请镇守失败 该镇守现在正在镇守BOSS活动中
    /// </summary>
    [pbr::OriginalName("InviteGuardInBossTime")] InviteGuardInBossTime = 419,
    /// <summary>
    ///公会消息侦查次数不足
    /// </summary>
    [pbr::OriginalName("GuildMsgInvestigateCountNotEnough")] GuildMsgInvestigateCountNotEnough = 420,
    /// <summary>
    ///镇守BOSS最大鼓舞次数
    /// </summary>
    [pbr::OriginalName("GuardBossInspireMaxNum")] GuardBossInspireMaxNum = 421,
    /// <summary>
    /// 获取镇守BOSS排行榜列表失败  活动状态错误
    /// </summary>
    [pbr::OriginalName("GetBossDamageRankListWrongState")] GetBossDamageRankListWrongState = 422,
    /// <summary>
    /// 公会建筑升级事件不存在
    /// </summary>
    [pbr::OriginalName("GuildBuildEventNotExist")] GuildBuildEventNotExist = 423,
    /// <summary>
    /// 公会建筑升级事件已结束
    /// </summary>
    [pbr::OriginalName("GuildBuildEventAreadyFinish")] GuildBuildEventAreadyFinish = 424,
    /// <summary>
    /// 获取宝箱失败 宝箱不存在
    /// </summary>
    [pbr::OriginalName("GetBossBoxNotExit")] GetBossBoxNotExit = 425,
    /// <summary>
    /// 家宴未开启
    /// </summary>
    [pbr::OriginalName("HomePartyNotOpen")] HomePartyNotOpen = 426,
    /// <summary>
    /// 公会拍卖分红已领取
    /// </summary>
    [pbr::OriginalName("GuildAuctionBonusAlreadyGet")] GuildAuctionBonusAlreadyGet = 427,
    /// <summary>
    /// 没有公会拍卖分红
    /// </summary>
    [pbr::OriginalName("GuildNoAuctionBonus")] GuildNoAuctionBonus = 428,
    /// <summary>
    /// 烟花不存在
    /// </summary>
    [pbr::OriginalName("HomePartyFireworkNotExist")] HomePartyFireworkNotExist = 429,
    /// <summary>
    /// 7-14日购买失败
    /// </summary>
    [pbr::OriginalName("FailedToSevenFourteenSaleItem")] FailedToSevenFourteenSaleItem = 430,
    /// <summary>
    /// 7-14日活跃值失败
    /// </summary>
    [pbr::OriginalName("FailedToSevenFourteenActiveItem")] FailedToSevenFourteenActiveItem = 431,
    /// <summary>
    ///获取兑换码礼包失败
    /// </summary>
    [pbr::OriginalName("FailedGetCodeReward")] FailedGetCodeReward = 432,
    /// <summary>
    /// redis错误 成员已经存在
    /// </summary>
    [pbr::OriginalName("RedisMemberExist")] RedisMemberExist = 433,
    /// <summary>
    /// </summary>
    [pbr::OriginalName("RedisSAddError")] RedisSaddError = 434,
    /// <summary>
    /// 工会状态非正常 不能参加镇守活动
    /// </summary>
    [pbr::OriginalName("InGuildWrongState")] InGuildWrongState = 435,
    /// <summary>
    ///镇守活动中
    /// </summary>
    [pbr::OriginalName("GuardInBossTime")] GuardInBossTime = 436,
    /// <summary>
    /// 家宴酿酒次数已用完
    /// </summary>
    [pbr::OriginalName("HomePartyNoWineCount")] HomePartyNoWineCount = 437,
    /// <summary>
    /// 家宴邀请玩家不存在
    /// </summary>
    [pbr::OriginalName("HomePartyInvitePlayerNotExist")] HomePartyInvitePlayerNotExist = 438,
    /// <summary>
    /// 强盗已经死亡
    /// </summary>
    [pbr::OriginalName("HomePartyRobberDied")] HomePartyRobberDied = 439,
    /// <summary>
    /// 家宴吃菜活动结束
    /// </summary>
    [pbr::OriginalName("HomePartyGameEatAlreadyFinish")] HomePartyGameEatAlreadyFinish = 440,
    /// <summary>
    /// 家宴集体气氛值奖励配置错误
    /// </summary>
    [pbr::OriginalName("HomePartyFinishAwardCfgError")] HomePartyFinishAwardCfgError = 441,
    /// <summary>
    /// 家宴游戏错误
    /// </summary>
    [pbr::OriginalName("HomePartyGameError")] HomePartyGameError = 442,
    /// <summary>
    /// 家宴个人气氛值奖励配置错误
    /// </summary>
    [pbr::OriginalName("HomePartyAtmosphereAchieveCfgError")] HomePartyAtmosphereAchieveCfgError = 443,
    /// <summary>
    /// 家宴个人气氛值不足
    /// </summary>
    [pbr::OriginalName("HomePartyAtmosphereNoEnough")] HomePartyAtmosphereNoEnough = 444,
    /// <summary>
    /// 家宴个人气氛值奖励已领取
    /// </summary>
    [pbr::OriginalName("HomePartyAtmosphereAchieveAwardAlreadyGet")] HomePartyAtmosphereAchieveAwardAlreadyGet = 445,
    /// <summary>
    /// 设置预设阵容失败
    /// </summary>
    [pbr::OriginalName("FailedToSetEmbattleIndex")] FailedToSetEmbattleIndex = 446,
    /// <summary>
    /// 没有找到玩家
    /// </summary>
    [pbr::OriginalName("NotFoundPlayerInfo")] NotFoundPlayerInfo = 447,
    /// <summary>
    /// 好友羁绊等级不足
    /// </summary>
    [pbr::OriginalName("FriendJiBanLvNoEnough")] FriendJiBanLvNoEnough = 448,
    /// <summary>
    /// 家宴集体气氛值奖励已领取
    /// </summary>
    [pbr::OriginalName("HomePartyAtmospherAwardAlreadyGet")] HomePartyAtmospherAwardAlreadyGet = 449,
    /// <summary>
    /// 已加入此宴会
    /// </summary>
    [pbr::OriginalName("HomePartyAlreadyJoin")] HomePartyAlreadyJoin = 450,
    /// <summary>
    /// 家宴活动结束
    /// </summary>
    [pbr::OriginalName("HomePartyAlreadyFinish")] HomePartyAlreadyFinish = 451,
    /// <summary>
    /// 公会妖兽难度未通关
    /// </summary>
    [pbr::OriginalName("GuildBossGroupNotPass")] GuildBossGroupNotPass = 452,
    /// <summary>
    /// 公会妖兽难度配置错误
    /// </summary>
    [pbr::OriginalName("GuildBossGroupCfgError")] GuildBossGroupCfgError = 453,
    /// <summary>
    ///代消未完成
    /// </summary>
    [pbr::OriginalName("DaiXiaoNotFinish")] DaiXiaoNotFinish = 454,
    /// <summary>
    ///代消已经失效
    /// </summary>
    [pbr::OriginalName("DaiXiaoNotInvalid")] DaiXiaoNotInvalid = 455,
    /// <summary>
    /// 家宴宾客数量超出最大数量
    /// </summary>
    [pbr::OriginalName("HomePartyGuestOverMax")] HomePartyGuestOverMax = 456,
    /// <summary>
    /// 家宴主宾客数量超出最大数量
    /// </summary>
    [pbr::OriginalName("HomePartyMainGuestOverMax")] HomePartyMainGuestOverMax = 457,
    /// <summary>
    ///领取战令奖励章节配置不存在
    /// </summary>
    [pbr::OriginalName("ZhangLingCfgNotExist")] ZhangLingCfgNotExist = 458,
    /// <summary>
    ///战令未解锁
    /// </summary>
    [pbr::OriginalName("ZhangLingNotUnlock")] ZhangLingNotUnlock = 459,
    /// <summary>
    ///已经领取过
    /// </summary>
    [pbr::OriginalName("ZhangLingAlreadyGet")] ZhangLingAlreadyGet = 460,
    /// <summary>
    ///账号平台绑定奖励已经领取过
    /// </summary>
    [pbr::OriginalName("AccountBindRewardGetAlready")] AccountBindRewardGetAlready = 461,
    /// <summary>
    ///账号平台绑定奖励领取失败
    /// </summary>
    [pbr::OriginalName("AccountBindRewardGetFail")] AccountBindRewardGetFail = 462,
    /// <summary>
    /// 上古遗迹无效的关卡
    /// </summary>
    [pbr::OriginalName("ShangGuYiJiInvalidLevelID")] ShangGuYiJiInvalidLevelId = 463,
    /// <summary>
    /// 上古遗迹快捷奖励次数不足
    /// </summary>
    [pbr::OriginalName("ShangGuShortcutNotEnough")] ShangGuShortcutNotEnough = 464,
    /// <summary>
    /// 支付订单错误
    /// </summary>
    [pbr::OriginalName("RechargeOrderError")] RechargeOrderError = 465,
    /// <summary>
    ///战斗录像已经过期
    /// </summary>
    [pbr::OriginalName("BattleVideoExpire")] BattleVideoExpire = 466,
    /// <summary>
    ///任务未完成
    /// </summary>
    [pbr::OriginalName("QuestNotFinished")] QuestNotFinished = 467,
    /// <summary>
    ///全服战令购买次数未达标
    /// </summary>
    [pbr::OriginalName("ZhangLingPayCountNotEnough")] ZhangLingPayCountNotEnough = 468,
    /// <summary>
    ///战令购买条件不符合
    /// </summary>
    [pbr::OriginalName("ZhangLingPayCheckError")] ZhangLingPayCheckError = 469,
    /// <summary>
    ///战令未付款
    /// </summary>
    [pbr::OriginalName("ZhangLingNotPay")] ZhangLingNotPay = 470,
    /// <summary>
    ///印记已经装备
    /// </summary>
    [pbr::OriginalName("AlreadyEquipStamp")] AlreadyEquipStamp = 471,
    /// <summary>
    ///印记锁住了
    /// </summary>
    [pbr::OriginalName("StampLock")] StampLock = 472,
    /// <summary>
    ///月卡过期 
    /// </summary>
    [pbr::OriginalName("YueKaOutOfTime")] YueKaOutOfTime = 473,
    /// <summary>
    ///当日月卡已经领取过
    /// </summary>
    [pbr::OriginalName("YueKaRewardAlreadyGet")] YueKaRewardAlreadyGet = 474,
    /// <summary>
    ///月卡购买条件不符合
    /// </summary>
    [pbr::OriginalName("YueKaPayCheckError")] YueKaPayCheckError = 475,
    /// <summary>
    ///月卡未购买 领取奖励失败
    /// </summary>
    [pbr::OriginalName("YueKaNotBuy")] YueKaNotBuy = 476,
    /// <summary>
    ///爬塔每日挑战次数用完
    /// </summary>
    [pbr::OriginalName("ClimbTowerNoTimes")] ClimbTowerNoTimes = 477,
    /// <summary>
    ///家园农场槽位错误
    /// </summary>
    [pbr::OriginalName("HomeFarmPosError")] HomeFarmPosError = 478,
    /// <summary>
    ///家园农场种田已完成
    /// </summary>
    [pbr::OriginalName("HomeFarmAlreadyComplete")] HomeFarmAlreadyComplete = 479,
    /// <summary>
    ///家园农场种田未完成
    /// </summary>
    [pbr::OriginalName("HomeFarmNotComplete")] HomeFarmNotComplete = 480,
    /// <summary>
    /// 好友农田外派位置已经被别人占领
    /// </summary>
    [pbr::OriginalName("HomeFarmPosAlreadyUsed")] HomeFarmPosAlreadyUsed = 481,
    /// <summary>
    /// 每个好友家只能派遣一个幻灵，请到其他好友农田中继续
    /// </summary>
    [pbr::OriginalName("HomeFarmOneFriendHeroOverMax")] HomeFarmOneFriendHeroOverMax = 482,
    /// <summary>
    ///家园农场槽位没有幻灵在种田
    /// </summary>
    [pbr::OriginalName("HomeFarmPosNoHero")] HomeFarmPosNoHero = 483,
    /// <summary>
    ///支付金额不足不能祈福
    /// </summary>
    [pbr::OriginalName("QiFuPayCountNotEnough")] QiFuPayCountNotEnough = 484,
    /// <summary>
    ///当日祈福次数用完
    /// </summary>
    [pbr::OriginalName("QiFuNoTimes")] QiFuNoTimes = 485,
    /// <summary>
    ///每日优惠奖励 今日已经领取过
    /// </summary>
    [pbr::OriginalName("DailyDealRewardAlreadyGet")] DailyDealRewardAlreadyGet = 486,
    /// <summary>
    ///每日特惠购买条件不符合
    /// </summary>
    [pbr::OriginalName("DailyDealPayCheckError")] DailyDealPayCheckError = 487,
    /// <summary>
    ///周礼包支付失败
    /// </summary>
    [pbr::OriginalName("WeekGiftPackagePayCheckError")] WeekGiftPackagePayCheckError = 488,
    /// <summary>
    ///每日礼包支付失败
    /// </summary>
    [pbr::OriginalName("DayGiftPackagePayCheckError")] DayGiftPackagePayCheckError = 489,
    /// <summary>
    ///每周购买上限
    /// </summary>
    [pbr::OriginalName("RechargeWeekLimit")] RechargeWeekLimit = 490,
    /// <summary>
    ///每日购买上限
    /// </summary>
    [pbr::OriginalName("RechargeDayLimit")] RechargeDayLimit = 491,
    /// <summary>
    ///该七日奖励已经领取过
    /// </summary>
    [pbr::OriginalName("SevenDayRewardAlreadyGet")] SevenDayRewardAlreadyGet = 492,
    /// <summary>
    ///未达成 不可领取
    /// </summary>
    [pbr::OriginalName("SevenDayRewardNotReached")] SevenDayRewardNotReached = 493,
    /// <summary>
    ///永久购买上限
    /// </summary>
    [pbr::OriginalName("RechargeLiveLimit")] RechargeLiveLimit = 494,
    /// <summary>
    /// 玩家未充值过
    /// </summary>
    [pbr::OriginalName("PlayerNoRechargeCount")] PlayerNoRechargeCount = 495,
    /// <summary>
    /// 首充奖励已领取
    /// </summary>
    [pbr::OriginalName("FirstRechargeAwardAlreadyGet")] FirstRechargeAwardAlreadyGet = 496,
    /// <summary>
    /// 领取天下觉灵奖励失败 没有足够的觉灵值
    /// </summary>
    [pbr::OriginalName("GetStarAwakenFailNotEnoughPoint")] GetStarAwakenFailNotEnoughPoint = 497,
    /// <summary>
    /// 购买觉灵奖励失败  需要物品不足
    /// </summary>
    [pbr::OriginalName("GetStarAwakenFailNotEnoughItem")] GetStarAwakenFailNotEnoughItem = 498,
    /// <summary>
    ///推送礼包支付失败
    /// </summary>
    [pbr::OriginalName("PickGiftRechargeError")] PickGiftRechargeError = 499,
    /// <summary>
    ///没有推送礼包
    /// </summary>
    [pbr::OriginalName("PickGiftPackageNotHave")] PickGiftPackageNotHave = 500,
    /// <summary>
    ///称号激活失败 没有获得
    /// </summary>
    [pbr::OriginalName("TitleActiveFailNotGet")] TitleActiveFailNotGet = 501,
    /// <summary>
    ///称号激活失败 没有在配置表中找到ID
    /// </summary>
    [pbr::OriginalName("TitleActiveFailNoID")] TitleActiveFailNoId = 502,
    /// <summary>
    ///称号装备失败 没有激活
    /// </summary>
    [pbr::OriginalName("TitleEquipFailNotActive")] TitleEquipFailNotActive = 503,
    /// <summary>
    ///营地不能升级
    /// </summary>
    [pbr::OriginalName("CampLevelCanotUp")] CampLevelCanotUp = 504,
    /// <summary>
    ///没有邀请次数
    /// </summary>
    [pbr::OriginalName("HomeFarmInviteNoCount")] HomeFarmInviteNoCount = 505,
    /// <summary>
    ///1000抽失败 条件不符合
    /// </summary>
    [pbr::OriginalName("ThousandDrawCardUnLock")] ThousandDrawCardUnLock = 506,
    /// <summary>
    ///1000抽失败 无效的INDEX
    /// </summary>
    [pbr::OriginalName("ThousandDrawCardNoIndex")] ThousandDrawCardNoIndex = 507,
    /// <summary>
    /// 未拥有此头像
    /// </summary>
    [pbr::OriginalName("NoHasThisHeadIcon")] NoHasThisHeadIcon = 508,
    /// <summary>
    ///未拥有此头像框
    /// </summary>
    [pbr::OriginalName("NoHasThisHeadIconFrame")] NoHasThisHeadIconFrame = 509,
    /// <summary>
    ///VIP等级未达到
    /// </summary>
    [pbr::OriginalName("VIPLevelNotReach")] ViplevelNotReach = 510,
    /// <summary>
    ///VIP等级奖励已经领取过
    /// </summary>
    [pbr::OriginalName("VIPAwardAlreadyGet")] VipawardAlreadyGet = 511,
    /// <summary>
    ///下载包奖励已经领取过
    /// </summary>
    [pbr::OriginalName("DownloadAwardAlreadyGet")] DownloadAwardAlreadyGet = 512,
    /// <summary>
    ///家园农场没有幻灵在种田
    /// </summary>
    [pbr::OriginalName("HomeFarmNoHeroWork")] HomeFarmNoHeroWork = 513,
    /// <summary>
    ///每日体力已经领取过
    /// </summary>
    [pbr::OriginalName("DailyPhysicalAlreadyGet")] DailyPhysicalAlreadyGet = 514,
    /// <summary>
    ///累计充值活动配置错误
    /// </summary>
    [pbr::OriginalName("RechargeTotalMomenyCfgError")] RechargeTotalMomenyCfgError = 515,
    /// <summary>
    ///累计充值奖励已领取
    /// </summary>
    [pbr::OriginalName("RechargeTotalMomenyAwardAlreadyGet")] RechargeTotalMomenyAwardAlreadyGet = 516,
    /// <summary>
    ///累计充值不足
    /// </summary>
    [pbr::OriginalName("RechargeTotalMomenyNoEnough")] RechargeTotalMomenyNoEnough = 517,
    /// <summary>
    /// 幻灵任务未完成
    /// </summary>
    [pbr::OriginalName("HeroQuestNotAllFinished")] HeroQuestNotAllFinished = 518,
    /// <summary>
    /// 幻灵任务奖励已领取
    /// </summary>
    [pbr::OriginalName("HeroQuestAwardAlreadyGet")] HeroQuestAwardAlreadyGet = 519,
    /// <summary>
    ///累计充值活动未开启
    /// </summary>
    [pbr::OriginalName("RechargeTotalMomenyNotExist")] RechargeTotalMomenyNotExist = 520,
    /// <summary>
    ///招财进宝达到最大次数
    /// </summary>
    [pbr::OriginalName("RollMoneyTreeMaxTimes")] RollMoneyTreeMaxTimes = 521,
    /// <summary>
    ///招财进宝次数奖励已经领取
    /// </summary>
    [pbr::OriginalName("RollMoneyTreeAwardAlready")] RollMoneyTreeAwardAlready = 522,
    /// <summary>
    ///破冰奖励已经领取
    /// </summary>
    [pbr::OriginalName("PoBingAwardAlreadyGet")] PoBingAwardAlreadyGet = 523,
    /// <summary>
    ///装备精炼失败 品质不符合
    /// </summary>
    [pbr::OriginalName("FXEquipRefineFailQuality")] FxequipRefineFailQuality = 524,
    /// <summary>
    ///匹配对手失败
    /// </summary>
    [pbr::OriginalName("FailedMatchOpponent")] FailedMatchOpponent = 525,
    /// <summary>
    /// 任务奖励已领取
    /// </summary>
    [pbr::OriginalName("QuestAwardAleadyGet")] QuestAwardAleadyGet = 526,
    /// <summary>
    /// 公会发展章节任务未完成
    /// </summary>
    [pbr::OriginalName("GuildDevelopChapterNotFinish")] GuildDevelopChapterNotFinish = 527,
    /// <summary>
    /// 公会发展章节奖励已领取
    /// </summary>
    [pbr::OriginalName("GuildDevelopChapterAwardAleadyGet")] GuildDevelopChapterAwardAleadyGet = 528,
    /// <summary>
    ///学社镇守膜拜没有次数
    /// </summary>
    [pbr::OriginalName("GuildGuardWorshipNoTimes")] GuildGuardWorshipNoTimes = 529,
    /// <summary>
    /// </summary>
    [pbr::OriginalName("ZINTERSTOREErr")] Zinterstoreerr = 530,
    /// <summary>
    ///协助副本选择的三消数据的玩家ID不对
    /// </summary>
    [pbr::OriginalName("AssistSanXiaoPlayerIDWrong")] AssistSanXiaoPlayerIdwrong = 531,
    /// <summary>
    ///先设置心愿再抽卡
    /// </summary>
    [pbr::OriginalName("MingGeDrawCardNoXinYuan")] MingGeDrawCardNoXinYuan = 532,
    /// <summary>
    ///匹配赛段位奖励领取失败
    /// </summary>
    [pbr::OriginalName("FailedToWorldMatchSeasonScoreAward")] FailedToWorldMatchSeasonScoreAward = 533,
    /// <summary>
    /// </summary>
    [pbr::OriginalName("YMPDrawCardNoXinYuan")] YmpdrawCardNoXinYuan = 534,
    /// <summary>
    /// 相片不存在
    /// </summary>
    [pbr::OriginalName("PhotoNotExist")] PhotoNotExist = 535,
    /// <summary>
    /// 相片数量超出上限
    /// </summary>
    [pbr::OriginalName("PhotoOverMaxCount")] PhotoOverMaxCount = 536,
    /// <summary>
    /// 没有相片点赞次数
    /// </summary>
    [pbr::OriginalName("PhotoLikeNoCount")] PhotoLikeNoCount = 537,
    /// <summary>
    /// 相片地址为空
    /// </summary>
    [pbr::OriginalName("PhotoURLEmpty")] PhotoUrlempty = 538,
    /// <summary>
    /// 相册位置已上传相片
    /// </summary>
    [pbr::OriginalName("PhotoPosAlreadyExist")] PhotoPosAlreadyExist = 539,
    /// <summary>
    ///请求幻灵战略失败 没有heroid
    /// </summary>
    [pbr::OriginalName("StrategyFailNoHeroID")] StrategyFailNoHeroId = 540,
    /// <summary>
    ///系统三消错误
    /// </summary>
    [pbr::OriginalName("SysSanXiaoErr")] SysSanXiaoErr = 541,
    /// <summary>
    /// 等级奖励已领取
    /// </summary>
    [pbr::OriginalName("LevelAwardAleadyGet")] LevelAwardAleadyGet = 542,
    /// <summary>
    /// 等级奖励不存在
    /// </summary>
    [pbr::OriginalName("LevelAwardNoExist")] LevelAwardNoExist = 543,
    /// <summary>
    /// 密卷合成消耗配置错误
    /// </summary>
    [pbr::OriginalName("ComposeItemCostCfgError")] ComposeItemCostCfgError = 544,
    /// <summary>
    /// 代金券不足
    /// </summary>
    [pbr::OriginalName("VoucherItemNoEnough")] VoucherItemNoEnough = 545,
    /// <summary>
    ///手牌配置不存在
    /// </summary>
    [pbr::OriginalName("HandCardCfgNotExist")] HandCardCfgNotExist = 546,
    /// <summary>
    ///手牌位孔配置不存在
    /// </summary>
    [pbr::OriginalName("HandCardPositionCfgNotExist")] HandCardPositionCfgNotExist = 547,
    /// <summary>
    ///位孔未解锁
    /// </summary>
    [pbr::OriginalName("HandCardPositionNotUnLocked")] HandCardPositionNotUnLocked = 548,
    /// <summary>
    ///装备手牌类型错误
    /// </summary>
    [pbr::OriginalName("HandCardTypeLimit")] HandCardTypeLimit = 549,
    /// <summary>
    ///此位孔无英雄
    /// </summary>
    [pbr::OriginalName("HandCardPositionNotHaveHero")] HandCardPositionNotHaveHero = 550,
    /// <summary>
    ///手牌已达最高等级
    /// </summary>
    [pbr::OriginalName("HandCardAlreadyAtTheHighestLevel")] HandCardAlreadyAtTheHighestLevel = 560,
    /// <summary>
    ///手牌合成数量不够
    /// </summary>
    [pbr::OriginalName("HandCardUpLevelNotEnough")] HandCardUpLevelNotEnough = 561,
    /// <summary>
    ///当前位孔无手牌
    /// </summary>
    [pbr::OriginalName("HandCardCurPositionNotHC")] HandCardCurPositionNotHc = 562,
    /// <summary>
    ///手牌不存在
    /// </summary>
    [pbr::OriginalName("HandCardNotExist")] HandCardNotExist = 563,
    /// <summary>
    ///敏感字
    /// </summary>
    [pbr::OriginalName("SensitiveWords")] SensitiveWords = 1000,
  }

  #endregion

}

#endregion Designer generated code
