

using System.Collections.Generic;
public enum NetMsgID {
    C2G_Login = 100 ,
    C2G_HeartBeat = 101 ,
    C2G_CreatePlayer = 102 ,
    C2G_PlayerLogin = 103 ,
    C2G_CreatePVEBattle = 104 ,
    C2G_GMRequest = 105 ,
    C2G_UPStarsReq = 106 ,
    C2G_FaXiangLvUpReq = 107 ,
    C2G_EquipAnyReq = 108 ,
    C2G_UnequipAnyReq = 109 ,
    C2G_FXEquipSlotLvUpReq = 110 ,
    C2G_EquipGemReq = 111 ,
    C2G_UnequipGemReq = 112 ,
    C2G_GemLvUPReq = 113 ,
    C2G_DrawTenReq = 115 ,
    C2G_DrawOneReq = 116 ,
    C2G_BattleReport = 117 ,
    C2G_ActiveAtlasReq = 118 ,
    C2G_ActiveFetterReq = 119 ,
    C2G_LockEquipmentReq = 120 ,
    C2G_DrawCardChestReq = 123 ,
    C2G_EmbattleReq = 124 ,
    C2G_SaveEmbattleInfoReq = 125 ,
    C2G_SummonHeroReq = 127 ,
    C2G_GetChapterBoxReq = 128 ,
    C2G_PVEFloorReq = 129 ,
    C2G_SkillLvUpReq = 130 ,
    C2G_GetLevelBoxReq = 131 ,
    C2G_HeroQualityUp = 133 ,
    C2G_GetMailItemReq = 135 ,
    C2G_QuitLevelReq = 136 ,
    C2G_UseItemReq = 137 ,
    C2G_EquipStampReq = 138 ,
    C2G_UnequipStampReq = 139 ,
    C2G_StampUpStarsReq = 140 ,
    C2G_FXEquipOneKeyLvUp = 141 ,
    C2G_KaiTianPaiUpStarsReq = 142 ,
    C2G_EquipKTReq = 143 ,
    C2G_SellItemToSysReq = 144 ,
    C2G_RefreshKTPShopReq = 145 ,
    C2G_BuyKaiTianPaiReq = 147 ,
    C2G_UnequipKTReq = 148 ,
    C2G_SaveSanXiaoReq = 149 ,
    C2G_GetClimbTowerBoxReq = 150 ,
    C2G_LockKTPShopReq = 151 ,
    C2G_PVESanXiaoRankReq = 158 ,
    C2G_EquipGodWeaponReq = 159 ,
    C2G_UnequipGodWeaponReq = 160 ,
    C2G_GodWeaponLvUpReq = 161 ,
    C2G_GodWeaponResetReq = 162 ,
    C2G_GetFriendSysReq = 164 ,
    C2G_ArenaChallengeList = 165 ,
    C2G_GetBattleVideoReq = 166 ,
    C2G_ArenaRankListReq = 167 ,
    C2G_ResolveItemReq = 168 ,
    C2G_EnterSanXiaoReq = 169 ,
    C2G_ReconnectReq = 170 ,
    C2G_ReadMailReq = 171 ,
    C2G_RemoveMailReq = 172 ,
    C2G_GetGeneralStoreReq = 173 ,
    C2G_BuyGeneralStoreReq = 174 ,
    C2G_HistoryBattleReport = 175 ,
    C2G_GetQuestAwardReq = 177 ,
    C2G_FloorArenaReq = 178 ,
    C2G_CreateGuildReq = 179 ,
    C2G_GuildGetInfoReq = 180 ,
    C2G_GuildModifyNameReq = 181 ,
    C2G_GuildModifyIconReq = 182 ,
    C2G_GuildModifyIntroduceReq = 183 ,
    C2G_GuildTransferReq = 184 ,
    C2G_GuildDisbandReq = 185 ,
    C2G_GuildCancelDisbandReq = 186 ,
    C2G_GuildApplyListReq = 187 ,
    C2G_GuildApplyReq = 188 ,
    C2G_GuildApplyAgreeReq = 189 ,
    C2G_GuildApplyRefuseReq = 190 ,
    C2G_GuildLeaveReq = 191 ,
    C2G_GuildKickReq = 192 ,
    C2G_GuildAppointReq = 193 ,
    C2G_GuildRelieveReq = 194 ,
    C2G_GuildCheckSettingReq = 195 ,
    C2G_GuildBroadcastMailReq = 196 ,
    C2G_GuildInviteReq = 197 ,
    C2G_GuildInviteAgreeReq = 198 ,
    C2G_GuildInviteRefuseReq = 199 ,
    C2G_GuildInviteListReq = 200 ,
    C2G_GuildRecommendReq = 201 ,
    C2G_GuildBuildingUpReq = 202 ,
    C2G_GuildMemberListReq = 203 ,
    C2G_GuildBuildingListReq = 204 ,
    C2G_GuildMsgListReq = 205 ,
    C2G_GuildBossQuickBattleReq = 206 ,
    C2G_GuildBossQuickBattleCancelReq = 207 ,
    C2G_GetDailyActiveValueReward = 208 ,
    C2G_GetNormalQuestGroupReward = 209 ,
    C2G_GetLZChapterReward = 210 ,
    C2G_GetRankListReq = 211 ,
    C2G_GetExpeditionReq = 213 ,
    C2G_GetExpeditionLevelReq = 214 ,
    C2G_ExpeditionClientStateReq = 215 ,
    C2G_ExpeditionGetRewardReq = 216 ,
    C2G_FindFriendReq = 217 ,
    C2G_ApplyForFriendReq = 218 ,
    C2G_AgreeFriendReq = 219 ,
    C2G_DisagreeFriendReq = 220 ,
    C2G_BlockFriendReq = 221 ,
    C2G_RecommendFriendReq = 222 ,
    C2G_ChatMsgReq = 224 ,
    C2G_GetTrialInfoReq = 225 ,
    C2G_TrialResetReq = 226 ,
    C2G_TrialFormationSaveReq = 227 ,
    C2G_TrialViewBattleReq = 228 ,
    C2G_TrialGetBattleInfoReq = 229 ,
    C2G_TrialTakeAwardReq = 230 ,
    C2G_InviteHelpSanXiaoReq = 231 ,
    C2G_BattleLevelReport = 232 ,
    C2G_ReadSanXiaoRevInfo = 238 ,
    C2G_SaveBeginnerGuidance = 239 ,
    C2G_ActivatePlayerAttrReq = 242 ,
    C2G_GetTowerDailyAward = 243 ,
    C2G_LvUpPlayerSkillReq = 244 ,
    C2G_CurrencyBuyPowerReq = 245 ,
    C2G_RefreshRandStoreReq = 246 ,
    C2G_UseWanNengChipReq = 249 ,
    C2G_FaXiangOneLvUpReq = 253 ,
    C2G_FaXiangFiveLvUpReq = 254 ,
    C2G_FactionSetReq = 255 ,
    C2G_GetChatRoomMsgReq = 256 ,
    C2G_UpdatePlayerSkillReq = 257 ,
    C2G_FaXiangGradeUpReq = 258 ,
    C2G_SignInReq = 259 ,
    C2G_GetAccumulatedSignInReq = 260 ,
    C2G_GuildDonateReq = 261 ,
    C2G_GuildModifyNoticeReq = 262 ,
    C2G_GuildAuthoritySaveReq = 263 ,
    C2G_GuildAuctionGetReq = 264 ,
    C2G_GuildAuctionBidReq = 265 ,
    C2G_GuildSkillUpReq = 266 ,
    C2G_GuildPublishQuestReq = 267 ,
    C2G_GuildGetBossInfoReq = 268 ,
    C2G_GuildSearchByNameReq = 269 ,
    C2G_GuildGetAuthorityInfoReq = 270 ,
    C2G_GuildGetBasicInfoReq = 271 ,
    C2G_AcceptAssistReq = 272 ,
    C2G_QuitAssistLevelReq = 273 ,
    C2G_AssistInfoReq = 274 ,
    C2G_AssistSweepReq = 275 ,
    C2G_AssistHelpSaveEmbattleInfoReq = 276 ,
    C2G_EnterAssistLevelReq = 278 ,
    C2G_InviteAssistReq = 279 ,
    C2G_GetXiXunInfoReq = 280 ,
    C2G_XiXunDianZanReq = 281 ,
    C2G_DeleteFriendReq = 282 ,
    C2G_RefreshArenaOppoent = 283 ,
    C2G_BuyArenaChallengeCount = 284 ,
    C2G_RechargeOrderReq = 285 ,
    C2G_ChangeGoodFriendRedPoint = 286 ,
    C2G_TowerDirectRewardReq = 287 ,
    C2G_BuyChoukaTimesReq = 289 ,
    C2G_OneKeyGetQuestAwardReq = 290 ,
    C2G_XingJunRewardReq = 292 ,
    C2G_ServerDataReq = 293 ,
    C2G_GetRingInfoReq = 294 ,
    C2G_RefreshRingOppoentReq = 295 ,
    C2G_GetRingTopThreeReq = 296 ,
    C2G_GetSanXiaoBaoDianInfoReq = 297 ,
    C2G_GetSanXiaoBaoDianLevelInfoReq = 298 ,
    C2G_GetSanXiaoBaoDianStatisticsInfoReq = 299 ,
    C2G_GetFBMailReq = 300 ,
    C2G_GetRingMainInfoReq = 311 ,
    C2G_ChangePlayerNameReq = 312 ,
    C2G_GetLoginSevenAwardReq = 313 ,
    C2G_GetCodeRewardReq = 314 ,
    C2G_RefreshBookReq = 315 ,
    C2G_RemoveBookReq = 316 ,
    C2G_LvUpPlayerSkillBookReq = 317 ,
    C2G_RefreshBookConfirmReq = 318 ,
    C2G_EquipBookReq = 319 ,
    C2G_CampPosUnlockReq = 320 ,
    C2G_CampPlaceHerokReq = 321 ,
    C2G_CampRemoveHerokReq = 322 ,
    C2G_UseKTSkillTabReq = 323 ,
    C2G_UnlockKaiTianTabIndexReq = 325 ,
    C2G_ChangeKaiTianPaiTabNameReq = 327 ,
    C2G_UnequipAllKTReq = 328 ,
    C2G_SwapKaiTianPaiReq = 329 ,
    C2G_SwapKTSkillIndexReq = 330 ,
    C2G_EquipKTSkillIndexReq = 331 ,
    C2G_UnequipKTSkillIndexReq = 332 ,
    C2G_HeroAwakeReq = 333 ,
    C2G_HeroPotentialReq = 334 ,
    C2G_HeroPotentialAttrReq = 335 ,
    C2G_PotentialAttrClearReq = 336 ,
    C2G_KangMieLvUpSaveReq = 337 ,
    C2G_KangMieLvClearReq = 338 ,
    C2G_HomeBuildingUpReq = 341 ,
    C2G_BuyItemInHomeStore = 342 ,
    C2G_HomeOrnamentPlaceReq = 343 ,
    C2G_HomeOrnamentPlaceRemoveReq = 344 ,
    C2G_HomeHeroPlaceReq = 345 ,
    C2G_HomeHeroPlaceRemoveReq = 346 ,
    C2G_HomeHeroInfoReq = 347 ,
    C2G_HomeHeroStoryFinishReq = 348 ,
    C2G_HomeVisitCourtyardReq = 349 ,
    C2G_HomeHotelQuestFinishReq = 350 ,
    C2G_GetHomeQuestAwardReq = 351 ,
    C2G_HomeRegionUnlockReq = 352 ,
    C2G_HomeQuestFinishReq = 353 ,
    C2G_GetHomeQuestProgressAward = 354 ,
    C2G_HomeBuildingSaveReq = 355 ,
    C2G_HomeHotelHeroPlaceReq = 356 ,
    C2G_HomeHotelHeroPlaceRemoveReq = 357 ,
    C2G_HomeAdventureGetReq = 358 ,
    C2G_HomeAdventureFinishReq = 359 ,
    C2G_HomeLogGetReq = 360 ,
    C2G_HomeCourtyardGetInfoReq = 361 ,
    C2G_HomeFarmGetInfoReq = 362 ,
    C2G_HomeFarmPlaceHeroReq = 363 ,
    C2G_HomeFarmPlaceFriendHeroReq = 364 ,
    C2G_HomeFarmCancelPlaceHeroReq = 365 ,
    C2G_HomeFarmTakeAwardReq = 366 ,
    C2G_HomeVistorJoinReq = 367 ,
    C2G_HomePartySubscribeReq = 368 ,
    C2G_HomePartyOpenReq = 369 ,
    C2G_HomePartyJoinReq = 371 ,
    C2G_HomePartySceneStateReq = 372 ,
    C2G_HomePartyGiftReq = 373 ,
    C2G_HomePartyMoveReq = 374 ,
    C2G_HomePartyDanceReq = 375 ,
    C2G_HomePartyScatterSugarReq = 376 ,
    C2G_HomePartyGetSugarReq = 377 ,
    C2G_HomePartyBuyFireworkReq = 378 ,
    C2G_HomePartyUseFireworkReq = 379 ,
    C2G_HomePartyPlaceFireworkReq = 380 ,
    C2G_HomePartyDanceReplayReq = 381 ,
    C2G_HomePartyEatDishReq = 382 ,
    C2G_HomePartyPlayerAction = 383 ,
    C2G_HomePartyMakeWineReq = 384 ,
    C2G_HomePartyGuessNumberReq = 385 ,
    C2G_HomePartyGetAwardReq = 386 ,
    C2G_HomePartyPlayerAtmosphereAwardReq = 387 ,
    C2G_HomePartyRejoinReq = 388 ,
    C2G_HomePartyPlayerCountReq = 389 ,
    C2G_HomePartyCelebrationOpenReq = 390 ,
    C2G_GuardBossPlayReportReq = 393 ,
    C2G_GuardBossWaitingQueueReq = 395 ,
    C2G_GuardBossBattleReportReq = 396 ,
    C2G_GetBossBoxReq = 398 ,
    C2G_GuardBossSanXiaoInfoReq = 400 ,
    C2G_JoinGuardBossReq = 401 ,
    C2G_GuardBossInspireReq = 402 ,
    C2G_GuardBossReviveReq = 403 ,
    C2G_GetBossDamageRankListReq = 404 ,
    C2G_GuildBossTakeAwardReq = 405 ,
    C2G_GuildBossBuyBattleCountReq = 406 ,
    C2G_GuildSyncInfoReq = 407 ,
    C2G_GuildAuctionPlayerRecordReq = 408 ,
    C2G_GuildRecruitReq = 409 ,
    C2G_OneKeyUnequipGemReq = 410 ,
    C2G_GuardRankReq = 411 ,
    C2G_GuardInfoReq = 412 ,
    C2G_SetTargetGuardReq = 413 ,
    C2G_GuardEventReq = 414 ,
    C2G_ExpeditionSaveElfListReq = 415 ,
    C2G_ExpeditionCreateBattleReq = 416 ,
    C2G_SetXinYuanCardReq = 417 ,
    C2G_SetEmbattlePlayerSkillReq = 418 ,
    C2G_ExpeditionGetPlayerInfoReq = 419 ,
    C2G_GuildBuildingUpAccReq = 420 ,
    C2G_GuildMsgInvestigateReq = 421 ,
    C2G_GuildGetAuctionBonusReq = 422 ,
    C2G_ViewEmbattleReq = 423 ,
    C2G_GetAccountBindRewardReq = 424 ,
    C2G_GetZhanlingPayCountAwardReq = 425 ,
    C2G_GetYueKaRewardReq = 426 ,
    C2G_GetSevenDayRewardReq = 427 ,
    G2C_Login = 500 ,
    G2C_HeartBeat = 501 ,
    G2C_CreatePlayer = 502 ,
    G2C_PlayerLogin = 503 ,
    G2C_UPStarsRes = 504 ,
    G2C_FaXiangLvUpRes = 505 ,
    G2C_EquipAnyRes = 506 ,
    G2C_UnequipAnyRes = 507 ,
    G2C_FXEquipSlotLvUpRes = 508 ,
    G2C_EquipGemRes = 509 ,
    G2C_UnequipGemRes = 510 ,
    G2C_GemLvUPRes = 511 ,
    G2C_DrawTenRes = 513 ,
    G2C_DrawOneRes = 514 ,
    G2C_BattleOver = 515 ,
    G2C_EnterPVEBattle = 516 ,
    G2C_ActiveAtlasRes = 517 ,
    G2C_ActiveFetterRes = 518 ,
    G2C_LockEquipmentRes = 519 ,
    G2C_GetBagInfoRes = 520 ,
    G2C_UpdatePlayerAttrRes = 526 ,
    G2C_UpdateHeroBagRes = 527 ,
    G2C_DrawCardChestRes = 529 ,
    G2C_GMResponse = 530 ,
    G2C_EmbattleRes = 531 ,
    G2C_SaveEmbattleInfoRes = 532 ,
    G2C_SummonHeroRes = 534 ,
    G2C_GetChapterBoxRes = 535 ,
    G2C_PVEFloorRes = 536 ,
    G2C_SkillLvUpRes = 537 ,
    G2C_GetLevelBoxRes = 538 ,
    G2C_UpdatePVELevelInfo = 539 ,
    G2C_HeroQualityUp = 540 ,
    G2C_GetAllMailRes = 541 ,
    G2C_GetMailItemRes = 542 ,
    G2C_QuitLevelRes = 543 ,
    G2C_UpdateFaXiangInfo = 544 ,
    G2C_UseItemRes = 545 ,
    G2C_EquipStampRes = 546 ,
    G2C_UnequipStampRes = 547 ,
    G2C_StampUpStarsRes = 548 ,
    G2C_FXEquipOneKeyLvUp = 549 ,
    G2C_KaiTianPaiUpStarsRes = 550 ,
    G2C_EquipKTRes = 551 ,
    G2C_SellItemToSysRes = 552 ,
    G2C_RefreshKTPShopRes = 553 ,
    G2C_GetKaiTianShopRes = 554 ,
    G2C_BuyKaiTianPaiRes = 555 ,
    G2C_UnequipKTRes = 556 ,
    G2C_SaveSanXiaoRes = 557 ,
    G2C_GetClimbTowerBoxRes = 558 ,
    G2C_LockKTPShopRes = 559 ,
    G2C_UpdateClimbTowerInfoRes = 560 ,
    G2C_SyncAllEmbattleRes = 562 ,
    G2C_PVESanXiaoRankRes = 564 ,
    G2C_SyncHandbookInfo = 565 ,
    G2C_EquipGodWeaponRes = 566 ,
    G2C_UnequipGodWeaponRes = 567 ,
    G2C_GodWeaponLvUpRes = 568 ,
    G2C_GodWeaponResetRes = 569 ,
    G2C_GetFriendSysRes = 570 ,
    G2C_ArenaChallengeList = 571 ,
    G2C_GetBattleVideoRes = 572 ,
    G2C_ArenaRankListRes = 573 ,
    G2C_BattleReport = 574 ,
    G2C_ResolveItemRes = 575 ,
    G2C_EnterSanXiaoRes = 576 ,
    G2C_ReconnectRes = 577 ,
    G2C_ReadMailRes = 578 ,
    G2C_RemoveMailRes = 579 ,
    G2C_GetGeneralStoreRes = 580 ,
    G2C_BuyGeneralStoreRes = 581 ,
    G2C_HistoryBattleReport = 582 ,
    G2C_GetQuestAwardRes = 584 ,
    G2C_FloorArenaRes = 585 ,
    G2C_CreateGuildRes = 586 ,
    G2C_GuildGetInfoRes = 587 ,
    G2C_GuildModifyNameRes = 588 ,
    G2C_GuildModifyIconRes = 589 ,
    G2C_GuildModifyIntroduceRes = 590 ,
    G2C_GuildTransferRes = 591 ,
    G2C_GuildDisbandRes = 592 ,
    G2C_GuildCancelDisbandRes = 593 ,
    G2C_GuildApplyRes = 594 ,
    G2C_GuildApplyListRes = 595 ,
    G2C_GuildApplyAgreeRes = 596 ,
    G2C_GuildApplyRefuseRes = 597 ,
    G2C_GuildLeaveRes = 598 ,
    G2C_GuildKickRes = 599 ,
    G2C_GuildAppointRes = 600 ,
    G2C_GuildRelieveRes = 601 ,
    G2C_GuildCheckSettingRes = 602 ,
    G2C_GuildBroadcastMailRes = 603 ,
    G2C_GuildInviteRes = 604 ,
    G2C_GuildInviteAgreeRes = 605 ,
    G2C_GuildInviteRefuseRes = 606 ,
    G2C_GuildInviteListRes = 607 ,
    G2C_GuildRecommendRes = 608 ,
    G2C_GuildBuildingUpRes = 609 ,
    G2C_GuildMemberListRes = 610 ,
    G2C_GuildBuildingListRes = 611 ,
    G2C_GuildMsgListRes = 612 ,
    G2C_SyncDayTimesInfoRes = 613 ,
    G2C_GetDailyActiveValueReward = 615 ,
    G2C_GetNormalQuestGroupReward = 616 ,
    G2C_SyncLieZhuanInfoRes = 617 ,
    G2C_GetLZChapterReward = 618 ,
    G2C_GetRankListRes = 619 ,
    G2C_SyncGeneralStoreInfo = 620 ,
    G2C_GetExpeditionRes = 622 ,
    G2C_GetExpeditionLevelRes = 623 ,
    G2C_ExpeditionClientStateRes = 624 ,
    G2C_ExpeditionGetRewardRes = 625 ,
    G2C_FindFriendRes = 626 ,
    G2C_ApplyForFriendRes = 627 ,
    G2C_AgreeFriendRes = 628 ,
    G2C_DisagreeFriendRes = 629 ,
    G2C_BlockFriendRes = 630 ,
    G2C_RecommendFriendRes = 631 ,
    G2C_ChatMsgRes = 632 ,
    G2C_GetTrialInfoRes = 633 ,
    G2C_TrialResetRes = 634 ,
    G2C_TrialFormationSaveRes = 635 ,
    G2C_TrialViewBattleRes = 636 ,
    G2C_TrialGetBattleInfoRes = 637 ,
    G2C_TrialTakeAwardRes = 638 ,
    G2C_OfflineNTfRes = 639 ,
    G2C_InviteHelpSanXiaoRes = 640 ,
    G2C_UpdateDaiXiaoInfo = 641 ,
    G2C_BattleLevelReport = 642 ,
    G2C_ReadSanXiaoRevInfo = 645 ,
    G2C_SaveBeginnerGuidance = 646 ,
    G2C_PlayerDataSyncFinish = 647 ,
    G2C_ActivatePlayerAttrRes = 650 ,
    G2C_UpdatePlayerSkills = 651 ,
    G2C_GetTowerDailyAward = 652 ,
    G2C_LvUpPlayerSkillRes = 653 ,
    G2C_GuildDonateRes = 654 ,
    G2C_GuildModifyNoticeRes = 655 ,
    G2C_GuildAuthoritySaveRes = 656 ,
    G2C_RefreshRandStoreRes = 657 ,
    G2C_CurrencyBuyPowerRes = 659 ,
    G2C_UseWanNengChipRes = 661 ,
    G2C_ChatMsgNotice = 662 ,
    G2C_FaXiangOneLvUpRes = 667 ,
    G2C_FaXiangFiveLvUpRes = 668 ,
    G2C_FactionSetRes = 669 ,
    G2C_SyncAchievementInfoRes = 670 ,
    G2C_SyncNormalQuestInfoRes = 671 ,
    G2C_SyncDailyQuestInfoRes = 672 ,
    G2C_GetChatRoomMsgRes = 673 ,
    G2C_UpdateSomeHeroBagRes = 674 ,
    G2C_UpdatePlayerSkillRes = 675 ,
    G2C_FaXiangGradeUpRes = 676 ,
    G2C_SignInRes = 677 ,
    G2C_UpdateSignInViewInfoRes = 678 ,
    G2C_GetAccumulatedSignInRes = 679 ,
    G2C_InviteAssistRes = 680 ,
    G2C_InviteAssist = 681 ,
    G2C_AcceptAssistRes = 682 ,
    G2C_PlayerAcceptAssist = 684 ,
    G2C_AssistInfoRes = 685 ,
    G2C_QuitAssistLevelRes = 686 ,
    G2C_QuitAssistLevelNotify = 687 ,
    G2C_AssistSweepRes = 688 ,
    G2C_AssistHelpSaveEmbattleInfoRes = 689 ,
    G2C_AssistNotifyEmbattle = 690 ,
    G2C_EnterAssistLevelRes = 691 ,
    G2C_AssistMapStateNotify = 692 ,
    G2C_SyncAssistLevelInfo = 693 ,
    G2C_GuildAuctionGetRes = 694 ,
    G2C_GuildAuctionBidRes = 695 ,
    G2C_GuildSkillUpRes = 696 ,
    G2C_GuildGetBossInfoRes = 697 ,
    G2C_GuildPublishQuestRes = 698 ,
    G2C_GuildSearchByNameRes = 699 ,
    G2C_GuildGetAuthorityInfoRes = 700 ,
    G2C_GuildGetBasicInfoRes = 701 ,
    G2C_GetXiXunInfoRes = 702 ,
    G2C_XiXunDianZanRes = 703 ,
    G2C_DeleteFriendRes = 704 ,
    G2C_RefreshArenaOppoent = 705 ,
    G2C_BuyArenaChallengeCount = 706 ,
    G2C_RechargeOrderRes = 707 ,
    G2C_SyncGuildQuestInfoRes = 708 ,
    G2C_ChangeGoodFriendRedPoint = 709 ,
    G2C_TowerDirectRewardRes = 711 ,
    G2C_GuildSyncInfoRes = 712 ,
    G2C_RechargeGetInfoRes = 713 ,
    G2C_RechargeCompleteRes = 714 ,
    G2C_BuyChoukaTimesRes = 715 ,
    G2C_OneKeyGetQuestAwardRes = 716 ,
    G2C_GetXingJunRes = 718 ,
    G2C_XingJunRewardRes = 719 ,
    G2C_ServerDataRes = 720 ,
    G2C_SyncServerData = 721 ,
    G2C_GetRingInfoRes = 722 ,
    G2C_ActivityNotice = 723 ,
    G2C_RefreshRingOppoentRes = 724 ,
    G2C_GetRingMainInfoRes = 725 ,
    G2C_GetRingTopThreeRes = 726 ,
    G2C_GetSanXiaoBaoDianInfoRes = 727 ,
    G2C_GetSanXiaoBaoDianLevelInfoRes = 728 ,
    G2C_GetSanXiaoBaoDianStatisticsInfoRes = 729 ,
    G2C_GetFBMailRes = 730 ,
    G2C_SyncSanXiaoAchievementInfoRes = 731 ,
    G2C_ChangePlayerNameRes = 732 ,
    G2C_GetLoginSevenAwardRes = 733 ,
    G2C_UpdateLoginSevenAwardInfo = 734 ,
    G2C_GetCodeRewardRes = 735 ,
    G2C_RemoveBookRes = 736 ,
    G2C_LvUpPlayerSkillBookRes = 737 ,
    G2C_RefreshBookConfirmRes = 738 ,
    G2C_EquipBookRes = 739 ,
    G2C_SyncPlayerBookData = 740 ,
    G2C_RefreshBookRes = 741 ,
    G2C_SyncCampInfoRes = 742 ,
    G2C_CampPosUnlockRes = 743 ,
    G2C_CampPlaceHeroRes = 744 ,
    G2C_UseKTSkillTabRes = 745 ,
    G2C_GetKaiTianTabInfoRes = 746 ,
    G2C_UnlockKaiTianTabIndexRes = 747 ,
    G2C_UpdateDesentLevelInfo = 748 ,
    G2C_ChangeKaiTianPaiTabNameRes = 750 ,
    G2C_UnequipAllKTRes = 751 ,
    G2C_SwapKaiTianPaiRes = 752 ,
    G2C_SwapKTSkillIndexRes = 753 ,
    G2C_EquipKTSkillIndexRes = 754 ,
    G2C_UnequipKTSkillIndexRes = 755 ,
    G2C_CampRemoveHeroRes = 756 ,
    G2C_HeroAwakeRes = 757 ,
    G2C_HeroPotentialRes = 758 ,
    G2C_KangMieLvUpSaveRes = 759 ,
    G2C_KangMieLvClearRes = 760 ,
    G2C_HeroPotentialAttrRes = 761 ,
    G2C_PotentialAttrClearRes = 762 ,
    G2C_SyncKangMieInfoRes = 763 ,
    G2C_GuildBossQuickBattleRes = 764 ,
    G2C_GuildBossQuickBattleCancelRes = 765 ,
    G2C_GuildBossTakeAwardRes = 766 ,
    G2C_SyncGuildPlayerInfo = 767 ,
    G2C_SyncGuildBossBattleResultRes = 768 ,
    G2C_GuildBossBuyBattleCountRes = 769 ,
    G2C_GuildAuctionPlayerRecordRes = 770 ,
    G2C_GuildSyncMemberStateRes = 771 ,
    G2C_GuildRecruitRes = 772 ,
    G2C_SyncGuildBossQuestInfoRes = 773 ,
    G2C_HomeGetInfoRes = 780 ,
    G2C_HomeBuildingUpRes = 781 ,
    G2C_BuyItemInHomeStore = 782 ,
    G2C_HomeOrnamentPlaceRes = 783 ,
    G2C_HomeOrnamentPlaceRemoveRes = 784 ,
    G2C_HomeHeroPlaceRes = 785 ,
    G2C_HomeHeroPlaceRemoveRes = 786 ,
    G2C_HomeHeroInfoRes = 787 ,
    G2C_HomeHeroStoryFinishRes = 788 ,
    G2C_HomeVisitCourtyardRes = 789 ,
    G2C_SyncHomeHotelQuestInfoRes = 790 ,
    G2C_GetHomeQuestAwardRes = 791 ,
    G2C_HomeRegionUnlockRes = 792 ,
    G2C_HomeQuestFinishRes = 793 ,
    G2C_GetHomeQuestProgressAward = 794 ,
    G2C_HomeBuildingSaveRes = 795 ,
    G2C_HomeHotelHeroPlaceRes = 797 ,
    G2C_HomeHotelHeroPlaceRemoveRes = 798 ,
    G2C_HomeAdventureGetRes = 799 ,
    G2C_HomeAdventureFinishRes = 800 ,
    G2C_HomeLogGetRes = 801 ,
    G2C_HomeCourtyardGetInfoRes = 802 ,
    G2C_HomeFarmGetInfoRes = 803 ,
    G2C_HomeFarmPlaceHeroRes = 804 ,
    G2C_HomeFarmPlaceFriendHeroRes = 805 ,
    G2C_HomeFarmCancelPlaceHeroRes = 806 ,
    G2C_HomeFarmTakeAwardRes = 807 ,
    G2C_HomeVistorJoinRes = 808 ,
    G2C_SyncHomeInfoRes = 809 ,
    G2C_HomeHotelQuestFinishRes = 810 ,
    G2C_HomePartySubscribeRes = 811 ,
    G2C_HomePartyOpenRes = 812 ,
    G2C_HomePartyGetListRes = 813 ,
    G2C_SyncHomePartyItemRes = 814 ,
    G2C_HomePartyJoinRes = 815 ,
    G2C_HomePartySceneStateRes = 816 ,
    G2C_HomePartyGiftRes = 817 ,
    G2C_SyncHomePartyInfoRes = 818 ,
    G2C_HomePartyMoveRes = 819 ,
    G2C_HomePartyDanceRes = 820 ,
    G2C_HomePartyScatterSugarRes = 821 ,
    G2C_HomePartyGetSugarRes = 822 ,
    G2C_HomePartyRemoveSugarRes = 823 ,
    G2C_HomePartyMakeWineRes = 824 ,
    G2C_HomePartyBuyFireworkRes = 825 ,
    G2C_HomePartyUseFireworkRes = 826 ,
    G2C_HomePartyPlaceFireworkRes = 827 ,
    G2C_HomePartyDanceReplayRes = 828 ,
    G2C_HomePartyEatDishRes = 830 ,
    G2C_HomePartyPlayerAction = 831 ,
    G2C_SyncHomePartyPlayerJoin = 832 ,
    G2C_UpdateHomePartyInfoRes = 833 ,
    G2C_SyncHomePartyDanceBeInvited = 834 ,
    G2C_SyncHomePartyDanceReplay = 835 ,
    G2C_SyncHomePartyGame = 836 ,
    G2C_HomePartyEatDishFinishRes = 837 ,
    G2C_HomePartyShowGift = 838 ,
    G2C_HomePartyMakeWineFinishRes = 839 ,
    G2C_MainUIRedPoint = 840 ,
    G2C_OneKeyUnequipGemRes = 841 ,
    G2C_SyncGuildGuardInfo = 842 ,
    G2C_GuardRankRes = 843 ,
    G2C_GuardInfoRes = 844 ,
    G2C_SetTargetGuardRes = 845 ,
    G2C_GuardventRes = 846 ,
    G2C_PaoMaDengRes = 847 ,
    G2C_SetXinYuanCardRes = 848 ,
    G2C_SetEmbattlePlayerSkillRes = 849 ,
    G2C_UpdateDrawCardInfo = 850 ,
    G2C_SyncPVPTypeSanXiaoInfo = 851 ,
    G2C_PVPTypeSanXiaoEmbattleIndex = 852 ,
    G2C_DescentLevelPlot = 854 ,
    G2C_GetDescentLevelReward = 855 ,
    G2C_ExpeditionGetPlayerInfoRes = 856 ,
    G2C_GuardBossInspireRes = 857 ,
    G2C_GuardBossReviveRes = 858 ,
    G2C_GuildBuildingUpAccRes = 859 ,
    G2C_GuildMsgInvestigateRes = 860 ,
    G2C_GuardAttackMy = 861 ,
    G2C_JoinGuardBossRes = 862 ,
    G2C_SyncGuardBossBasicInfo = 863 ,
    G2C_GuardBossEnd = 864 ,
    G2C_ExpeditionSaveElfListRes = 865 ,
    G2C_ExpeditionCreateBattleRes = 866 ,
    G2C_GetBossDamageRankListRes = 867 ,
    G2C_GetBossBoxRes = 868 ,
    G2C_GuardBossBattleReportRes = 869 ,
    G2C_GuildGetAuctionBonusRes = 870 ,
    G2C_GetSevenTimerQuestRes = 871 ,
    G2C_GuardBossPlayReportRes = 872 ,
    G2C_GetFourteenQuestRes = 880 ,
    G2C_GetFourteenTimerQuestRes = 881 ,
    G2C_GetBuySevenSaleItemRes = 882 ,
    G2C_GetBuyFourteenSaleItemRes = 883 ,
    G2C_GetFourteenActivityItemRes = 884 ,
    G2C_GetSevenActivityItemRes = 885 ,
    G2C_GuardBossSanXiaoRes = 886 ,
    G2C_GuardAttackQueue = 887 ,
    G2C_GetSevenQuestRes = 888 ,
    G2C_SyncSevenFourtheenInfo = 889 ,
    G2C_GuardBossWaitingQueueRes = 890 ,
    G2C_SendFriendPointRes = 891 ,
    G2C_RevFriendPointRes = 892 ,
    G2C_HomePartyRobberDiedRes = 893 ,
    G2C_EnterRobberBattleRes = 894 ,
    G2C_HomePartyGuessNumberRes = 895 ,
    G2C_HomePartyGuessNumberAnswerAwardRes = 896 ,
    G2C_HomePartyGuessNumberPrepareRes = 897 ,
    G2C_HomePartyGuessNumberUpdateRes = 898 ,
    G2C_HomePartyGuessNumberFinishRes = 899 ,
    G2C_HomePartyGetAwardRes = 900 ,
    G2C_HomePartyPlayerAtmosphereAwardRes = 901 ,
    G2C_OneKeyUPStarsRes = 902 ,
    G2C_PlayerSummaryInfoRes = 903 ,
    G2C_FinishQuestRes = 904 ,
    G2C_HomePartyRejoinRes = 905 ,
    G2C_PlayerDataReconnectSyncFinish = 906 ,
    G2C_UseDaiXiaoDataRes = 907 ,
    G2C_HomePartyPlayerCountRes = 909 ,
    G2C_ViewEmbattleRes = 910 ,
    G2C_GuildAuctionCollectionRes = 911 ,
    G2C_SummonGodWeaponRes = 912 ,
    G2C_CreateShortcutBattle = 913 ,
    G2C_SyncZhanLingInfo = 914 ,
    G2C_GetZhanLingRewardRes = 915 ,
    G2C_SyncShangGuInfo = 916 ,
    G2C_GetShangGuTimerAward = 917 ,
    G2C_GetAccountBindRewardRes = 918 ,
    G2C_GetShangGuShortcutAward = 919 ,
    G2C_RechargeOrderCancelRes = 920 ,
    G2C_GetFightPowerVideo = 921 ,
    G2C_GetRankQuestInfoRes = 922 ,
    G2C_GetRankQuestByIDRes = 923 ,
    G2C_GetRankQuestAwardRes = 924 ,
    G2C_SyncRankQuestInfoRes = 925 ,
    G2C_SummonLingGenRes = 926 ,
    G2C_SyncZhanlingPayCount = 927 ,
    G2C_GetZhanlingPayCountAwardRes = 928 ,
    G2C_LockStampRes = 929 ,
    G2C_GetSanXiaoBaoDianLevelListRes = 930 ,
    G2C_GetSanXiaoBaoDianShowMedalRes = 931 ,
    G2C_SyncSanXiaoStatisticsQuestInfoRes = 932 ,
    G2C_ShangGuInfoViewRes = 933 ,
    G2C_GetYueKaRewardRes = 934 ,
    G2C_SyncYueKaInfo = 935 ,
    G2C_HomePartyCelebrationOpenRes = 936 ,
    G2C_HomeVistorSceneStateRes = 937 ,
    G2C_HomeFarmInviteRes = 938 ,
    G2C_ClickChatButtonRes = 939 ,
    G2C_UseHeroSkinRes = 940 ,
    G2C_UsePlayerSkinRes = 941 ,
    G2C_SyncHeroSkinList = 942 ,
    G2C_SyncPlayerSkinList = 943 ,
    G2C_SyncQiFuInfo = 944 ,
    G2C_QiFuRes = 945 ,
    G2C_HomeFarmFriendTakeAwardRes = 946 ,
    G2C_HomeVistorUpdateHomeInfoRes = 947 ,
    G2C_HomeFarmActivateCropsRes = 948 ,
    G2C_EnterSomePVEBattle = 949 ,
    G2C_SyncDailyDealInfo = 950 ,
    G2C_UpdateMainPlayerHeadIcon = 951 ,
    G2C_GetDailyDealRewardRes = 952 ,
    G2C_SyncWeekGiftPackage = 953 ,
    G2C_SyncDayGiftPackage = 954 ,
    G2C_GetSevenDayRewardRes = 955 ,
    G2C_SyncPlayerSevenDayInfo = 956 ,
    G2C_SyncAllPickGiftPackage = 957 ,
    G2C_HomeFarmFriendWorkCountRes = 958 ,
    G2C_RechargeGetFirstAwardRes = 959 ,
    G2C_RechargeUpdateInfoRes = 960 ,
    G2C_SyncRechargeGetFirstAwardRes = 961 ,
    G2C_SyncStarAwakenQuestInfo = 962 ,
    G2C_DelDaiXiaoRevRes = 963 ,
    G2C_GetStarAwakenRewardRes = 964 ,
    G2C_ActivePickGiftPackageRes = 965 ,
    G2C_PayZeroMoneyRes = 966 ,
    G2C_ActivePlayerTitleRes = 967 ,
    G2C_EquipPlayerTitleRes = 968 ,
    G2C_SyncPlayerTitleInfo = 969 ,
    G2C_CampLevelUpRes = 970 ,
    G2C_SyncThousandDrawCardInfo = 971 ,
    G2C_ThousandDrawCardRes = 972 ,
    G2C_ThousandCardGetRes = 973 ,
    G2C_SyncStarAwakenInfo = 974 ,
    G2C_SetPlayerHeadIconRes = 975 ,
    G2C_SetPlayerHeadFrameIconRes = 976 ,
    G2C_GetPlayerBasicInfoRes = 977 ,
    G2C_SyncPlayerSapceInfoRes = 978 ,
    G2C_UpdatePlayerSapceInfoRes = 979 ,
    G2C_ClearHeadIconNewRes = 980 ,
    G2C_GetVIPRewardRes = 981 ,
    G2C_SyncVIPRewardInfo = 982 ,
    G2C_GetDownloadRewardRes = 983 ,
    G2C_GetRechargeItemListRes = 984 ,
    G2C_GetDailyPhysicalRes = 985 ,
    G2C_SyncDailyPhysicalInfo = 986 ,
    G2C_SyncHeroQuestInfoRes = 987 ,
    G2C_DaiXiaoHistoryInfoRes = 988 ,
    G2C_SyncBusinessActivityListRes = 989 ,
    G2C_UpdateBusinessActivityInfoRes = 990 ,
    G2C_BusinessActivityGetInfoByTypRes = 991 ,
    G2C_SyncRechargeTotalMoneyActivityInfoRes = 992 ,
    G2C_RechargeTotalMoneyGetAwardRes = 993 ,
    G2C_GetHeroQuestAwardRes = 994 ,
    G2C_ViewEmbattleHeroInfoRes = 995 ,
    G2C_AssistStartLevelRes = 996 ,
    G2C_AssistStartLevelNotify = 997 ,
    G2C_SyncPlayerDisplayInfo = 998 ,
    C2G_PVPTypeSanXiaoEmbattleIndex = 1000 ,
    C2G_DescentLevelPlot = 1002 ,
    C2G_GetDescentLevelReward = 1003 ,
    C2G_GetSevenQuestReq = 1005 ,
    C2G_GetSevenTimerQuestReq = 1006 ,
    C2G_GetFourteenQuestReq = 1007 ,
    C2G_GetFourteenTimerQuestReq = 1008 ,
    C2G_GetBuySevenSaleItemReq = 1009 ,
    C2G_GetBuyFourteenSaleItemReq = 1010 ,
    C2G_GetFourteenActivityItemReq = 1011 ,
    C2G_GetSevenActivityItemReq = 1012 ,
    C2G_SendFriendPointReq = 1013 ,
    C2G_RevFriendPointReq = 1014 ,
    C2G_EnterRobberBattleReq = 1015 ,
    C2G_OneKeyUPStarsReq = 1016 ,
    C2G_PlayerSummaryInfoReq = 1017 ,
    C2G_FinishQuestReq = 1018 ,
    C2G_UseDaiXiaoDataReq = 1019 ,
    C2G_GuildAuctionCollectionReq = 1020 ,
    C2G_SummonGodWeaponReq = 1021 ,
    C2G_CreateShortcutBattle = 1022 ,
    C2G_GetZhanLingRewardReq = 1023 ,
    C2G_GetShangGuTimerAward = 1024 ,
    C2G_GetShangGuShortcutAward = 1025 ,
    C2G_RechargeOrderCancelReq = 1026 ,
    C2G_GetFightPowerVideo = 1027 ,
    C2G_GetRankQuestByIDReq = 1029 ,
    C2G_GetRankQuestAwardReq = 1030 ,
    C2G_SummonLingGenReq = 1031 ,
    C2G_LockStampReq = 1032 ,
    C2G_GetSanXiaoBaoDianLevelListReq = 1033 ,
    C2G_GetSanXiaoBaoDianShowMedalReq = 1034 ,
    C2G_ShangGuInfoViewReq = 1035 ,
    C2G_HomeVistorSceneStateReq = 1036 ,
    C2G_HomeFarmInviteReq = 1037 ,
    C2G_ClickChatButtonReq = 1038 ,
    C2G_UseHeroSkinReq = 1039 ,
    C2G_UsePlayerSkinReq = 1040 ,
    C2G_QiFuReq = 1041 ,
    C2G_HomeFarmFriendTakeAwardReq = 1042 ,
    C2G_HomeFarmActivateCropsReq = 1043 ,
    C2G_CreateSomePVEBattle = 1044 ,
    G2C_GetDailyDealRewardReq = 1045 ,
    C2G_HomeFarmFriendWorkCountReq = 1046 ,
    C2G_RechargeGetFirstAwardReq = 1047 ,
    C2G_GetStarAwakenRewardReq = 1048 ,
    C2G_DelDaiXiaoRevReq = 1049 ,
    C2G_ActivePickGiftPackageReq = 1050 ,
    C2G_PayZeroMoneyReq = 1051 ,
    C2G_EquipPlayerTitleReq = 1052 ,
    C2G_ActivePlayerTitleReq = 1053 ,
    C2G_CampLevelUpReq = 1054 ,
    C2G_ThousandDrawCardReq = 1055 ,
    C2G_ThousandCardGetReq = 1056 ,
    C2G_SetPlayerHeadIconReq = 1057 ,
    C2G_SetPlayerHeadFrameIconReq = 1058 ,
    C2G_GetPlayerBasicInfoReq = 1059 ,
    C2G_ClearHeadIconNewReq = 1060 ,
    C2G_GetVIPRewardReq = 1061 ,
    C2G_GetDownloadRewardReq = 1062 ,
    C2G_GetRechargeItemListReq = 1063 ,
    C2G_GetDailyPhysicalReq = 1064 ,
    C2G_DaiXiaoHistoryInfoReq = 1065 ,
    C2G_BusinessActivityGetInfoByTypeReq = 1066 ,
    C2G_RechargeTotalMoneyGetAwardReq = 1067 ,
    C2G_GetHeroQuestAwardReq = 1068 ,
    C2G_ViewEmbattleHeroInfoReq = 1069 ,
    C2G_AssistStartLevelReq = 1070 ,
    C2G_RollMoneyTreeReq = 1071 ,
    C2G_RollMoneyTreeTenReq = 1072 ,
    C2G_GetRollMoneyTreeAwardReq = 1073 ,
    C2G_GetPoBingAwardReq = 1074 ,
    C2G_AssistQuitEmbattleReq = 1075 ,
    C2G_FXEquipRefineLvUpReq = 1076 ,
    C2G_WorldMatchOpponentReq = 1077 ,
    C2G_GuildGuardWorshipReq = 1078 ,
    C2G_GetGuildDevelopChapterAwardReq = 1079 ,
    C2G_GetGuildDevelopQuestAwardReq = 1080 ,
    C2G_SetPlayerLabelReq = 1081 ,
    C2G_SetPlayerMoodReq = 1082 ,
    C2G_SetPlayerSpaceVisitorActionReq = 1083 ,
    C2G_GetPlayerSpaceVisitorInfoReq = 1084 ,
    C2G_SetMingGeWishReq = 1085 ,
    C2G_MingGeDrawOneCardReq = 1086 ,
    C2G_AssistBattlePlayerInfoReq = 1087 ,
    C2G_AssistChoseSanXiaoPlayerReq = 1088 ,
    C2G_GetWorldMatchSeasonScoreAward = 1089 ,
    C2G_MingGeDrawTenCardReq = 1090 ,
    C2G_SendGiftToPlayerReq = 1091 ,
    C2G_SetYMPWishReq = 1092 ,
    C2G_YMPDrawOneCardReq = 1093 ,
    C2G_YMPDrawTenCardReq = 1094 ,
    C2G_PlayerGiftSysReadReq = 1095 ,
    C2G_PlayerGiftSysZuiJinReq = 1096 ,
    C2G_GetPlayerSpacePhotoInfoReq = 1097 ,
    C2G_SetPlayerSpacePhotoReq = 1098 ,
    C2G_SetPlayerSpacePhotoLikeReq = 1099 ,
    C2G_DeletePlayerSpacePhotoReq = 1100 ,
    C2G_SetPlayerCustomHeadIconReq = 1101 ,
    C2G_ActiveGodWeaponAtlasReq = 1102 ,
    C2G_GetWorldMatchPlayerInfoReq = 1103 ,
    C2G_HeroStrategyReq = 1104 ,
    C2G_WorldMatchPlayerBeBeatenReq = 1105 ,
    C2G_WorldMatchPlayerBeBeatenNtfReq = 1106 ,
    C2G_GetPlayerLvAwardReq = 1107 ,
    C2G_ComposeItemReq = 1108 ,
    G2C_GuardBossSanXiaoBattle = 2001 ,
    G2C_NewBossBoxNotify = 2002 ,
    G2C_DeleteBossBoxNotify = 2003 ,
    G2C_RollMoneyTreeRes = 2004 ,
    G2C_RollMoneyTreeTenRes = 2005 ,
    G2C_SyncMoneyTreeData = 2006 ,
    G2C_GetRollMoneyTreeAwardRes = 2007 ,
    G2C_SyncPoBingInfo = 2008 ,
    G2C_GetPoBingAwardRes = 2009 ,
    G2C_AssistQuitEmbattleNotify = 2010 ,
    G2C_FXEquipRefineLvUpRes = 2011 ,
    G2C_WorldMatchOpponentRes = 2012 ,
    G2C_GuildGuardWorshipRes = 2013 ,
    G2C_GetGuildDevelopChapterAwardRes = 2014 ,
    G2C_GetGuildDevelopQuestAwardRes = 2015 ,
    G2C_SetPlayerLabelRes = 2016 ,
    G2C_SetPlayerMoodRes = 2017 ,
    G2C_SetPlayerSpaceVisitorActionRes = 2018 ,
    G2C_GetPlayerSpaceVisitorInfoRes = 2019 ,
    G2C_SetMingGeWishRes = 2020 ,
    G2C_MingGeDrawOneCardRes = 2021 ,
    G2C_SyncMingGeDrawCardInfo = 2022 ,
    G2C_SyncPeriodActDailyQuestInfoRes = 2023 ,
    G2C_AssistBattlePlayerInfoRes = 2024 ,
    G2C_SyncPeriodActAchieveQuestInfoRes = 2025 ,
    G2C_AssistChoseSanXiaoPlayerRes = 2026 ,
    G2C_AssistChoseSanXiaoPlayerNotify = 2027 ,
    G2C_SyncWorldMatchQuestInfoRes = 2028 ,
    G2C_SyncWorldMatchSeasonScoreQuestInfoRes = 2029 ,
    G2C_GetWorldMatchSeasonScoreAward = 2030 ,
    G2C_SyncFightShanhaiRankQuestInfoRes = 2031 ,
    G2C_MingGeDrawTenCardRes = 2032 ,
    G2C_SendGiftToPlayerRes = 2033 ,
    G2C_SyncPlayerGiftSys = 2034 ,
    G2C_SetYMPWishRes = 2035 ,
    G2C_SyncYMPDrawCardInfo = 2036 ,
    G2C_YMPDrawOneCardRes = 2037 ,
    G2C_YMPDrawTenCardRes = 2038 ,
    G2C_PlayerGiftSysReadRes = 2039 ,
    G2C_PlayerGiftSysZuiJinRes = 2040 ,
    G2C_GetPlayerSpacePhotoInfoRes = 2041 ,
    G2C_SetPlayerSpacePhotoRes = 2042 ,
    G2C_SetPlayerSpacePhotoLikeRes = 2043 ,
    G2C_DeletePlayerSpacePhotoRes = 2044 ,
    G2C_SetPlayerCustomHeadIconRes = 2045 ,
    G2C_SyncGodWeaponHandbookInfo = 2046 ,
    G2C_ActiveGodWeaponAtlasRes = 2047 ,
    G2C_SyncVipAttrRes = 2048 ,
    G2C_NtfGiftToAllPlayerRes = 2049 ,
    G2C_GetWorldMatchPlayerInfoRes = 2050 ,
    G2C_HeroStrategyRes = 2051 ,
    G2C_WorldMatchPlayerBeBeatenRes = 2052 ,
    G2C_WorldMatchPlayerBeBeatenNtfRes = 2053 ,
    G2C_SyncWorldMatchNtfRes = 2054 ,
    G2C_GetPlayerLvAwardRes = 2055 ,
    G2C_SyncPlayerLvAwardRes = 2056 ,
    G2C_ComposeItemRes = 2057 ,
    G2C_SyncFightShanhaiRankPlayerInfoRes = 2058 ,
    G2C_AssistFriendInfoView = 2059 ,

};




public static class MessageDefine {
    public static Dictionary<NetMsgID, NetMsgID> ReqAndRes = new Dictionary<NetMsgID, NetMsgID>(){
     { NetMsgID.C2G_AcceptAssistReq , NetMsgID.G2C_AcceptAssistRes },
     { NetMsgID.C2G_ActivatePlayerAttrReq , NetMsgID.G2C_ActivatePlayerAttrRes },
     { NetMsgID.C2G_ActiveAtlasReq , NetMsgID.G2C_ActiveAtlasRes },
     { NetMsgID.C2G_ActiveFetterReq , NetMsgID.G2C_ActiveFetterRes },
     { NetMsgID.C2G_ActiveGodWeaponAtlasReq , NetMsgID.G2C_ActiveGodWeaponAtlasRes },
     { NetMsgID.C2G_ActivePickGiftPackageReq , NetMsgID.G2C_ActivePickGiftPackageRes },
     { NetMsgID.C2G_ActivePlayerTitleReq , NetMsgID.G2C_ActivePlayerTitleRes },
     { NetMsgID.C2G_AgreeFriendReq , NetMsgID.G2C_AgreeFriendRes },
     { NetMsgID.C2G_ApplyForFriendReq , NetMsgID.G2C_ApplyForFriendRes },
     { NetMsgID.C2G_ArenaChallengeList , NetMsgID.G2C_ArenaChallengeList },
     { NetMsgID.C2G_ArenaRankListReq , NetMsgID.G2C_ArenaRankListRes },
     { NetMsgID.C2G_AssistBattlePlayerInfoReq , NetMsgID.G2C_AssistBattlePlayerInfoRes },
     { NetMsgID.C2G_AssistChoseSanXiaoPlayerReq , NetMsgID.G2C_AssistChoseSanXiaoPlayerRes },
     { NetMsgID.C2G_AssistHelpSaveEmbattleInfoReq , NetMsgID.G2C_AssistHelpSaveEmbattleInfoRes },
     { NetMsgID.C2G_AssistInfoReq , NetMsgID.G2C_AssistInfoRes },
     { NetMsgID.C2G_AssistStartLevelReq , NetMsgID.G2C_AssistStartLevelRes },
     { NetMsgID.C2G_AssistSweepReq , NetMsgID.G2C_AssistSweepRes },
     { NetMsgID.C2G_BattleLevelReport , NetMsgID.G2C_BattleLevelReport },
     { NetMsgID.C2G_BattleReport , NetMsgID.G2C_BattleOver },
     { NetMsgID.C2G_BlockFriendReq , NetMsgID.G2C_BlockFriendRes },
     { NetMsgID.C2G_BusinessActivityGetInfoByTypeReq , NetMsgID.G2C_BusinessActivityGetInfoByTypRes },
     { NetMsgID.C2G_BuyArenaChallengeCount , NetMsgID.G2C_BuyArenaChallengeCount },
     { NetMsgID.C2G_BuyChoukaTimesReq , NetMsgID.G2C_BuyChoukaTimesRes },
     { NetMsgID.C2G_BuyGeneralStoreReq , NetMsgID.G2C_BuyGeneralStoreRes },
     { NetMsgID.C2G_BuyItemInHomeStore , NetMsgID.G2C_BuyItemInHomeStore },
     { NetMsgID.C2G_BuyKaiTianPaiReq , NetMsgID.G2C_BuyKaiTianPaiRes },
     { NetMsgID.C2G_CampLevelUpReq , NetMsgID.G2C_CampLevelUpRes },
     { NetMsgID.C2G_CampPlaceHerokReq , NetMsgID.G2C_CampPlaceHeroRes },
     { NetMsgID.C2G_CampPosUnlockReq , NetMsgID.G2C_CampPosUnlockRes },
     { NetMsgID.C2G_CampRemoveHerokReq , NetMsgID.G2C_CampRemoveHeroRes },
     { NetMsgID.C2G_ChangeGoodFriendRedPoint , NetMsgID.G2C_ChangeGoodFriendRedPoint },
     { NetMsgID.C2G_ChangeKaiTianPaiTabNameReq , NetMsgID.G2C_ChangeKaiTianPaiTabNameRes },
     { NetMsgID.C2G_ChangePlayerNameReq , NetMsgID.G2C_ChangePlayerNameRes },
     { NetMsgID.C2G_ChatMsgReq , NetMsgID.G2C_ChatMsgRes },
     { NetMsgID.C2G_ClearHeadIconNewReq , NetMsgID.G2C_ClearHeadIconNewRes },
     { NetMsgID.C2G_ClickChatButtonReq , NetMsgID.G2C_ClickChatButtonRes },
     { NetMsgID.C2G_ComposeItemReq , NetMsgID.G2C_ComposeItemRes },
     { NetMsgID.C2G_CreateGuildReq , NetMsgID.G2C_CreateGuildRes },
     { NetMsgID.C2G_CreatePVEBattle , NetMsgID.G2C_EnterPVEBattle },
     { NetMsgID.C2G_CreatePlayer , NetMsgID.G2C_CreatePlayer },
     { NetMsgID.C2G_CreateShortcutBattle , NetMsgID.G2C_CreateShortcutBattle },
     { NetMsgID.C2G_CreateSomePVEBattle , NetMsgID.G2C_EnterSomePVEBattle },
     { NetMsgID.C2G_CurrencyBuyPowerReq , NetMsgID.G2C_CurrencyBuyPowerRes },
     { NetMsgID.C2G_DaiXiaoHistoryInfoReq , NetMsgID.G2C_DaiXiaoHistoryInfoRes },
     { NetMsgID.C2G_DelDaiXiaoRevReq , NetMsgID.G2C_DelDaiXiaoRevRes },
     { NetMsgID.C2G_DeleteFriendReq , NetMsgID.G2C_DeleteFriendRes },
     { NetMsgID.C2G_DeletePlayerSpacePhotoReq , NetMsgID.G2C_DeletePlayerSpacePhotoRes },
     { NetMsgID.C2G_DescentLevelPlot , NetMsgID.G2C_DescentLevelPlot },
     { NetMsgID.C2G_DisagreeFriendReq , NetMsgID.G2C_DisagreeFriendRes },
     { NetMsgID.C2G_DrawCardChestReq , NetMsgID.G2C_DrawCardChestRes },
     { NetMsgID.C2G_DrawOneReq , NetMsgID.G2C_DrawOneRes },
     { NetMsgID.C2G_DrawTenReq , NetMsgID.G2C_DrawTenRes },
     { NetMsgID.C2G_EmbattleReq , NetMsgID.G2C_EmbattleRes },
     { NetMsgID.C2G_EnterAssistLevelReq , NetMsgID.G2C_EnterAssistLevelRes },
     { NetMsgID.C2G_EnterRobberBattleReq , NetMsgID.G2C_EnterRobberBattleRes },
     { NetMsgID.C2G_EnterSanXiaoReq , NetMsgID.G2C_EnterSanXiaoRes },
     { NetMsgID.C2G_EquipAnyReq , NetMsgID.G2C_EquipAnyRes },
     { NetMsgID.C2G_EquipBookReq , NetMsgID.G2C_EquipBookRes },
     { NetMsgID.C2G_EquipGemReq , NetMsgID.G2C_EquipGemRes },
     { NetMsgID.C2G_EquipGodWeaponReq , NetMsgID.G2C_EquipGodWeaponRes },
     { NetMsgID.C2G_EquipKTReq , NetMsgID.G2C_EquipKTRes },
     { NetMsgID.C2G_EquipKTSkillIndexReq , NetMsgID.G2C_EquipKTSkillIndexRes },
     { NetMsgID.C2G_EquipPlayerTitleReq , NetMsgID.G2C_EquipPlayerTitleRes },
     { NetMsgID.C2G_EquipStampReq , NetMsgID.G2C_EquipStampRes },
     { NetMsgID.C2G_ExpeditionClientStateReq , NetMsgID.G2C_ExpeditionClientStateRes },
     { NetMsgID.C2G_ExpeditionCreateBattleReq , NetMsgID.G2C_ExpeditionCreateBattleRes },
     { NetMsgID.C2G_ExpeditionGetPlayerInfoReq , NetMsgID.G2C_ExpeditionGetPlayerInfoRes },
     { NetMsgID.C2G_ExpeditionGetRewardReq , NetMsgID.G2C_ExpeditionGetRewardRes },
     { NetMsgID.C2G_ExpeditionSaveElfListReq , NetMsgID.G2C_ExpeditionSaveElfListRes },
     { NetMsgID.C2G_FXEquipOneKeyLvUp , NetMsgID.G2C_FXEquipOneKeyLvUp },
     { NetMsgID.C2G_FXEquipRefineLvUpReq , NetMsgID.G2C_FXEquipRefineLvUpRes },
     { NetMsgID.C2G_FXEquipSlotLvUpReq , NetMsgID.G2C_FXEquipSlotLvUpRes },
     { NetMsgID.C2G_FaXiangFiveLvUpReq , NetMsgID.G2C_FaXiangFiveLvUpRes },
     { NetMsgID.C2G_FaXiangGradeUpReq , NetMsgID.G2C_FaXiangGradeUpRes },
     { NetMsgID.C2G_FaXiangLvUpReq , NetMsgID.G2C_FaXiangLvUpRes },
     { NetMsgID.C2G_FaXiangOneLvUpReq , NetMsgID.G2C_FaXiangOneLvUpRes },
     { NetMsgID.C2G_FactionSetReq , NetMsgID.G2C_FactionSetRes },
     { NetMsgID.C2G_FindFriendReq , NetMsgID.G2C_FindFriendRes },
     { NetMsgID.C2G_FinishQuestReq , NetMsgID.G2C_FinishQuestRes },
     { NetMsgID.C2G_FloorArenaReq , NetMsgID.G2C_FloorArenaRes },
     { NetMsgID.C2G_GMRequest , NetMsgID.G2C_GMResponse },
     { NetMsgID.C2G_GemLvUPReq , NetMsgID.G2C_GemLvUPRes },
     { NetMsgID.C2G_GetAccountBindRewardReq , NetMsgID.G2C_GetAccountBindRewardRes },
     { NetMsgID.C2G_GetAccumulatedSignInReq , NetMsgID.G2C_GetAccumulatedSignInRes },
     { NetMsgID.C2G_GetBattleVideoReq , NetMsgID.G2C_GetBattleVideoRes },
     { NetMsgID.C2G_GetBossBoxReq , NetMsgID.G2C_GetBossBoxRes },
     { NetMsgID.C2G_GetBossDamageRankListReq , NetMsgID.G2C_GetBossDamageRankListRes },
     { NetMsgID.C2G_GetBuyFourteenSaleItemReq , NetMsgID.G2C_GetBuyFourteenSaleItemRes },
     { NetMsgID.C2G_GetBuySevenSaleItemReq , NetMsgID.G2C_GetBuySevenSaleItemRes },
     { NetMsgID.C2G_GetChapterBoxReq , NetMsgID.G2C_GetChapterBoxRes },
     { NetMsgID.C2G_GetChatRoomMsgReq , NetMsgID.G2C_GetChatRoomMsgRes },
     { NetMsgID.C2G_GetClimbTowerBoxReq , NetMsgID.G2C_GetClimbTowerBoxRes },
     { NetMsgID.C2G_GetCodeRewardReq , NetMsgID.G2C_GetCodeRewardRes },
     { NetMsgID.C2G_GetDailyActiveValueReward , NetMsgID.G2C_GetDailyActiveValueReward },
     { NetMsgID.C2G_GetDailyPhysicalReq , NetMsgID.G2C_GetDailyPhysicalRes },
     { NetMsgID.C2G_GetDescentLevelReward , NetMsgID.G2C_GetDescentLevelReward },
     { NetMsgID.C2G_GetDownloadRewardReq , NetMsgID.G2C_GetDownloadRewardRes },
     { NetMsgID.C2G_GetExpeditionLevelReq , NetMsgID.G2C_GetExpeditionLevelRes },
     { NetMsgID.C2G_GetExpeditionReq , NetMsgID.G2C_GetExpeditionRes },
     { NetMsgID.C2G_GetFBMailReq , NetMsgID.G2C_GetFBMailRes },
     { NetMsgID.C2G_GetFightPowerVideo , NetMsgID.G2C_GetFightPowerVideo },
     { NetMsgID.C2G_GetFourteenActivityItemReq , NetMsgID.G2C_GetFourteenActivityItemRes },
     { NetMsgID.C2G_GetFourteenQuestReq , NetMsgID.G2C_GetFourteenQuestRes },
     { NetMsgID.C2G_GetFourteenTimerQuestReq , NetMsgID.G2C_GetFourteenTimerQuestRes },
     { NetMsgID.C2G_GetFriendSysReq , NetMsgID.G2C_GetFriendSysRes },
     { NetMsgID.C2G_GetGeneralStoreReq , NetMsgID.G2C_GetGeneralStoreRes },
     { NetMsgID.C2G_GetGuildDevelopChapterAwardReq , NetMsgID.G2C_GetGuildDevelopChapterAwardRes },
     { NetMsgID.C2G_GetGuildDevelopQuestAwardReq , NetMsgID.G2C_GetGuildDevelopQuestAwardRes },
     { NetMsgID.C2G_GetHeroQuestAwardReq , NetMsgID.G2C_GetHeroQuestAwardRes },
     { NetMsgID.C2G_GetHomeQuestAwardReq , NetMsgID.G2C_GetHomeQuestAwardRes },
     { NetMsgID.C2G_GetHomeQuestProgressAward , NetMsgID.G2C_GetHomeQuestProgressAward },
     { NetMsgID.C2G_GetLZChapterReward , NetMsgID.G2C_GetLZChapterReward },
     { NetMsgID.C2G_GetLevelBoxReq , NetMsgID.G2C_GetLevelBoxRes },
     { NetMsgID.C2G_GetLoginSevenAwardReq , NetMsgID.G2C_GetLoginSevenAwardRes },
     { NetMsgID.C2G_GetMailItemReq , NetMsgID.G2C_GetMailItemRes },
     { NetMsgID.C2G_GetNormalQuestGroupReward , NetMsgID.G2C_GetNormalQuestGroupReward },
     { NetMsgID.C2G_GetPlayerBasicInfoReq , NetMsgID.G2C_GetPlayerBasicInfoRes },
     { NetMsgID.C2G_GetPlayerLvAwardReq , NetMsgID.G2C_GetPlayerLvAwardRes },
     { NetMsgID.C2G_GetPlayerSpacePhotoInfoReq , NetMsgID.G2C_GetPlayerSpacePhotoInfoRes },
     { NetMsgID.C2G_GetPlayerSpaceVisitorInfoReq , NetMsgID.G2C_GetPlayerSpaceVisitorInfoRes },
     { NetMsgID.C2G_GetPoBingAwardReq , NetMsgID.G2C_GetPoBingAwardRes },
     { NetMsgID.C2G_GetQuestAwardReq , NetMsgID.G2C_GetQuestAwardRes },
     { NetMsgID.C2G_GetRankListReq , NetMsgID.G2C_GetRankListRes },
     { NetMsgID.C2G_GetRankQuestAwardReq , NetMsgID.G2C_GetRankQuestAwardRes },
     { NetMsgID.C2G_GetRankQuestByIDReq , NetMsgID.G2C_GetRankQuestByIDRes },
     { NetMsgID.C2G_GetRechargeItemListReq , NetMsgID.G2C_GetRechargeItemListRes },
     { NetMsgID.C2G_GetRingInfoReq , NetMsgID.G2C_GetRingInfoRes },
     { NetMsgID.C2G_GetRingMainInfoReq , NetMsgID.G2C_GetRingMainInfoRes },
     { NetMsgID.C2G_GetRingTopThreeReq , NetMsgID.G2C_GetRingTopThreeRes },
     { NetMsgID.C2G_GetRollMoneyTreeAwardReq , NetMsgID.G2C_GetRollMoneyTreeAwardRes },
     { NetMsgID.C2G_GetSanXiaoBaoDianInfoReq , NetMsgID.G2C_GetSanXiaoBaoDianInfoRes },
     { NetMsgID.C2G_GetSanXiaoBaoDianLevelInfoReq , NetMsgID.G2C_GetSanXiaoBaoDianLevelInfoRes },
     { NetMsgID.C2G_GetSanXiaoBaoDianLevelListReq , NetMsgID.G2C_GetSanXiaoBaoDianLevelListRes },
     { NetMsgID.C2G_GetSanXiaoBaoDianShowMedalReq , NetMsgID.G2C_GetSanXiaoBaoDianShowMedalRes },
     { NetMsgID.C2G_GetSanXiaoBaoDianStatisticsInfoReq , NetMsgID.G2C_GetSanXiaoBaoDianStatisticsInfoRes },
     { NetMsgID.C2G_GetSevenActivityItemReq , NetMsgID.G2C_GetSevenActivityItemRes },
     { NetMsgID.C2G_GetSevenDayRewardReq , NetMsgID.G2C_GetSevenDayRewardRes },
     { NetMsgID.C2G_GetSevenQuestReq , NetMsgID.G2C_GetSevenQuestRes },
     { NetMsgID.C2G_GetSevenTimerQuestReq , NetMsgID.G2C_GetSevenTimerQuestRes },
     { NetMsgID.C2G_GetShangGuShortcutAward , NetMsgID.G2C_GetShangGuShortcutAward },
     { NetMsgID.C2G_GetShangGuTimerAward , NetMsgID.G2C_GetShangGuTimerAward },
     { NetMsgID.C2G_GetStarAwakenRewardReq , NetMsgID.G2C_GetStarAwakenRewardRes },
     { NetMsgID.C2G_GetTowerDailyAward , NetMsgID.G2C_GetTowerDailyAward },
     { NetMsgID.C2G_GetTrialInfoReq , NetMsgID.G2C_GetTrialInfoRes },
     { NetMsgID.C2G_GetVIPRewardReq , NetMsgID.G2C_GetVIPRewardRes },
     { NetMsgID.C2G_GetWorldMatchPlayerInfoReq , NetMsgID.G2C_GetWorldMatchPlayerInfoRes },
     { NetMsgID.C2G_GetWorldMatchSeasonScoreAward , NetMsgID.G2C_GetWorldMatchSeasonScoreAward },
     { NetMsgID.C2G_GetXiXunInfoReq , NetMsgID.G2C_GetXiXunInfoRes },
     { NetMsgID.C2G_GetYueKaRewardReq , NetMsgID.G2C_GetYueKaRewardRes },
     { NetMsgID.C2G_GetZhanLingRewardReq , NetMsgID.G2C_GetZhanLingRewardRes },
     { NetMsgID.C2G_GetZhanlingPayCountAwardReq , NetMsgID.G2C_GetZhanlingPayCountAwardRes },
     { NetMsgID.C2G_GodWeaponLvUpReq , NetMsgID.G2C_GodWeaponLvUpRes },
     { NetMsgID.C2G_GodWeaponResetReq , NetMsgID.G2C_GodWeaponResetRes },
     { NetMsgID.C2G_GuardBossBattleReportReq , NetMsgID.G2C_GuardBossBattleReportRes },
     { NetMsgID.C2G_GuardBossInspireReq , NetMsgID.G2C_GuardBossInspireRes },
     { NetMsgID.C2G_GuardBossPlayReportReq , NetMsgID.G2C_GuardBossPlayReportRes },
     { NetMsgID.C2G_GuardBossReviveReq , NetMsgID.G2C_GuardBossReviveRes },
     { NetMsgID.C2G_GuardBossSanXiaoInfoReq , NetMsgID.G2C_GuardBossSanXiaoRes },
     { NetMsgID.C2G_GuardBossWaitingQueueReq , NetMsgID.G2C_GuardBossWaitingQueueRes },
     { NetMsgID.C2G_GuardEventReq , NetMsgID.G2C_GuardventRes },
     { NetMsgID.C2G_GuardInfoReq , NetMsgID.G2C_GuardInfoRes },
     { NetMsgID.C2G_GuardRankReq , NetMsgID.G2C_GuardRankRes },
     { NetMsgID.C2G_GuildApplyAgreeReq , NetMsgID.G2C_GuildApplyAgreeRes },
     { NetMsgID.C2G_GuildApplyListReq , NetMsgID.G2C_GuildApplyListRes },
     { NetMsgID.C2G_GuildApplyRefuseReq , NetMsgID.G2C_GuildApplyRefuseRes },
     { NetMsgID.C2G_GuildApplyReq , NetMsgID.G2C_GuildApplyRes },
     { NetMsgID.C2G_GuildAppointReq , NetMsgID.G2C_GuildAppointRes },
     { NetMsgID.C2G_GuildAuctionBidReq , NetMsgID.G2C_GuildAuctionBidRes },
     { NetMsgID.C2G_GuildAuctionCollectionReq , NetMsgID.G2C_GuildAuctionCollectionRes },
     { NetMsgID.C2G_GuildAuctionGetReq , NetMsgID.G2C_GuildAuctionGetRes },
     { NetMsgID.C2G_GuildAuctionPlayerRecordReq , NetMsgID.G2C_GuildAuctionPlayerRecordRes },
     { NetMsgID.C2G_GuildAuthoritySaveReq , NetMsgID.G2C_GuildAuthoritySaveRes },
     { NetMsgID.C2G_GuildBossBuyBattleCountReq , NetMsgID.G2C_GuildBossBuyBattleCountRes },
     { NetMsgID.C2G_GuildBossQuickBattleCancelReq , NetMsgID.G2C_GuildBossQuickBattleCancelRes },
     { NetMsgID.C2G_GuildBossQuickBattleReq , NetMsgID.G2C_GuildBossQuickBattleRes },
     { NetMsgID.C2G_GuildBossTakeAwardReq , NetMsgID.G2C_GuildBossTakeAwardRes },
     { NetMsgID.C2G_GuildBroadcastMailReq , NetMsgID.G2C_GuildBroadcastMailRes },
     { NetMsgID.C2G_GuildBuildingListReq , NetMsgID.G2C_GuildBuildingListRes },
     { NetMsgID.C2G_GuildBuildingUpAccReq , NetMsgID.G2C_GuildBuildingUpAccRes },
     { NetMsgID.C2G_GuildBuildingUpReq , NetMsgID.G2C_GuildBuildingUpRes },
     { NetMsgID.C2G_GuildCancelDisbandReq , NetMsgID.G2C_GuildCancelDisbandRes },
     { NetMsgID.C2G_GuildCheckSettingReq , NetMsgID.G2C_GuildCheckSettingRes },
     { NetMsgID.C2G_GuildDisbandReq , NetMsgID.G2C_GuildDisbandRes },
     { NetMsgID.C2G_GuildDonateReq , NetMsgID.G2C_GuildDonateRes },
     { NetMsgID.C2G_GuildGetAuctionBonusReq , NetMsgID.G2C_GuildGetAuctionBonusRes },
     { NetMsgID.C2G_GuildGetAuthorityInfoReq , NetMsgID.G2C_GuildGetAuthorityInfoRes },
     { NetMsgID.C2G_GuildGetBasicInfoReq , NetMsgID.G2C_GuildGetBasicInfoRes },
     { NetMsgID.C2G_GuildGetBossInfoReq , NetMsgID.G2C_GuildGetBossInfoRes },
     { NetMsgID.C2G_GuildGetInfoReq , NetMsgID.G2C_GuildGetInfoRes },
     { NetMsgID.C2G_GuildGuardWorshipReq , NetMsgID.G2C_GuildGuardWorshipRes },
     { NetMsgID.C2G_GuildInviteAgreeReq , NetMsgID.G2C_GuildInviteAgreeRes },
     { NetMsgID.C2G_GuildInviteListReq , NetMsgID.G2C_GuildInviteListRes },
     { NetMsgID.C2G_GuildInviteRefuseReq , NetMsgID.G2C_GuildInviteRefuseRes },
     { NetMsgID.C2G_GuildInviteReq , NetMsgID.G2C_GuildInviteRes },
     { NetMsgID.C2G_GuildKickReq , NetMsgID.G2C_GuildKickRes },
     { NetMsgID.C2G_GuildLeaveReq , NetMsgID.G2C_GuildLeaveRes },
     { NetMsgID.C2G_GuildMemberListReq , NetMsgID.G2C_GuildMemberListRes },
     { NetMsgID.C2G_GuildModifyIconReq , NetMsgID.G2C_GuildModifyIconRes },
     { NetMsgID.C2G_GuildModifyIntroduceReq , NetMsgID.G2C_GuildModifyIntroduceRes },
     { NetMsgID.C2G_GuildModifyNameReq , NetMsgID.G2C_GuildModifyNameRes },
     { NetMsgID.C2G_GuildModifyNoticeReq , NetMsgID.G2C_GuildModifyNoticeRes },
     { NetMsgID.C2G_GuildMsgInvestigateReq , NetMsgID.G2C_GuildMsgInvestigateRes },
     { NetMsgID.C2G_GuildMsgListReq , NetMsgID.G2C_GuildMsgListRes },
     { NetMsgID.C2G_GuildPublishQuestReq , NetMsgID.G2C_GuildPublishQuestRes },
     { NetMsgID.C2G_GuildRecommendReq , NetMsgID.G2C_GuildRecommendRes },
     { NetMsgID.C2G_GuildRecruitReq , NetMsgID.G2C_GuildRecruitRes },
     { NetMsgID.C2G_GuildRelieveReq , NetMsgID.G2C_GuildRelieveRes },
     { NetMsgID.C2G_GuildSearchByNameReq , NetMsgID.G2C_GuildSearchByNameRes },
     { NetMsgID.C2G_GuildSkillUpReq , NetMsgID.G2C_GuildSkillUpRes },
     { NetMsgID.C2G_GuildSyncInfoReq , NetMsgID.G2C_GuildSyncInfoRes },
     { NetMsgID.C2G_GuildTransferReq , NetMsgID.G2C_GuildTransferRes },
     { NetMsgID.C2G_HeroAwakeReq , NetMsgID.G2C_HeroAwakeRes },
     { NetMsgID.C2G_HeroPotentialAttrReq , NetMsgID.G2C_HeroPotentialAttrRes },
     { NetMsgID.C2G_HeroPotentialReq , NetMsgID.G2C_HeroPotentialRes },
     { NetMsgID.C2G_HeroQualityUp , NetMsgID.G2C_HeroQualityUp },
     { NetMsgID.C2G_HeroStrategyReq , NetMsgID.G2C_HeroStrategyRes },
     { NetMsgID.C2G_HistoryBattleReport , NetMsgID.G2C_HistoryBattleReport },
     { NetMsgID.C2G_HomeAdventureFinishReq , NetMsgID.G2C_HomeAdventureFinishRes },
     { NetMsgID.C2G_HomeAdventureGetReq , NetMsgID.G2C_HomeAdventureGetRes },
     { NetMsgID.C2G_HomeBuildingSaveReq , NetMsgID.G2C_HomeBuildingSaveRes },
     { NetMsgID.C2G_HomeBuildingUpReq , NetMsgID.G2C_HomeBuildingUpRes },
     { NetMsgID.C2G_HomeCourtyardGetInfoReq , NetMsgID.G2C_HomeCourtyardGetInfoRes },
     { NetMsgID.C2G_HomeFarmActivateCropsReq , NetMsgID.G2C_HomeFarmActivateCropsRes },
     { NetMsgID.C2G_HomeFarmCancelPlaceHeroReq , NetMsgID.G2C_HomeFarmCancelPlaceHeroRes },
     { NetMsgID.C2G_HomeFarmFriendTakeAwardReq , NetMsgID.G2C_HomeFarmFriendTakeAwardRes },
     { NetMsgID.C2G_HomeFarmFriendWorkCountReq , NetMsgID.G2C_HomeFarmFriendWorkCountRes },
     { NetMsgID.C2G_HomeFarmGetInfoReq , NetMsgID.G2C_HomeFarmGetInfoRes },
     { NetMsgID.C2G_HomeFarmInviteReq , NetMsgID.G2C_HomeFarmInviteRes },
     { NetMsgID.C2G_HomeFarmPlaceFriendHeroReq , NetMsgID.G2C_HomeFarmPlaceFriendHeroRes },
     { NetMsgID.C2G_HomeFarmPlaceHeroReq , NetMsgID.G2C_HomeFarmPlaceHeroRes },
     { NetMsgID.C2G_HomeFarmTakeAwardReq , NetMsgID.G2C_HomeFarmTakeAwardRes },
     { NetMsgID.C2G_HomeHeroInfoReq , NetMsgID.G2C_HomeHeroInfoRes },
     { NetMsgID.C2G_HomeHeroPlaceRemoveReq , NetMsgID.G2C_HomeHeroPlaceRemoveRes },
     { NetMsgID.C2G_HomeHeroPlaceReq , NetMsgID.G2C_HomeHeroPlaceRes },
     { NetMsgID.C2G_HomeHeroStoryFinishReq , NetMsgID.G2C_HomeHeroStoryFinishRes },
     { NetMsgID.C2G_HomeHotelHeroPlaceRemoveReq , NetMsgID.G2C_HomeHotelHeroPlaceRemoveRes },
     { NetMsgID.C2G_HomeHotelHeroPlaceReq , NetMsgID.G2C_HomeHotelHeroPlaceRes },
     { NetMsgID.C2G_HomeHotelQuestFinishReq , NetMsgID.G2C_HomeHotelQuestFinishRes },
     { NetMsgID.C2G_HomeLogGetReq , NetMsgID.G2C_HomeLogGetRes },
     { NetMsgID.C2G_HomeOrnamentPlaceRemoveReq , NetMsgID.G2C_HomeOrnamentPlaceRemoveRes },
     { NetMsgID.C2G_HomeOrnamentPlaceReq , NetMsgID.G2C_HomeOrnamentPlaceRes },
     { NetMsgID.C2G_HomePartyBuyFireworkReq , NetMsgID.G2C_HomePartyBuyFireworkRes },
     { NetMsgID.C2G_HomePartyCelebrationOpenReq , NetMsgID.G2C_HomePartyCelebrationOpenRes },
     { NetMsgID.C2G_HomePartyDanceReplayReq , NetMsgID.G2C_HomePartyDanceReplayRes },
     { NetMsgID.C2G_HomePartyDanceReq , NetMsgID.G2C_HomePartyDanceRes },
     { NetMsgID.C2G_HomePartyEatDishReq , NetMsgID.G2C_HomePartyEatDishRes },
     { NetMsgID.C2G_HomePartyGetAwardReq , NetMsgID.G2C_HomePartyGetAwardRes },
     { NetMsgID.C2G_HomePartyGetSugarReq , NetMsgID.G2C_HomePartyGetSugarRes },
     { NetMsgID.C2G_HomePartyGiftReq , NetMsgID.G2C_HomePartyGiftRes },
     { NetMsgID.C2G_HomePartyGuessNumberReq , NetMsgID.G2C_HomePartyGuessNumberRes },
     { NetMsgID.C2G_HomePartyJoinReq , NetMsgID.G2C_HomePartyJoinRes },
     { NetMsgID.C2G_HomePartyMakeWineReq , NetMsgID.G2C_HomePartyMakeWineRes },
     { NetMsgID.C2G_HomePartyMoveReq , NetMsgID.G2C_HomePartyMoveRes },
     { NetMsgID.C2G_HomePartyOpenReq , NetMsgID.G2C_HomePartyOpenRes },
     { NetMsgID.C2G_HomePartyPlaceFireworkReq , NetMsgID.G2C_HomePartyPlaceFireworkRes },
     { NetMsgID.C2G_HomePartyPlayerAtmosphereAwardReq , NetMsgID.G2C_HomePartyPlayerAtmosphereAwardRes },
     { NetMsgID.C2G_HomePartyPlayerCountReq , NetMsgID.G2C_HomePartyPlayerCountRes },
     { NetMsgID.C2G_HomePartyRejoinReq , NetMsgID.G2C_HomePartyRejoinRes },
     { NetMsgID.C2G_HomePartyScatterSugarReq , NetMsgID.G2C_HomePartyScatterSugarRes },
     { NetMsgID.C2G_HomePartySceneStateReq , NetMsgID.G2C_HomePartySceneStateRes },
     { NetMsgID.C2G_HomePartySubscribeReq , NetMsgID.G2C_HomePartySubscribeRes },
     { NetMsgID.C2G_HomeQuestFinishReq , NetMsgID.G2C_HomeQuestFinishRes },
     { NetMsgID.C2G_HomeRegionUnlockReq , NetMsgID.G2C_HomeRegionUnlockRes },
     { NetMsgID.C2G_HomeVisitCourtyardReq , NetMsgID.G2C_HomeVisitCourtyardRes },
     { NetMsgID.C2G_HomeVistorJoinReq , NetMsgID.G2C_HomeVistorJoinRes },
     { NetMsgID.C2G_HomeVistorSceneStateReq , NetMsgID.G2C_HomeVistorSceneStateRes },
     { NetMsgID.C2G_InviteAssistReq , NetMsgID.G2C_InviteAssistRes },
     { NetMsgID.C2G_InviteHelpSanXiaoReq , NetMsgID.G2C_InviteHelpSanXiaoRes },
     { NetMsgID.C2G_JoinGuardBossReq , NetMsgID.G2C_JoinGuardBossRes },
     { NetMsgID.C2G_KaiTianPaiUpStarsReq , NetMsgID.G2C_KaiTianPaiUpStarsRes },
     { NetMsgID.C2G_KangMieLvClearReq , NetMsgID.G2C_KangMieLvClearRes },
     { NetMsgID.C2G_KangMieLvUpSaveReq , NetMsgID.G2C_KangMieLvUpSaveRes },
     { NetMsgID.C2G_LockEquipmentReq , NetMsgID.G2C_LockEquipmentRes },
     { NetMsgID.C2G_LockKTPShopReq , NetMsgID.G2C_LockKTPShopRes },
     { NetMsgID.C2G_LockStampReq , NetMsgID.G2C_LockStampRes },
     { NetMsgID.C2G_Login , NetMsgID.G2C_Login },
     { NetMsgID.C2G_LvUpPlayerSkillBookReq , NetMsgID.G2C_LvUpPlayerSkillBookRes },
     { NetMsgID.C2G_LvUpPlayerSkillReq , NetMsgID.G2C_LvUpPlayerSkillRes },
     { NetMsgID.C2G_MingGeDrawOneCardReq , NetMsgID.G2C_MingGeDrawOneCardRes },
     { NetMsgID.C2G_MingGeDrawTenCardReq , NetMsgID.G2C_MingGeDrawTenCardRes },
     { NetMsgID.C2G_OneKeyGetQuestAwardReq , NetMsgID.G2C_OneKeyGetQuestAwardRes },
     { NetMsgID.C2G_OneKeyUPStarsReq , NetMsgID.G2C_OneKeyUPStarsRes },
     { NetMsgID.C2G_OneKeyUnequipGemReq , NetMsgID.G2C_OneKeyUnequipGemRes },
     { NetMsgID.C2G_PVEFloorReq , NetMsgID.G2C_PVEFloorRes },
     { NetMsgID.C2G_PVESanXiaoRankReq , NetMsgID.G2C_PVESanXiaoRankRes },
     { NetMsgID.C2G_PVPTypeSanXiaoEmbattleIndex , NetMsgID.G2C_PVPTypeSanXiaoEmbattleIndex },
     { NetMsgID.C2G_PayZeroMoneyReq , NetMsgID.G2C_PayZeroMoneyRes },
     { NetMsgID.C2G_PlayerGiftSysReadReq , NetMsgID.G2C_PlayerGiftSysReadRes },
     { NetMsgID.C2G_PlayerGiftSysZuiJinReq , NetMsgID.G2C_PlayerGiftSysZuiJinRes },
     { NetMsgID.C2G_PlayerLogin , NetMsgID.G2C_PlayerLogin },
     { NetMsgID.C2G_PlayerSummaryInfoReq , NetMsgID.G2C_PlayerSummaryInfoRes },
     { NetMsgID.C2G_PotentialAttrClearReq , NetMsgID.G2C_PotentialAttrClearRes },
     { NetMsgID.C2G_QiFuReq , NetMsgID.G2C_QiFuRes },
     { NetMsgID.C2G_QuitAssistLevelReq , NetMsgID.G2C_QuitAssistLevelRes },
     { NetMsgID.C2G_QuitLevelReq , NetMsgID.G2C_QuitLevelRes },
     { NetMsgID.C2G_ReadMailReq , NetMsgID.G2C_ReadMailRes },
     { NetMsgID.C2G_ReadSanXiaoRevInfo , NetMsgID.G2C_ReadSanXiaoRevInfo },
     { NetMsgID.C2G_RechargeGetFirstAwardReq , NetMsgID.G2C_RechargeGetFirstAwardRes },
     { NetMsgID.C2G_RechargeOrderCancelReq , NetMsgID.G2C_RechargeOrderCancelRes },
     { NetMsgID.C2G_RechargeOrderReq , NetMsgID.G2C_RechargeOrderRes },
     { NetMsgID.C2G_RechargeTotalMoneyGetAwardReq , NetMsgID.G2C_RechargeTotalMoneyGetAwardRes },
     { NetMsgID.C2G_RecommendFriendReq , NetMsgID.G2C_RecommendFriendRes },
     { NetMsgID.C2G_ReconnectReq , NetMsgID.G2C_ReconnectRes },
     { NetMsgID.C2G_RefreshArenaOppoent , NetMsgID.G2C_RefreshArenaOppoent },
     { NetMsgID.C2G_RefreshBookConfirmReq , NetMsgID.G2C_RefreshBookConfirmRes },
     { NetMsgID.C2G_RefreshBookReq , NetMsgID.G2C_RefreshBookRes },
     { NetMsgID.C2G_RefreshKTPShopReq , NetMsgID.G2C_RefreshKTPShopRes },
     { NetMsgID.C2G_RefreshRandStoreReq , NetMsgID.G2C_RefreshRandStoreRes },
     { NetMsgID.C2G_RefreshRingOppoentReq , NetMsgID.G2C_RefreshRingOppoentRes },
     { NetMsgID.C2G_RemoveBookReq , NetMsgID.G2C_RemoveBookRes },
     { NetMsgID.C2G_RemoveMailReq , NetMsgID.G2C_RemoveMailRes },
     { NetMsgID.C2G_ResolveItemReq , NetMsgID.G2C_ResolveItemRes },
     { NetMsgID.C2G_RevFriendPointReq , NetMsgID.G2C_RevFriendPointRes },
     { NetMsgID.C2G_RollMoneyTreeReq , NetMsgID.G2C_RollMoneyTreeRes },
     { NetMsgID.C2G_RollMoneyTreeTenReq , NetMsgID.G2C_RollMoneyTreeTenRes },
     { NetMsgID.C2G_SaveBeginnerGuidance , NetMsgID.G2C_SaveBeginnerGuidance },
     { NetMsgID.C2G_SaveEmbattleInfoReq , NetMsgID.G2C_SaveEmbattleInfoRes },
     { NetMsgID.C2G_SaveSanXiaoReq , NetMsgID.G2C_SaveSanXiaoRes },
     { NetMsgID.C2G_SellItemToSysReq , NetMsgID.G2C_SellItemToSysRes },
     { NetMsgID.C2G_SendFriendPointReq , NetMsgID.G2C_SendFriendPointRes },
     { NetMsgID.C2G_SendGiftToPlayerReq , NetMsgID.G2C_SendGiftToPlayerRes },
     { NetMsgID.C2G_ServerDataReq , NetMsgID.G2C_ServerDataRes },
     { NetMsgID.C2G_SetEmbattlePlayerSkillReq , NetMsgID.G2C_SetEmbattlePlayerSkillRes },
     { NetMsgID.C2G_SetMingGeWishReq , NetMsgID.G2C_SetMingGeWishRes },
     { NetMsgID.C2G_SetPlayerCustomHeadIconReq , NetMsgID.G2C_SetPlayerCustomHeadIconRes },
     { NetMsgID.C2G_SetPlayerHeadFrameIconReq , NetMsgID.G2C_SetPlayerHeadFrameIconRes },
     { NetMsgID.C2G_SetPlayerHeadIconReq , NetMsgID.G2C_SetPlayerHeadIconRes },
     { NetMsgID.C2G_SetPlayerLabelReq , NetMsgID.G2C_SetPlayerLabelRes },
     { NetMsgID.C2G_SetPlayerMoodReq , NetMsgID.G2C_SetPlayerMoodRes },
     { NetMsgID.C2G_SetPlayerSpacePhotoLikeReq , NetMsgID.G2C_SetPlayerSpacePhotoLikeRes },
     { NetMsgID.C2G_SetPlayerSpacePhotoReq , NetMsgID.G2C_SetPlayerSpacePhotoRes },
     { NetMsgID.C2G_SetPlayerSpaceVisitorActionReq , NetMsgID.G2C_SetPlayerSpaceVisitorActionRes },
     { NetMsgID.C2G_SetTargetGuardReq , NetMsgID.G2C_SetTargetGuardRes },
     { NetMsgID.C2G_SetXinYuanCardReq , NetMsgID.G2C_SetXinYuanCardRes },
     { NetMsgID.C2G_SetYMPWishReq , NetMsgID.G2C_SetYMPWishRes },
     { NetMsgID.C2G_ShangGuInfoViewReq , NetMsgID.G2C_ShangGuInfoViewRes },
     { NetMsgID.C2G_SignInReq , NetMsgID.G2C_SignInRes },
     { NetMsgID.C2G_SkillLvUpReq , NetMsgID.G2C_SkillLvUpRes },
     { NetMsgID.C2G_StampUpStarsReq , NetMsgID.G2C_StampUpStarsRes },
     { NetMsgID.C2G_SummonGodWeaponReq , NetMsgID.G2C_SummonGodWeaponRes },
     { NetMsgID.C2G_SummonHeroReq , NetMsgID.G2C_SummonHeroRes },
     { NetMsgID.C2G_SummonLingGenReq , NetMsgID.G2C_SummonLingGenRes },
     { NetMsgID.C2G_SwapKTSkillIndexReq , NetMsgID.G2C_SwapKTSkillIndexRes },
     { NetMsgID.C2G_SwapKaiTianPaiReq , NetMsgID.G2C_SwapKaiTianPaiRes },
     { NetMsgID.C2G_ThousandCardGetReq , NetMsgID.G2C_ThousandCardGetRes },
     { NetMsgID.C2G_ThousandDrawCardReq , NetMsgID.G2C_ThousandDrawCardRes },
     { NetMsgID.C2G_TowerDirectRewardReq , NetMsgID.G2C_TowerDirectRewardRes },
     { NetMsgID.C2G_TrialFormationSaveReq , NetMsgID.G2C_TrialFormationSaveRes },
     { NetMsgID.C2G_TrialGetBattleInfoReq , NetMsgID.G2C_TrialGetBattleInfoRes },
     { NetMsgID.C2G_TrialResetReq , NetMsgID.G2C_TrialResetRes },
     { NetMsgID.C2G_TrialTakeAwardReq , NetMsgID.G2C_TrialTakeAwardRes },
     { NetMsgID.C2G_TrialViewBattleReq , NetMsgID.G2C_TrialViewBattleRes },
     { NetMsgID.C2G_UPStarsReq , NetMsgID.G2C_UPStarsRes },
     { NetMsgID.C2G_UnequipAllKTReq , NetMsgID.G2C_UnequipAllKTRes },
     { NetMsgID.C2G_UnequipAnyReq , NetMsgID.G2C_UnequipAnyRes },
     { NetMsgID.C2G_UnequipGemReq , NetMsgID.G2C_UnequipGemRes },
     { NetMsgID.C2G_UnequipGodWeaponReq , NetMsgID.G2C_UnequipGodWeaponRes },
     { NetMsgID.C2G_UnequipKTReq , NetMsgID.G2C_UnequipKTRes },
     { NetMsgID.C2G_UnequipKTSkillIndexReq , NetMsgID.G2C_UnequipKTSkillIndexRes },
     { NetMsgID.C2G_UnequipStampReq , NetMsgID.G2C_UnequipStampRes },
     { NetMsgID.C2G_UnlockKaiTianTabIndexReq , NetMsgID.G2C_UnlockKaiTianTabIndexRes },
     { NetMsgID.C2G_UpdatePlayerSkillReq , NetMsgID.G2C_UpdatePlayerSkillRes },
     { NetMsgID.C2G_UseDaiXiaoDataReq , NetMsgID.G2C_UseDaiXiaoDataRes },
     { NetMsgID.C2G_UseHeroSkinReq , NetMsgID.G2C_UseHeroSkinRes },
     { NetMsgID.C2G_UseItemReq , NetMsgID.G2C_UseItemRes },
     { NetMsgID.C2G_UseKTSkillTabReq , NetMsgID.G2C_UseKTSkillTabRes },
     { NetMsgID.C2G_UsePlayerSkinReq , NetMsgID.G2C_UsePlayerSkinRes },
     { NetMsgID.C2G_UseWanNengChipReq , NetMsgID.G2C_UseWanNengChipRes },
     { NetMsgID.C2G_ViewEmbattleHeroInfoReq , NetMsgID.G2C_ViewEmbattleHeroInfoRes },
     { NetMsgID.C2G_ViewEmbattleReq , NetMsgID.G2C_ViewEmbattleRes },
     { NetMsgID.C2G_WorldMatchOpponentReq , NetMsgID.G2C_WorldMatchOpponentRes },
     { NetMsgID.C2G_WorldMatchPlayerBeBeatenNtfReq , NetMsgID.G2C_WorldMatchPlayerBeBeatenNtfRes },
     { NetMsgID.C2G_WorldMatchPlayerBeBeatenReq , NetMsgID.G2C_WorldMatchPlayerBeBeatenRes },
     { NetMsgID.C2G_XiXunDianZanReq , NetMsgID.G2C_XiXunDianZanRes },
     { NetMsgID.C2G_XingJunRewardReq , NetMsgID.G2C_XingJunRewardRes },
     { NetMsgID.C2G_YMPDrawOneCardReq , NetMsgID.G2C_YMPDrawOneCardRes },
     { NetMsgID.C2G_YMPDrawTenCardReq , NetMsgID.G2C_YMPDrawTenCardRes },
     { NetMsgID.G2C_GetDailyDealRewardReq , NetMsgID.G2C_GetDailyDealRewardRes },

    };
}
